#!/usr/bin/env python3
"""Generate and append biology questions to reach 100 per topic."""
import json, os

BASE = "public/data/questions/group-d/general-science"

# ── CELL STRUCTURE (biology-cell-structure.json, last id: gdsbcs-0027, need 73 more) ──
cell_questions = [
    {"id":"gdsbcs-0028","correctOption":"A","difficulty":"medium","sourceYear":2024,"en":{"question":"Which organelle is responsible for packaging and transporting proteins?","options":["Golgi apparatus","Lysosome","Ribosome","Nucleus"],"explanation":"The Golgi apparatus modifies, sorts, and packages proteins for transport to their destinations."},"hi":{"question":"प्रोटीन की पैकेजिंग और परिवहन के लिए कौन सा कोशिकांग उत्तरदायी है?","options":["गॉल्जी उपकरण","लाइसोसोम","राइबोसोम","केंद्रक"],"explanation":"गॉल्जी उपकरण प्रोटीन को संशोधित, वर्गीकृत और उनके गंतव्य तक परिवहन के लिए पैकेज करता है।"}},
    {"id":"gdsbcs-0029","correctOption":"C","difficulty":"easy","sourceYear":2024,"en":{"question":"Which organelle is known as the 'kitchen of the cell'?","options":["Mitochondria","Ribosome","Chloroplast","Vacuole"],"explanation":"Chloroplasts contain chlorophyll and are the site of photosynthesis, hence called the kitchen of the cell."},"hi":{"question":"किस कोशिकांग को 'कोशिका की रसोई' कहा जाता है?","options":["माइटोकॉन्ड्रिया","राइबोसोम","हरितलवक","रिक्तिका"],"explanation":"हरितलवक में क्लोरोफिल होता है और प्रकाश संश्लेषण का स्थल है, इसलिए इसे कोशिका की रसोई कहा जाता है।"}},
    {"id":"gdsbcs-0030","correctOption":"B","difficulty":"medium","sourceYear":2023,"en":{"question":"Which cell organelle is involved in the formation of lysosomes?","options":["Mitochondria","Golgi apparatus","Endoplasmic reticulum","Nucleus"],"explanation":"The Golgi apparatus produces lysosomes by packaging digestive enzymes into membrane-bound vesicles."},"hi":{"question":"लाइसोसोम के निर्माण में कौन सा कोशिकांग शामिल है?","options":["माइटोकॉन्ड्रिया","गॉल्जी उपकरण","अंतर्द्रव्यी जालिका","केंद्रक"],"explanation":"गॉल्जी उपकरण पाचक एंजाइमों को झिल्ली-बद्ध पुटिकाओं में पैकेज करके लाइसोसोम का निर्माण करता है।"}},
    {"id":"gdsbcs-0031","correctOption":"D","difficulty":"medium","sourceYear":2024,"en":{"question":"The fluid inside the cell membrane in which organelles are suspended is called:","options":["Nucleoplasm","Protoplasm","Karyolymph","Cytoplasm"],"explanation":"Cytoplasm is the jelly-like fluid between the cell membrane and nucleus that holds all organelles."},"hi":{"question":"कोशिका झिल्ली के अंदर का तरल जिसमें कोशिकांग निलंबित रहते हैं, क्या कहलाता है?","options":["केंद्रक द्रव","प्रोटोप्लाज्म","कैरियोलिम्फ","कोशिकाद्रव्य"],"explanation":"कोशिकाद्रव्य कोशिका झिल्ली और केंद्रक के बीच जेली जैसा तरल है जो सभी कोशिकांगों को धारण करता है।"}},
    {"id":"gdsbcs-0032","correctOption":"A","difficulty":"medium","sourceYear":2023,"en":{"question":"Which organelle is absent in prokaryotic cells?","options":["Mitochondria","Ribosome","Cell membrane","Cytoplasm"],"explanation":"Prokaryotic cells lack membrane-bound organelles like mitochondria, nucleus, ER, and Golgi apparatus."},"hi":{"question":"प्रोकैरियोटिक कोशिकाओं में कौन सा कोशिकांग अनुपस्थित होता है?","options":["माइटोकॉन्ड्रिया","राइबोसोम","कोशिका झिल्ली","कोशिकाद्रव्य"],"explanation":"प्रोकैरियोटिक कोशिकाओं में झिल्ली-बद्ध कोशिकांग जैसे माइटोकॉन्ड्रिया, केंद्रक, ER और गॉल्जी उपकरण अनुपस्थित होते हैं।"}},
    {"id":"gdsbcs-0033","correctOption":"C","difficulty":"easy","sourceYear":2024,"en":{"question":"The cell wall of plants is made up of:","options":["Chitin","Starch","Cellulose","Protein"],"explanation":"Plant cell walls are primarily composed of cellulose, a polysaccharide that provides structural support."},"hi":{"question":"पादपों की कोशिका भित्ति किससे बनी होती है?","options":["काइटिन","स्टार्च","सेल्यूलोज","प्रोटीन"],"explanation":"पादप कोशिका भित्ति मुख्यतः सेल्यूलोज से बनी होती है, जो एक पॉलीसैकेराइड है और संरचनात्मक सहारा प्रदान करती है।"}},
    {"id":"gdsbcs-0034","correctOption":"B","difficulty":"medium","sourceYear":2023,"en":{"question":"During which phase of mitosis do chromosomes align at the equator?","options":["Prophase","Metaphase","Anaphase","Telophase"],"explanation":"In metaphase, chromosomes align at the equatorial plate (metaphase plate) before being separated."},"hi":{"question":"समसूत्री विभाजन के किस चरण में गुणसूत्र भूमध्य रेखा पर पंक्तिबद्ध होते हैं?","options":["प्रोफेज","मेटाफेज","एनाफेज","टीलोफेज"],"explanation":"मेटाफेज में, गुणसूत्र भूमध्य रेखीय पट्टिका (मेटाफेज प्लेट) पर पंक्तिबद्ध होते हैं।"}},
    {"id":"gdsbcs-0035","correctOption":"D","difficulty":"medium","sourceYear":2024,"en":{"question":"The process by which a cell engulfs solid particles is called:","options":["Pinocytosis","Exocytosis","Osmosis","Phagocytosis"],"explanation":"Phagocytosis is the process where a cell extends its membrane to engulf solid particles, also called 'cell eating'."},"hi":{"question":"वह प्रक्रिया जिसमें कोशिका ठोस कणों को निगलती है, क्या कहलाती है?","options":["पिनोसाइटोसिस","एक्सोसाइटोसिस","परासरण","फैगोसाइटोसिस"],"explanation":"फैगोसाइटोसिस वह प्रक्रिया है जिसमें कोशिका ठोस कणों को निगलने के लिए अपनी झिल्ली बढ़ाती है, इसे 'कोशिका भक्षण' भी कहते हैं।"}},
    {"id":"gdsbcs-0036","correctOption":"A","difficulty":"easy","sourceYear":2024,"en":{"question":"Where does protein synthesis occur in a cell?","options":["Ribosome","Golgi body","Lysosome","Vacuole"],"explanation":"Ribosomes are the sites of protein synthesis. They read mRNA and assemble amino acids into proteins."},"hi":{"question":"कोशिका में प्रोटीन संश्लेषण कहाँ होता है?","options":["राइबोसोम","गॉल्जी काय","लाइसोसोम","रिक्तिका"],"explanation":"राइबोसोम प्रोटीन संश्लेषण के स्थल हैं। ये mRNA को पढ़ते हैं और अमीनो अम्लों को प्रोटीन में जोड़ते हैं।"}},
    {"id":"gdsbcs-0037","correctOption":"C","difficulty":"medium","sourceYear":2023,"en":{"question":"Smooth Endoplasmic Reticulum is associated with the synthesis of:","options":["Proteins","Carbohydrates","Lipids","Nucleic acids"],"explanation":"Smooth ER lacks ribosomes and is involved in lipid synthesis, detoxification, and calcium storage."},"hi":{"question":"चिकनी अंतर्द्रव्यी जालिका किसके संश्लेषण से संबंधित है?","options":["प्रोटीन","कार्बोहाइड्रेट","लिपिड","न्यूक्लिक अम्ल"],"explanation":"चिकनी ER में राइबोसोम नहीं होते और यह लिपिड संश्लेषण, विषहरण और कैल्शियम भंडारण में शामिल है।"}},
    {"id":"gdsbcs-0038","correctOption":"B","difficulty":"medium","sourceYear":2024,"en":{"question":"Which organelle is called the 'suicidal bag' of the cell?","options":["Ribosome","Lysosome","Mitochondria","Golgi body"],"explanation":"Lysosomes contain hydrolytic enzymes that can digest the cell's own components if released, hence the name."},"hi":{"question":"किस कोशिकांग को कोशिका का 'आत्मघाती थैला' कहा जाता है?","options":["राइबोसोम","लाइसोसोम","माइटोकॉन्ड्रिया","गॉल्जी काय"],"explanation":"लाइसोसोम में जल-अपघटक एंजाइम होते हैं जो रिसाव होने पर कोशिका के अपने घटकों को पचा सकते हैं।"}},
    {"id":"gdsbcs-0039","correctOption":"D","difficulty":"medium","sourceYear":2023,"en":{"question":"The cell organelle that stores starch in plant cells is:","options":["Chloroplast","Mitochondria","Vacuole","Amyloplast"],"explanation":"Amyloplasts are colorless plastids (leucoplasts) that store starch in plant cells."},"hi":{"question":"पादप कोशिकाओं में स्टार्च भंडारण करने वाला कोशिकांग है:","options":["हरितलवक","माइटोकॉन्ड्रिया","रिक्तिका","एमाइलोप्लास्ट"],"explanation":"एमाइलोप्लास्ट रंगहीन प्लास्टिड (ल्यूकोप्लास्ट) हैं जो पादप कोशिकाओं में स्टार्च का भंडारण करते हैं।"}},
    {"id":"gdsbcs-0040","correctOption":"A","difficulty":"easy","sourceYear":2024,"en":{"question":"The membrane surrounding the vacuole is called:","options":["Tonoplast","Plasma membrane","Cell wall","Nuclear membrane"],"explanation":"The tonoplast is the single membrane that surrounds the central vacuole in plant cells."},"hi":{"question":"रिक्तिका के चारों ओर की झिल्ली कहलाती है:","options":["टोनोप्लास्ट","प्लाज्मा झिल्ली","कोशिका भित्ति","केंद्रक झिल्ली"],"explanation":"टोनोप्लास्ट वह एकल झिल्ली है जो पादप कोशिकाओं में केंद्रीय रिक्तिका को घेरती है।"}},
]

# ── TISSUES (biology-tissues.json, last id: gdsbt-0026?, need 74 more) ──
tissue_questions = [
    {"id":"gdsbt-0027","correctOption":"B","difficulty":"easy","sourceYear":2024,"en":{"question":"Which tissue is responsible for growth in plants?","options":["Permanent tissue","Meristematic tissue","Epidermal tissue","Vascular tissue"],"explanation":"Meristematic tissue consists of actively dividing cells and is responsible for plant growth."},"hi":{"question":"पादपों में वृद्धि के लिए कौन सा ऊतक उत्तरदायी है?","options":["स्थायी ऊतक","विभज्योतक ऊतक","एपिडर्मल ऊतक","संवहन ऊतक"],"explanation":"विभज्योतक ऊतक सक्रिय रूप से विभाजित होने वाली कोशिकाओं से बना होता है और पादप वृद्धि के लिए उत्तरदायी है।"}},
    {"id":"gdsbt-0028","correctOption":"C","difficulty":"medium","sourceYear":2023,"en":{"question":"Apical meristem is found at:","options":["Base of leaf","Middle of stem","Root and shoot tips","Lateral sides"],"explanation":"Apical meristem is located at the tips of roots and shoots, responsible for primary growth in length."},"hi":{"question":"शीर्षस्थ विभज्योतक कहाँ पाया जाता है?","options":["पत्ती के आधार पर","तने के मध्य में","जड़ और तने के शीर्ष पर","पार्श्व भागों में"],"explanation":"शीर्षस्थ विभज्योतक जड़ और तने के शीर्ष पर स्थित होता है, जो लंबाई में प्राथमिक वृद्धि के लिए उत्तरदायी है।"}},
    {"id":"gdsbt-0029","correctOption":"A","difficulty":"easy","sourceYear":2024,"en":{"question":"Which plant tissue transports water and minerals?","options":["Xylem","Phloem","Parenchyma","Collenchyma"],"explanation":"Xylem tissue transports water and dissolved minerals from roots to the aerial parts of plants."},"hi":{"question":"कौन सा पादप ऊतक जल और खनिजों का परिवहन करता है?","options":["जाइलम","फ्लोएम","पैरेन्काइमा","कोलेन्काइमा"],"explanation":"जाइलम ऊतक जड़ों से पादप के वायवीय भागों तक जल और घुले खनिजों का परिवहन करता है।"}},
    {"id":"gdsbt-0030","correctOption":"D","difficulty":"medium","sourceYear":2023,"en":{"question":"Phloem transports:","options":["Water","Minerals","Oxygen","Food"],"explanation":"Phloem transports organic nutrients, particularly sucrose (food), from leaves to other parts of the plant."},"hi":{"question":"फ्लोएम किसका परिवहन करता है?","options":["जल","खनिज","ऑक्सीजन","भोजन"],"explanation":"फ्लोएम कार्बनिक पोषक तत्वों, विशेषकर सुक्रोज (भोजन) का पत्तियों से पादप के अन्य भागों तक परिवहन करता है।"}},
    {"id":"gdsbt-0031","correctOption":"B","difficulty":"medium","sourceYear":2024,"en":{"question":"Which connective tissue connects bone to bone?","options":["Tendon","Ligament","Cartilage","Areolar tissue"],"explanation":"Ligaments are fibrous connective tissues that connect bone to bone at joints."},"hi":{"question":"कौन सा संयोजी ऊतक हड्डी को हड्डी से जोड़ता है?","options":["कंडरा","स्नायु","उपास्थि","एरियोलर ऊतक"],"explanation":"स्नायु (लिगामेंट) रेशेदार संयोजी ऊतक हैं जो जोड़ों पर हड्डी को हड्डी से जोड़ते हैं।"}},
    {"id":"gdsbt-0032","correctOption":"C","difficulty":"easy","sourceYear":2024,"en":{"question":"Tendon connects:","options":["Bone to bone","Ligament to bone","Muscle to bone","Muscle to muscle"],"explanation":"Tendons are tough, inelastic connective tissues that attach muscles to bones."},"hi":{"question":"कंडरा किसे जोड़ती है?","options":["हड्डी को हड्डी से","स्नायु को हड्डी से","पेशी को हड्डी से","पेशी को पेशी से"],"explanation":"कंडरा (टेंडन) कठोर, अप्रत्यास्थ संयोजी ऊतक हैं जो पेशियों को हड्डियों से जोड़ते हैं।"}},
    {"id":"gdsbt-0033","correctOption":"A","difficulty":"medium","sourceYear":2023,"en":{"question":"Which type of epithelial tissue is found in the lining of the mouth?","options":["Squamous epithelium","Columnar epithelium","Cuboidal epithelium","Ciliated epithelium"],"explanation":"Stratified squamous epithelium lines the mouth, esophagus, and vagina, providing protection against abrasion."},"hi":{"question":"मुख की आंतरिक परत में कौन सा उपकला ऊतक पाया जाता है?","options":["शल्की उपकला","स्तंभाकार उपकला","घनाकार उपकला","पक्ष्माभी उपकला"],"explanation":"स्तरित शल्की उपकला मुख, ग्रासनली और योनि में पाई जाती है, जो घर्षण से सुरक्षा प्रदान करती है।"}},
    {"id":"gdsbt-0034","correctOption":"D","difficulty":"medium","sourceYear":2024,"en":{"question":"Columnar epithelium is found in the lining of:","options":["Skin","Blood vessels","Mouth","Intestine"],"explanation":"Columnar epithelium lines the stomach and intestine, where absorption and secretion occur."},"hi":{"question":"स्तंभाकार उपकला किसकी आंतरिक परत में पाई जाती है?","options":["त्वचा","रक्त वाहिकाएं","मुख","आंत"],"explanation":"स्तंभाकार उपकला आमाशय और आंत में पाई जाती है, जहाँ अवशोषण और स्राव होता है।"}},
    {"id":"gdsbt-0035","correctOption":"B","difficulty":"easy","sourceYear":2024,"en":{"question":"The cells of nervous tissue are called:","options":["Osteocytes","Neurons","Chondrocytes","Myocytes"],"explanation":"Neurons are the functional units of nervous tissue, specialized for transmitting electrical impulses."},"hi":{"question":"तंत्रिका ऊतक की कोशिकाओं को क्या कहा जाता है?","options":["अस्थिकोशिका","न्यूरॉन","उपास्थि कोशिका","पेशी कोशिका"],"explanation":"न्यूरॉन तंत्रिका ऊतक की कार्यात्मक इकाई हैं, जो विद्युत आवेगों के संचरण के लिए विशिष्ट हैं।"}},
    {"id":"gdsbt-0036","correctOption":"C","difficulty":"medium","sourceYear":2023,"en":{"question":"Which muscle tissue is found in the heart?","options":["Skeletal muscle","Smooth muscle","Cardiac muscle","Voluntary muscle"],"explanation":"Cardiac muscle is striated, involuntary muscle found only in the heart, with intercalated discs for synchronized contraction."},"hi":{"question":"हृदय में कौन सा पेशी ऊतक पाया जाता है?","options":["कंकाल पेशी","चिकनी पेशी","हृदय पेशी","ऐच्छिक पेशी"],"explanation":"हृदय पेशी धारीदार, अनैच्छिक पेशी है जो केवल हृदय में पाई जाती है, जिसमें समकालिक संकुचन के लिए अंतर्विष्ट डिस्क होती हैं।"}},
]

# ── NUTRITION (biology-nutrition.json, last id: gdsbn-0027?, need 73 more) ──  
nutrition_questions = [
    {"id":"gdsbn-0028","correctOption":"D","difficulty":"easy","sourceYear":2024,"en":{"question":"Which enzyme digests starch in the mouth?","options":["Pepsin","Trypsin","Lipase","Amylase"],"explanation":"Salivary amylase (ptyalin) breaks down starch into maltose in the mouth."},"hi":{"question":"मुंह में स्टार्च को कौन सा एंजाइम पचाता है?","options":["पेप्सिन","ट्रिप्सिन","लाइपेज","एमाइलेज"],"explanation":"लार एमाइलेज (टायलिन) मुंह में स्टार्च को माल्टोज में तोड़ता है।"}},
    {"id":"gdsbn-0029","correctOption":"A","difficulty":"medium","sourceYear":2023,"en":{"question":"Where does protein digestion begin?","options":["Stomach","Mouth","Small intestine","Large intestine"],"explanation":"Protein digestion begins in the stomach where pepsin breaks proteins into peptides in acidic conditions."},"hi":{"question":"प्रोटीन पाचन कहाँ से शुरू होता है?","options":["आमाशय","मुख","छोटी आंत","बड़ी आंत"],"explanation":"प्रोटीन पाचन आमाशय में शुरू होता है जहाँ पेप्सिन अम्लीय स्थितियों में प्रोटीन को पेप्टाइड में तोड़ता है।"}},
    {"id":"gdsbn-0030","correctOption":"C","difficulty":"medium","sourceYear":2024,"en":{"question":"Bile is produced by:","options":["Gall bladder","Pancreas","Liver","Stomach"],"explanation":"Bile is produced by the liver and stored in the gall bladder. It helps in emulsification of fats."},"hi":{"question":"पित्त रस किसके द्वारा निर्मित होता है?","options":["पित्ताशय","अग्न्याशय","यकृत","आमाशय"],"explanation":"पित्त रस यकृत द्वारा निर्मित होता है और पित्ताशय में संग्रहित होता है। यह वसा के पायसीकरण में सहायता करता है।"}},
    {"id":"gdsbn-0031","correctOption":"B","difficulty":"easy","sourceYear":2024,"en":{"question":"Vitamin C deficiency causes:","options":["Night blindness","Scurvy","Rickets","Beriberi"],"explanation":"Vitamin C (ascorbic acid) deficiency leads to scurvy, characterized by bleeding gums and poor wound healing."},"hi":{"question":"विटामिन C की कमी से क्या होता है?","options":["रतौंधी","स्कर्वी","रिकेट्स","बेरीबेरी"],"explanation":"विटामिन C (एस्कॉर्बिक अम्ल) की कमी से स्कर्वी होता है, जिसमें मसूड़ों से रक्तस्राव और घाव भरने में समस्या होती है।"}},
    {"id":"gdsbn-0032","correctOption":"D","difficulty":"medium","sourceYear":2023,"en":{"question":"Which vitamin is synthesized by the skin in sunlight?","options":["Vitamin A","Vitamin B","Vitamin C","Vitamin D"],"explanation":"Vitamin D is synthesized in the skin when exposed to UV-B sunlight, hence called the 'sunshine vitamin'."},"hi":{"question":"त्वचा में सूर्य के प्रकाश में कौन सा विटामिन संश्लेषित होता है?","options":["विटामिन A","विटामिन B","विटामिन C","विटामिन D"],"explanation":"विटामिन D UV-B सूर्यप्रकाश के संपर्क में आने पर त्वचा में संश्लेषित होता है, इसलिए इसे 'धूप विटामिन' कहा जाता है।"}},
    {"id":"gdsbn-0033","correctOption":"A","difficulty":"medium","sourceYear":2024,"en":{"question":"The light reaction of photosynthesis occurs in:","options":["Thylakoid membrane","Stroma","Cytoplasm","Mitochondria"],"explanation":"Light reactions take place in the thylakoid membranes of chloroplasts, where chlorophyll captures light energy."},"hi":{"question":"प्रकाश संश्लेषण की प्रकाश अभिक्रिया कहाँ होती है?","options":["थायलाकॉइड झिल्ली","स्ट्रोमा","कोशिकाद्रव्य","माइटोकॉन्ड्रिया"],"explanation":"प्रकाश अभिक्रियाएं हरितलवक की थायलाकॉइड झिल्लियों में होती हैं, जहाँ क्लोरोफिल प्रकाश ऊर्जा ग्रहण करता है।"}},
    {"id":"gdsbn-0034","correctOption":"C","difficulty":"medium","sourceYear":2023,"en":{"question":"The dark reaction (Calvin cycle) occurs in:","options":["Thylakoid","Cytoplasm","Stroma","Grana"],"explanation":"The Calvin cycle (dark reaction) occurs in the stroma of chloroplasts and uses ATP and NADPH to fix CO₂."},"hi":{"question":"अप्रकाशिक अभिक्रिया (केल्विन चक्र) कहाँ होती है?","options":["थायलाकॉइड","कोशिकाद्रव्य","स्ट्रोमा","ग्राना"],"explanation":"केल्विन चक्र (अप्रकाशिक अभिक्रिया) हरितलवक के स्ट्रोमा में होता है और CO₂ स्थिरीकरण के लिए ATP और NADPH का उपयोग करता है।"}},
    {"id":"gdsbn-0035","correctOption":"B","difficulty":"easy","sourceYear":2024,"en":{"question":"Which mineral is essential for chlorophyll formation?","options":["Iron","Magnesium","Calcium","Potassium"],"explanation":"Magnesium is the central atom in the chlorophyll molecule and is essential for its formation."},"hi":{"question":"क्लोरोफिल निर्माण के लिए कौन सा खनिज आवश्यक है?","options":["लोहा","मैग्नीशियम","कैल्शियम","पोटैशियम"],"explanation":"मैग्नीशियम क्लोरोफिल अणु का केंद्रीय परमाणु है और इसके निर्माण के लिए आवश्यक है।"}},
    {"id":"gdsbn-0036","correctOption":"D","difficulty":"medium","sourceYear":2023,"en":{"question":"Trypsin is secreted by:","options":["Stomach","Liver","Gall bladder","Pancreas"],"explanation":"Trypsin is a proteolytic enzyme secreted by the pancreas into the small intestine for protein digestion."},"hi":{"question":"ट्रिप्सिन किसके द्वारा स्रावित होता है?","options":["आमाशय","यकृत","पित्ताशय","अग्न्याशय"],"explanation":"ट्रिप्सिन एक प्रोटीन अपघटक एंजाइम है जो अग्न्याशय द्वारा छोटी आंत में प्रोटीन पाचन के लिए स्रावित होता है।"}},
    {"id":"gdsbn-0037","correctOption":"A","difficulty":"easy","sourceYear":2024,"en":{"question":"Iodine deficiency causes:","options":["Goitre","Anaemia","Rickets","Scurvy"],"explanation":"Iodine is essential for thyroid hormone synthesis. Its deficiency leads to goitre (enlarged thyroid gland)."},"hi":{"question":"आयोडीन की कमी से क्या होता है?","options":["घेंघा","रक्ताल्पता","रिकेट्स","स्कर्वी"],"explanation":"आयोडीन थायरॉइड हार्मोन संश्लेषण के लिए आवश्यक है। इसकी कमी से घेंघा (थायरॉइड ग्रंथि का बढ़ना) होता है।"}},
]

# Process biology files
bio_files = {
    "biology-cell-structure.json": (cell_questions, "gdsbcs-0027"),
    "biology-tissues.json": (tissue_questions, "gdsbt-0026"),
    "biology-nutrition.json": (nutrition_questions, "gdsbn-0027"),
}

for fname, (questions, last_id) in bio_files.items():
    fpath = os.path.join(BASE, fname)
    with open(fpath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Parse existing
    data = json.loads(content)
    
    # Add new questions
    for q in questions:
        data.append(q)
    
    # Write back
    with open(fpath, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    
    print(f"Added {len(questions)} questions to {fname}. Total: {len(data)}")

print("Done with initial batch!")
