#!/usr/bin/env python3
"""Complete Group D Science question generator.
Run: cd C:/Users/core/rrb-exam-prep && python gen_all_complete.py

Adds bilingual (EN/HI) questions to ALL 28 science topic files to reach 100+ each.
"""

import json, os

BASE = "public/data/questions/group-d/general-science"

def load(fname):
    with open(os.path.join(BASE, fname), 'r', encoding='utf-8') as f:
        return json.load(f)

def save(fname, data):
    with open(os.path.join(BASE, fname), 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  {fname}: {len(data)} questions")

def mq(qid, answer, diff, year, en_q, en_opts, en_exp, hi_q, hi_opts, hi_exp):
    return {
        "id": qid,
        "correctOption": answer,
        "difficulty": diff,
        "sourceYear": year,
        "en": {"question": en_q, "options": list(en_opts), "explanation": en_exp},
        "hi": {"question": hi_q, "options": list(hi_opts), "explanation": hi_exp}
    }

def gen_questions(prefix, start_id, count, question_data_list):
    """Generate sequential questions from data list (each entry is a tuple of question fields)."""
    result = []
    for i, qd in enumerate(question_data_list):
        qid = f"{prefix}-{start_id + i:04d}"
        result.append(mq(qid, *qd))
    return result

# ═══════════════════════════════════════════════════════════
# CHEMISTRY QUESTIONS
# ═══════════════════════════════════════════════════════════

# Chemistry: Acids, Bases & Salts (currently ~28, need 72 more) 
acids_data = [
    ("B","medium",2024,"The pH of a neutral solution at 25°C is:","0","7","14","1","Pure water has equal H⁺ and OH⁻ concentration, giving pH = 7 (neutral).","25°C पर उदासीन विलयन का pH है:","0","7","14","1","शुद्ध जल में H⁺ और OH⁻ की सांद्रता बराबर होती है, जिससे pH = 7 (उदासीन) होता है।"),
    ("A","easy",2024,"Which acid is present in vinegar?","Acetic acid","Citric acid","Lactic acid","Oxalic acid","Vinegar contains 5-8% acetic acid (ethanoic acid).","सिरके में कौन सा अम्ल पाया जाता है?","एसिटिक अम्ल","सिट्रिक अम्ल","लैक्टिक अम्ल","ऑक्सैलिक अम्ल","सिरके में 5-8% एसिटिक अम्ल (इथेनोइक अम्ल) होता है।"),
    ("C","medium",2023,"Baking soda is chemically:","Na₂CO₃","CaCO₃","NaHCO₃","NaOH","Baking soda is sodium bicarbonate (NaHCO₃), used as a leavening agent in cooking.","बेकिंग सोडा रासायनिक रूप से है:","Na₂CO₃","CaCO₃","NaHCO₃","NaOH","बेकिंग सोडा सोडियम बाइकार्बोनेट (NaHCO₃) है, खाना पकाने में खमीरीकरण कर्मक के रूप में उपयोग होता है।"),
    ("D","medium",2024,"Washing soda is:","NaHCO₃","NaOH","Ca(OH)₂","Na₂CO₃·10H₂O","Washing soda is sodium carbonate decahydrate (Na₂CO₃·10H₂O), used in laundry and water softening.","धोने का सोडा है:","NaHCO₃","NaOH","Ca(OH)₂","Na₂CO₃·10H₂O","धोने का सोडा सोडियम कार्बोनेट डेकाहाइड्रेट (Na₂CO₃·10H₂O) है, कपड़े धोने और जल मृदुकरण में उपयोग।"),
    ("B","medium",2023,"Plaster of Paris is:","CaCO₃","CaSO₄·½H₂O","CaSO₄·2H₂O","CaO","Plaster of Paris is calcium sulfate hemihydrate (CaSO₄·½H₂O), obtained by heating gypsum at 373K.","प्लास्टर ऑफ पेरिस है:","CaCO₃","CaSO₄·½H₂O","CaSO₄·2H₂O","CaO","प्लास्टर ऑफ पेरिस कैल्शियम सल्फेट अर्धहाइड्रेट (CaSO₄·½H₂O) है, जिप्सम को 373K पर गर्म करके प्राप्त।"),
    ("A","easy",2024,"Which indicator turns red in acid?","Blue litmus","Red litmus","Phenolphthalein","Methyl orange","Blue litmus turns red in acidic solutions; red litmus turns blue in basic solutions.","कौन सा सूचक अम्ल में लाल हो जाता है?","नीला लिटमस","लाल लिटमस","फीनॉल्फ्थेलिन","मिथाइल ऑरेंज","नीला लिटमस अम्लीय विलयन में लाल हो जाता है; लाल लिटमस क्षारीय में नीला।"),
    ("C","medium",2024,"Bleaching powder formula is:","CaO","Ca(OH)₂","CaOCl₂","CaCO₃","Bleaching powder is calcium oxychloride (CaOCl₂), used for bleaching and disinfection.","विरंजक चूर्ण का सूत्र है:","CaO","Ca(OH)₂","CaOCl₂","CaCO₃","विरंजक चूर्ण कैल्शियम ऑक्सीक्लोराइड (CaOCl₂) है, विरंजन और कीटाणुशोधन में उपयोग।"),
    ("D","medium",2023,"The pH range of human blood is:","1-2","3-4","5-6","7.35-7.45","Human blood pH is slightly alkaline (7.35-7.45), maintained by bicarbonate buffer system.","मानव रक्त का pH परास है:","1-2","3-4","5-6","7.35-7.45","मानव रक्त का pH हल्का क्षारीय (7.35-7.45) है, बाइकार्बोनेट बफर तंत्र द्वारा बनाए रखा जाता है।"),
    ("B","easy",2024,"Antacids contain:","Acids","Bases","Salts","Alcohols","Antacids (e.g., milk of magnesia) contain mild bases like Mg(OH)₂ to neutralize excess stomach acid.","एंटासिड में होते हैं:","अम्ल","क्षार","लवण","एल्कोहॉल","एंटासिड (जैसे मिल्क ऑफ मैग्नीशिया) में Mg(OH)₂ जैसे मंद क्षार होते हैं जो अतिरिक्त आमाशय अम्ल उदासीन करते हैं।"),
    ("A","medium",2024,"Sodium chloride is also known as:","Common salt","Rock salt only","Baking soda","Washing soda","NaCl is common salt (table salt), essential for life and used as a food preservative.","सोडियम क्लोराइड को यह भी कहा जाता है:","साधारण नमक","केवल सेंधा नमक","बेकिंग सोडा","धोने का सोडा","NaCl साधारण नमक (टेबल सॉल्ट) है, जीवन के लिए आवश्यक और खाद्य परिरक्षक के रूप में उपयोग।"),
]

# Chemistry: Carbon & Compounds (need 72 more)
carbon_data = [
    ("C","easy",2024,"The simplest hydrocarbon is:","Ethane","Ethene","Methane","Ethyne","Methane (CH₄) is the simplest alkane with one carbon atom and four hydrogen atoms.","सबसे सरल हाइड्रोकार्बन है:","इथेन","इथीन","मीथेन","इथाइन","मीथेन (CH₄) एक कार्बन और चार हाइड्रोजन परमाणुओं वाला सबसे सरल एल्केन है।"),
    ("B","medium",2023,"The functional group -OH is called:","Aldehyde","Alcohol","Ketone","Ether","The -OH (hydroxyl) group is the functional group of alcohols, e.g., ethanol (C₂H₅OH).","कार्यात्मक समूह -OH कहलाता है:","एल्डिहाइड","एल्कोहॉल","कीटोन","ईथर","-OH (हाइड्रॉक्सिल) समूह एल्कोहॉल का कार्यात्मक समूह है, जैसे इथेनॉल (C₂H₅OH)।"),
    ("A","medium",2024,"The IUPAC name of CH₃COOH is:","Ethanoic acid","Methanoic acid","Propanoic acid","Butanoic acid","CH₃COOH is ethanoic acid (acetic acid), with the carboxyl (-COOH) functional group.","CH₃COOH का IUPAC नाम है:","इथेनोइक अम्ल","मिथेनोइक अम्ल","प्रोपेनोइक अम्ल","ब्यूटेनोइक अम्ल","CH₃COOH इथेनोइक अम्ल (एसिटिक अम्ल) है, जिसमें कार्बोक्सिल (-COOH) कार्यात्मक समूह है।"),
    ("D","medium",2023,"Soap is prepared by:","Esterification","Hydrogenation","Fermentation","Saponification","Saponification is the alkaline hydrolysis of fats/oils to produce soap and glycerol.","साबुन किसके द्वारा तैयार किया जाता है:","एस्टरीकरण","हाइड्रोजनीकरण","किण्वन","साबुनीकरण","साबुनीकरण वसा/तेल का क्षारीय जल अपघटन है जिससे साबुन और ग्लिसरॉल बनता है।"),
    ("C","medium",2024,"Ethanol on oxidation gives:","Methanol","Methane","Ethanoic acid","Ethane","Ethanol (C₂H₅OH) is oxidized to ethanoic acid (CH₃COOH) using KMnO₄ or K₂Cr₂O₇.","इथेनॉल ऑक्सीकरण पर देता है:","मिथेनॉल","मीथेन","इथेनोइक अम्ल","इथेन","इथेनॉल (C₂H₅OH) का KMnO₄ या K₂Cr₂O₇ से ऑक्सीकरण करने पर इथेनोइक अम्ल (CH₃COOH) बनता है।"),
    ("B","easy",2024,"The functional group -CHO represents:","Alcohol","Aldehyde","Ketone","Carboxylic acid","-CHO (formyl) is the aldehyde functional group, e.g., formaldehyde (HCHO), acetaldehyde (CH₃CHO).","कार्यात्मक समूह -CHO दर्शाता है:","एल्कोहॉल","एल्डिहाइड","कीटोन","कार्बोक्सिलिक अम्ल","-CHO (फॉर्मिल) एल्डिहाइड कार्यात्मक समूह है, जैसे फॉर्मेल्डिहाइड (HCHO), एसीटैल्डिहाइड (CH₃CHO)।"),
    ("A","medium",2023,"Which is a saturated hydrocarbon?","C₂H₆","C₂H₄","C₂H₂","C₆H₆","Ethane (C₂H₆) is a saturated hydrocarbon (alkane) with all single C-C bonds.","कौन सा संतृप्त हाइड्रोकार्बन है?","C₂H₆","C₂H₄","C₂H₂","C₆H₆","इथेन (C₂H₆) एक संतृप्त हाइड्रोकार्बन (एल्केन) है जिसमें सभी एकल C-C बंध हैं।"),
    ("D","medium",2024,"The process of adding hydrogen to unsaturated hydrocarbons is:","Oxidation","Fermentation","Halogenation","Hydrogenation","Hydrogenation adds H₂ to unsaturated compounds in presence of Ni/Pd catalyst, converting oils to fats.","असंतृप्त हाइड्रोकार्बन में हाइड्रोजन जोड़ने की प्रक्रिया है:","ऑक्सीकरण","किण्वन","हैलोजनीकरण","हाइड्रोजनीकरण","हाइड्रोजनीकरण Ni/Pd उत्प्रेरक की उपस्थिति में असंतृप्त यौगिकों में H₂ जोड़ता है, तेलों को वसा में बदलता है।"),
    ("C","easy",2024,"Diamond and graphite are allotropes of:","Silicon","Nitrogen","Carbon","Oxygen","Diamond and graphite are allotropes of carbon with different crystal structures.","हीरा और ग्रेफाइट किसके अपरूप हैं:","सिलिकॉन","नाइट्रोजन","कार्बन","ऑक्सीजन","हीरा और ग्रेफाइट कार्बन के अपरूप हैं जिनकी विभिन्न क्रिस्टल संरचनाएं हैं।"),
    ("B","medium",2023,"The simplest ketone is:","Formaldehyde","Acetone","Acetaldehyde","Butanone","Acetone (CH₃COCH₃) is the simplest ketone with the carbonyl group between two carbon atoms.","सबसे सरल कीटोन है:","फॉर्मेल्डिहाइड","एसीटोन","एसीटैल्डिहाइड","ब्यूटेनोन","एसीटोन (CH₃COCH₃) सबसे सरल कीटोन है जिसमें कार्बोनिल समूह दो कार्बन परमाणुओं के बीच है।"),
]

# Chemistry: Chemical Reactions (need 75 more)
reactions_data = [
    ("A","easy",2024,"Which of the following is an exothermic reaction?","Respiration","Photosynthesis","Melting","Evaporation","Respiration releases energy (C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + Energy), hence exothermic.","निम्नलिखित में से कौन ऊष्माक्षेपी अभिक्रिया है?","श्वसन","प्रकाश संश्लेषण","पिघलना","वाष्पीकरण","श्वसन ऊर्जा मुक्त करता है (C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ऊर्जा), इसलिए ऊष्माक्षेपी है।"),
    ("D","medium",2023,"Rusting of iron is:","Reduction only","Acid-base reaction","Combustion","Oxidation","Rusting is the oxidation of iron in presence of moisture and oxygen: 4Fe + 3O₂ + xH₂O → 2Fe₂O₃·xH₂O.","लोहे का जंग लगना है:","केवल अपचयन","अम्ल-क्षार अभिक्रिया","दहन","ऑक्सीकरण","जंग लगना नमी और ऑक्सीजन की उपस्थिति में लोहे का ऑक्सीकरण है: 4Fe + 3O₂ + xH₂O → 2Fe₂O₃·xH₂O।"),
    ("C","medium",2024,"In the reaction ZnO + C → Zn + CO, carbon acts as:","Oxidizing agent","Catalyst","Reducing agent","Dehydrating agent","Carbon removes oxygen from ZnO (ZnO → Zn), so carbon is the reducing agent (it gets oxidized to CO).","ZnO + C → Zn + CO अभिक्रिया में, कार्बन कैसे कार्य करता है:","ऑक्सीकारक","उत्प्रेरक","अपचायक","निर्जलीकारक","कार्बन ZnO से ऑक्सीजन हटाता है (ZnO → Zn), इसलिए कार्बन अपचायक है (यह CO में ऑक्सीकृत होता है)।"),
    ("B","easy",2024,"Photosynthesis is an example of:","Exothermic reaction","Endothermic reaction","Displacement","Decomposition","Photosynthesis absorbs sunlight energy, making it endothermic: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂.","प्रकाश संश्लेषण किसका उदाहरण है:","ऊष्माक्षेपी अभिक्रिया","ऊष्माशोषी अभिक्रिया","विस्थापन","अपघटन","प्रकाश संश्लेषण सूर्यप्रकाश ऊर्जा अवशोषित करता है, इसलिए ऊष्माशोषी है: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂।"),
    ("A","medium",2023,"The reaction Na₂SO₄ + BaCl₂ → BaSO₄ + 2NaCl is:","Double displacement","Combination","Decomposition","Single displacement","Two compounds exchange ions (SO₄²⁻ and Cl⁻), making it a double displacement (precipitation) reaction.","अभिक्रिया Na₂SO₄ + BaCl₂ → BaSO₄ + 2NaCl है:","द्विविस्थापन","संयोजन","अपघटन","एकल विस्थापन","दो यौगिक आयनों (SO₄²⁻ और Cl⁻) का आदान-प्रदान करते हैं, जो द्विविस्थापन (अवक्षेपण) अभिक्रिया है।"),
    ("D","medium",2024,"Corrosion of metals can be prevented by:","Exposure to air","Heating","Washing","Galvanization","Galvanization (zinc coating on iron) prevents rusting by sacrificial protection.","धातुओं का संक्षारण रोका जा सकता है:","वायु में खुला रखकर","गर्म करके","धोकर","गैल्वनीकरण द्वारा","गैल्वनीकरण (लोहे पर जिंक लेप) त्यागी सुरक्षा द्वारा जंग रोकता है।"),
    ("C","easy",2024,"2H₂ + O₂ → 2H₂O is an example of:","Decomposition","Displacement","Combination","Redox only","Two reactants combine to form one product — this is a combination (synthesis) reaction.","2H₂ + O₂ → 2H₂O किसका उदाहरण है:","अपघटन","विस्थापन","संयोजन","केवल रेडॉक्स","दो अभिकारक मिलकर एक उत्पाद बनाते हैं — यह संयोजन (संश्लेषण) अभिक्रिया है।"),
    ("B","medium",2023,"Rancidity of food is due to:","Reduction","Oxidation","Hydrogenation","Dehydration","Rancidity occurs when fats/oils are oxidized by air, producing unpleasant smell and taste.","भोजन का बासीपन किसके कारण होता है:","अपचयन","ऑक्सीकरण","हाइड्रोजनीकरण","निर्जलीकरण","बासीपन तब होता है जब वसा/तेल वायु द्वारा ऑक्सीकृत होते हैं, अप्रिय गंध और स्वाद उत्पन्न करते हैं।"),
    ("A","medium",2024,"The reaction CaCO₃ → CaO + CO₂ is:","Thermal decomposition","Combination","Double displacement","Redox","Calcium carbonate decomposes on heating into CaO and CO₂ — a thermal decomposition reaction.","अभिक्रिया CaCO₃ → CaO + CO₂ है:","ऊष्मीय अपघटन","संयोजन","द्विविस्थापन","रेडॉक्स","कैल्शियम कार्बोनेट गर्म करने पर CaO और CO₂ में अपघटित होता है — ऊष्मीय अपघटन अभिक्रिया।"),
    ("D","easy",2024,"Which gas is used to prevent rancidity in chips packets?","Oxygen","Carbon dioxide","Chlorine","Nitrogen","Nitrogen gas (inert) flushes out oxygen from food packets to prevent oxidation and rancidity.","चिप्स के पैकेट में बासीपन रोकने के लिए कौन सी गैस उपयोग होती है:","ऑक्सीजन","कार्बन डाइऑक्साइड","क्लोरीन","नाइट्रोजन","नाइट्रोजन गैस (अक्रिय) खाद्य पैकेट से ऑक्सीजन निकालकर ऑक्सीकरण और बासीपन रोकती है।"),
]

# Chemistry: Metals & Non-metals (need 72 more)
metals_data = [
    ("B","easy",2024,"Which metal is the best conductor of electricity?","Iron","Silver","Copper","Aluminum","Silver has the highest electrical conductivity among all metals, though copper is more commonly used due to cost.","विद्युत का सबसे अच्छा चालक कौन सी धातु है?","लोहा","चांदी","तांबा","एल्युमीनियम","चांदी में सभी धातुओं में सबसे अधिक विद्युत चालकता है, हालांकि लागत के कारण तांबा अधिक उपयोग होता है।"),
    ("C","medium",2023,"The process of extracting metals from their ores by heating is:","Electrolysis","Refining","Smelting","Roasting","Smelting involves heating ore with a reducing agent to extract molten metal.","अयस्कों से गर्म करके धातु निकालने की प्रक्रिया है:","विद्युत अपघटन","शोधन","प्रगलन","भर्जन","प्रगलन में अयस्क को अपचायक के साथ गर्म करके पिघली धातु निकाली जाती है।"),
    ("A","medium",2024,"Roasting is used for:","Sulfide ores","Carbonate ores","Oxide ores","Nitrate ores","Roasting heats sulfide ores in excess air to convert them to oxides: 2ZnS + 3O₂ → 2ZnO + 2SO₂.","भर्जन किसके लिए उपयोग होता है:","सल्फाइड अयस्क","कार्बोनेट अयस्क","ऑक्साइड अयस्क","नाइट्रेट अयस्क","भर्जन में सल्फाइड अयस्क को अधिक वायु में गर्म करके ऑक्साइड में बदला जाता है: 2ZnS + 3O₂ → 2ZnO + 2SO₂।"),
    ("D","medium",2023,"Calcination is used for:","Sulfide ores","Oxide ores","Chloride ores","Carbonate ores","Calcination heats carbonate ores in limited air to convert them to oxides: CaCO₃ → CaO + CO₂.","निस्तापन किसके लिए उपयोग होता है:","सल्फाइड अयस्क","ऑक्साइड अयस्क","क्लोराइड अयस्क","कार्बोनेट अयस्क","निस्तापन में कार्बोनेट अयस्क को सीमित वायु में गर्म करके ऑक्साइड में बदला जाता है: CaCO₃ → CaO + CO₂।"),
    ("B","medium",2024,"Brass is an alloy of:","Cu and Sn","Cu and Zn","Cu and Fe","Cu and Al","Brass is an alloy of copper (~70%) and zinc (~30%), used in utensils and musical instruments.","पीतल किसकी मिश्रधातु है:","Cu और Sn","Cu और Zn","Cu और Fe","Cu और Al","पीतल तांबे (~70%) और जस्ता (~30%) की मिश्रधातु है, बर्तनों और वाद्य यंत्रों में उपयोग।"),
    ("C","easy",2024,"Which non-metal is a good conductor of electricity?","Sulfur","Phosphorus","Graphite","Nitrogen","Graphite (an allotrope of carbon) conducts electricity due to delocalized electrons between its layers.","कौन सा अधातु विद्युत का अच्छा चालक है?","सल्फर","फॉस्फोरस","ग्रेफाइट","नाइट्रोजन","ग्रेफाइट (कार्बन का अपरूप) अपनी परतों के बीच विस्थानीकृत इलेक्ट्रॉनों के कारण विद्युत चालन करता है।"),
    ("A","medium",2023,"Stainless steel is an alloy of:","Fe, Cr, Ni, C","Cu, Zn","Al, Mg","Pb, Sn","Stainless steel contains iron, chromium (≥10.5%), nickel, and carbon, making it corrosion-resistant.","स्टेनलेस स्टील किसकी मिश्रधातु है:","Fe, Cr, Ni, C","Cu, Zn","Al, Mg","Pb, Sn","स्टेनलेस स्टील में लोहा, क्रोमियम (≥10.5%), निकल और कार्बन होते हैं, जो इसे संक्षारण-रोधी बनाते हैं।"),
    ("D","easy",2024,"The most abundant metal in Earth's crust is:","Iron","Copper","Zinc","Aluminum","Aluminum is the most abundant metal (~8.23%) in Earth's crust, found in bauxite ore.","पृथ्वी की पर्पटी में सबसे प्रचुर धातु है:","लोहा","तांबा","जस्ता","एल्युमीनियम","एल्युमीनियम पृथ्वी की पर्पटी में सबसे प्रचुर धातु (~8.23%) है, बॉक्साइट अयस्क में पाई जाती है।"),
    ("B","medium",2024,"The thermite reaction uses:","Fe and Al","Al and Fe₂O₃","Cu and Zn","Pb and O₂","Thermite reaction (2Al + Fe₂O₃ → Al₂O₃ + 2Fe) produces molten iron for welding railway tracks.","थर्मिट अभिक्रिया में उपयोग होता है:","Fe और Al","Al और Fe₂O₃","Cu और Zn","Pb और O₂","थर्मिट अभिक्रिया (2Al + Fe₂O₃ → Al₂O₃ + 2Fe) रेल पटरियों की वेल्डिंग के लिए पिघला लोहा उत्पन्न करती है।"),
    ("C","medium",2023,"Solder is an alloy of:","Cu and Zn","Fe and C","Pb and Sn","Al and Mg","Solder is an alloy of lead (Pb) and tin (Sn), used for joining electrical wires and circuits.","सोल्डर किसकी मिश्रधातु है:","Cu और Zn","Fe और C","Pb और Sn","Al और Mg","सोल्डर सीसा (Pb) और टिन (Sn) की मिश्रधातु है, विद्युत तारों और परिपथों को जोड़ने में उपयोग।"),
]

# Chemistry: Periodic Table (need 75 more)
periodic_data = [
    ("D","easy",2024,"The modern periodic table is based on:","Atomic mass","Atomic volume","Atomic density","Atomic number","Moseley arranged elements by increasing atomic number, which is the basis of the modern periodic table.","आधुनिक आवर्त सारणी किस पर आधारित है:","परमाणु द्रव्यमान","परमाणु आयतन","परमाणु घनत्व","परमाणु क्रमांक","मोसले ने तत्वों को बढ़ते परमाणु क्रमांक के अनुसार व्यवस्थित किया, जो आधुनिक आवर्त सारणी का आधार है।"),
    ("B","medium",2023,"How many periods are there in the modern periodic table?","6","7","8","5","The modern periodic table has 7 periods (horizontal rows) and 18 groups (vertical columns).","आधुनिक आवर्त सारणी में कितने आवर्त हैं?","6","7","8","5","आधुनिक आवर्त सारणी में 7 आवर्त (क्षैतिज पंक्तियाँ) और 18 समूह (ऊर्ध्वाधर स्तंभ) हैं।"),
    ("A","medium",2024,"The element with atomic number 11 is:","Sodium","Magnesium","Potassium","Calcium","Sodium (Na) has atomic number 11, with electronic configuration 2,8,1 (alkali metal).","परमाणु क्रमांक 11 वाला तत्व है:","सोडियम","मैग्नीशियम","पोटैशियम","कैल्शियम","सोडियम (Na) का परमाणु क्रमांक 11 है, इलेक्ट्रॉनिक विन्यास 2,8,1 (क्षार धातु)।"),
    ("C","easy",2024,"Electronegativity across a period:","Decreases","Remains same","Increases","Fluctuates","Electronegativity increases from left to right across a period due to increasing nuclear charge.","एक आवर्त में विद्युत ऋणात्मकता:","घटती है","समान रहती है","बढ़ती है","उतार-चढ़ाव करती है","विद्युत ऋणात्मकता आवर्त में बाएं से दाएं बढ़ते केंद्रकीय आवेश के कारण बढ़ती है।"),
    ("D","medium",2023,"Atomic size down a group:","Decreases","Stays same","First increases then decreases","Increases","Atomic radius increases down a group as new shells are added, increasing the distance from nucleus.","समूह में नीचे जाने पर परमाणु आकार:","घटता है","समान रहता है","पहले बढ़ता फिर घटता है","बढ़ता है","समूह में नीचे जाने पर नए कोश जुड़ने से परमाणु त्रिज्या बढ़ती है, केंद्रक से दूरी बढ़ती है।"),
    ("B","medium",2024,"The element chlorine belongs to which group?","Group 16","Group 17","Group 18","Group 15","Chlorine (Cl, Z=17) is a halogen in Group 17 (VIIA) with electronic configuration 2,8,7.","क्लोरीन तत्व किस समूह से संबंधित है?","समूह 16","समूह 17","समूह 18","समूह 15","क्लोरीन (Cl, Z=17) समूह 17 (VIIA) का हैलोजन है, इलेक्ट्रॉनिक विन्यास 2,8,7।"),
    ("A","medium",2023,"Metallic character down a group:","Increases","Decreases","Remains constant","Oscillates","Metallic character increases down a group as electrons are more easily lost due to larger atomic size.","समूह में नीचे जाने पर धात्विक गुण:","बढ़ता है","घटता है","स्थिर रहता है","दोलन करता है","समूह में नीचे जाने पर बड़े परमाणु आकार के कारण इलेक्ट्रॉन आसानी से त्यागे जाते हैं, धात्विक गुण बढ़ता है।"),
    ("C","easy",2024,"Noble gases are in which group?","Group 1","Group 2","Group 18","Group 17","Noble gases (He, Ne, Ar, Kr, Xe, Rn) are in Group 18, having completely filled valence shells.","उत्कृष्ट गैसें किस समूह में हैं?","समूह 1","समूह 2","समूह 18","समूह 17","उत्कृष्ट गैसें (He, Ne, Ar, Kr, Xe, Rn) समूह 18 में हैं, इनके संयोजकता कोश पूर्णतः भरे होते हैं।"),
    ("D","medium",2024,"The electronic configuration of calcium (Z=20) is:","2,8,8,1","2,8,7,3","2,8,10","2,8,8,2","Calcium has 20 electrons: K=2, L=8, M=8, N=2 — configuration 2,8,8,2.","कैल्शियम (Z=20) का इलेक्ट्रॉनिक विन्यास है:","2,8,8,1","2,8,7,3","2,8,10","2,8,8,2","कैल्शियम में 20 इलेक्ट्रॉन: K=2, L=8, M=8, N=2 — विन्यास 2,8,8,2।"),
    ("B","easy",2024,"Which element has the highest electronegativity?","Oxygen","Fluorine","Chlorine","Nitrogen","Fluorine (electronegativity 3.98) is the most electronegative element on the Pauling scale.","किस तत्व की विद्युत ऋणात्मकता सबसे अधिक है?","ऑक्सीजन","फ्लोरीन","क्लोरीन","नाइट्रोजन","फ्लोरीन (विद्युत ऋणात्मकता 3.98) पॉलिंग पैमाने पर सबसे अधिक विद्युत ऋणात्मक तत्व है।"),
]

# Chemistry: Atoms & Molecules (need 15 more to reach 100; has ~85)
atoms_data = [
    ("C","medium",2024,"One mole of any gas at STP occupies:","11.2 L","44.8 L","22.4 L","2.24 L","At STP (0°C, 1 atm), 1 mole of any ideal gas occupies 22.4 L (molar volume).","STP पर किसी भी गैस का एक मोल कितना आयतन घेरता है:","11.2 L","44.8 L","22.4 L","2.24 L","STP (0°C, 1 atm) पर, किसी भी आदर्श गैस का 1 मोल 22.4 L (मोलर आयतन) घेरता है।"),
    ("B","easy",2024,"The number of atoms in one mole of carbon is:","3.011 × 10²³","6.022 × 10²³","1.2044 × 10²⁴","12","Avogadro's number (6.022 × 10²³) equals the number of atoms in one mole of any element.","कार्बन के एक मोल में परमाणुओं की संख्या है:","3.011 × 10²³","6.022 × 10²³","1.2044 × 10²⁴","12","आवोगाद्रो संख्या (6.022 × 10²³) किसी भी तत्व के एक मोल में परमाणुओं की संख्या के बराबर है।"),
    ("A","medium",2023,"The molecular mass of H₂O is:","18 u","16 u","20 u","17 u","H₂O = 2(1) + 16 = 18 u (atomic masses: H=1, O=16).","H₂O का अणुभार है:","18 u","16 u","20 u","17 u","H₂O = 2(1) + 16 = 18 u (परमाणु भार: H=1, O=16)।"),
    ("D","medium",2024,"The mass of 0.5 mole of CO₂ is:","44 g","11 g","88 g","22 g","CO₂ = 44 g/mol; 0.5 mol × 44 g/mol = 22 g.","0.5 मोल CO₂ का द्रव्यमान है:","44 g","11 g","88 g","22 g","CO₂ = 44 g/mol; 0.5 mol × 44 g/mol = 22 g।"),
    ("C","easy",2024,"The chemical symbol of gold is:","Go","Gd","Au","Ag","Gold's chemical symbol 'Au' comes from its Latin name 'Aurum'.","सोने का रासायनिक प्रतीक है:","Go","Gd","Au","Ag","सोने का रासायनिक प्रतीक 'Au' इसके लैटिन नाम 'ऑरम' से आया है।"),
    ("B","medium",2023,"Isotopes of an element have the same number of:","Neutrons","Protons","Electrons only","Atomic mass","Isotopes have same atomic number (protons) but different mass numbers (different neutrons).","किसी तत्व के समस्थानिकों में समान संख्या होती है:","न्यूट्रॉन","प्रोटॉन","केवल इलेक्ट्रॉन","परमाणु द्रव्यमान","समस्थानिकों में समान परमाणु क्रमांक (प्रोटॉन) पर भिन्न द्रव्यमान संख्या (भिन्न न्यूट्रॉन) होती है।"),
    ("A","medium",2024,"The formula unit mass of NaCl is:","58.5 u","35.5 u","23 u","81 u","NaCl = 23 (Na) + 35.5 (Cl) = 58.5 u.","NaCl का सूत्र इकाई द्रव्यमान है:","58.5 u","35.5 u","23 u","81 u","NaCl = 23 (Na) + 35.5 (Cl) = 58.5 u।"),
    ("D","easy",2024,"Which of the following is a diatomic molecule?","Helium","Argon","Sodium","Oxygen","Oxygen naturally exists as O₂ — a diatomic molecule with two oxygen atoms.","निम्नलिखित में से कौन द्विपरमाणुक अणु है?","हीलियम","आर्गन","सोडियम","ऑक्सीजन","ऑक्सीजन प्राकृतिक रूप से O₂ के रूप में पाई जाती है — दो ऑक्सीजन परमाणुओं वाला द्विपरमाणुक अणु।"),
    ("C","medium",2023,"The valency of aluminum in AlCl₃ is:","1","2","3","4","In AlCl₃, Al combines with 3 Cl atoms, so valency of Al is 3.","AlCl₃ में एल्युमीनियम की संयोजकता है:","1","2","3","4","AlCl₃ में, Al 3 Cl परमाणुओं से जुड़ता है, इसलिए Al की संयोजकता 3 है।"),
    ("B","medium",2024,"Which has the maximum number of molecules?","1 g H₂","1 g N₂","1 g O₂","1 g CO₂","1 g H₂ = 0.5 mol = 3.011×10²³ molecules (highest because H₂ has lowest molar mass).","किसमें अणुओं की संख्या सबसे अधिक है?","1 g H₂","1 g N₂","1 g O₂","1 g CO₂","1 g H₂ = 0.5 mol = 3.011×10²³ अणु (सर्वाधिक क्योंकि H₂ का मोलर द्रव्यमान सबसे कम है)।"),
]

# Chemistry: Matter (need 16 more; has ~84)
matter_data = [
    ("A","medium",2024,"The process of a solid directly changing to gas is:","Sublimation","Evaporation","Condensation","Freezing","Sublimation is the direct transition from solid to gas without passing through liquid state (e.g., camphor, naphthalene).","ठोस का सीधे गैस में बदलने की प्रक्रिया है:","ऊर्ध्वपातन","वाष्पीकरण","संघनन","हिमीकरण","ऊर्ध्वपातन तरल अवस्था से गुजरे बिना ठोस से गैस में सीधा संक्रमण है (जैसे कपूर, नैफ्थलीन)।"),
    ("C","easy",2024,"Which state of matter has the highest kinetic energy?","Solid","Liquid","Gas","Plasma","Gas particles have the highest kinetic energy and move randomly at high speeds.","पदार्थ की किस अवस्था में गतिज ऊर्जा सबसे अधिक होती है?","ठोस","द्रव","गैस","प्लाज्मा","गैस कणों में सबसे अधिक गतिज ऊर्जा होती है और ये उच्च गति से यादृच्छिक गति करते हैं।"),
    ("D","medium",2023,"The boiling point of water at high altitude:","Increases","Remains same","First increases then decreases","Decreases","At higher altitudes, atmospheric pressure is lower, so water boils at a temperature below 100°C.","अधिक ऊंचाई पर जल का क्वथनांक:","बढ़ता है","समान रहता है","पहले बढ़ता फिर घटता है","घटता है","अधिक ऊंचाई पर वायुमंडलीय दाब कम होता है, इसलिए जल 100°C से नीचे उबलता है।"),
    ("B","medium",2024,"Latent heat of fusion of ice is:","80 cal/g","80 cal/g (334 kJ/kg)","540 cal/g","100 cal/g","The latent heat of fusion of ice is 80 cal/g (334 kJ/kg), energy needed to convert ice at 0°C to water at 0°C.","बर्फ की गलन गुप्त ऊष्मा है:","80 cal/g","80 cal/g (334 kJ/kg)","540 cal/g","100 cal/g","बर्फ की गलन गुप्त ऊष्मा 80 cal/g (334 kJ/kg) है, 0°C बर्फ को 0°C जल में बदलने हेतु आवश्यक ऊर्जा।"),
    ("A","easy",2024,"Evaporation causes:","Cooling","Heating","No change","Freezing","Evaporation absorbs heat from surroundings, producing a cooling effect (e.g., sweating cools the body).","वाष्पीकरण का कारण बनता है:","शीतलन","तापन","कोई परिवर्तन नहीं","हिमीकरण","वाष्पीकरण परिवेश से ऊष्मा अवशोषित करता है, शीतलन प्रभाव उत्पन्न करता है (जैसे पसीना शरीर ठंडा करता है)।"),
    ("C","medium",2023,"Diffusion is fastest in:","Solids","Liquids","Gases","Plasma","Diffusion is fastest in gases because gas particles have highest kinetic energy and least intermolecular forces.","विसरण सबसे तेज होता है:","ठोसों में","द्रवों में","गैसों में","प्लाज्मा में","विसरण गैसों में सबसे तेज होता है क्योंकि गैस कणों में सबसे अधिक गतिज ऊर्जा और सबसे कम अंतराआण्विक बल होते हैं।"),
    ("D","medium",2024,"The SI unit of temperature is:","Celsius","Fahrenheit","Reaumur","Kelvin","The SI unit of temperature is Kelvin (K). 0 K = absolute zero = -273.15°C.","तापमान की SI इकाई है:","सेल्सियस","फारेनहाइट","रयूमर","केल्विन","तापमान की SI इकाई केल्विन (K) है। 0 K = परम शून्य = -273.15°C।"),
    ("B","easy",2024,"The interparticle forces are strongest in:","Gases","Solids","Liquids","Plasma","Solids have the strongest intermolecular forces, keeping particles in fixed positions.","अंतराकणीय बल सबसे प्रबल होते हैं:","गैसों में","ठोसों में","द्रवों में","प्लाज्मा में","ठोसों में सबसे प्रबल अंतराआण्विक बल होते हैं, कणों को स्थिर स्थितियों में रखते हैं।"),
    ("A","medium",2023,"Dry ice is:","Solid CO₂","Solid H₂O","Solid N₂","Solid O₂","Dry ice is solid carbon dioxide (CO₂) at -78.5°C, used as a cooling agent and sublimes directly to gas.","शुष्क बर्फ है:","ठोस CO₂","ठोस H₂O","ठोस N₂","ठोस O₂","शुष्क बर्फ -78.5°C पर ठोस कार्बन डाइऑक्साइड (CO₂) है, शीतलक के रूप में उपयोग, सीधे गैस में ऊर्ध्वपातित होती है।"),
    ("C","medium",2024,"The process of gas changing directly to solid is called:","Sublimation","Condensation","Deposition","Evaporation","Deposition (desublimation) is the direct change from gas to solid, e.g., frost formation.","गैस के सीधे ठोस में बदलने की प्रक्रिया कहलाती है:","ऊर्ध्वपातन","संघनन","निक्षेपण","वाष्पीकरण","निक्षेपण (डिसब्लिमेशन) गैस से ठोस में सीधा परिवर्तन है, जैसे पाले का बनना।"),
]

# ═══════════════════════════════════════════════════════════
# PHYSICS QUESTIONS (each needs 10-15 more to reach 100)
# ═══════════════════════════════════════════════════════════

physics_electricity = [
    ("B","medium",2024,"Two resistors of 6Ω each in parallel give equivalent resistance of:","12Ω","3Ω","6Ω","1Ω","1/R = 1/6 + 1/6 = 2/6; R = 3Ω.","समांतर क्रम में 6Ω के दो प्रतिरोधकों का तुल्य प्रतिरोध है:","12Ω","3Ω","6Ω","1Ω","1/R = 1/6 + 1/6 = 2/6; R = 3Ω।"),
    ("C","easy",2024,"The SI unit of electric charge is:","Volt","Ampere","Coulomb","Ohm","Coulomb is the SI unit of electric charge; 1 coulomb = charge of ~6.25×10¹⁸ electrons.","विद्युत आवेश की SI इकाई है:","वोल्ट","एम्पियर","कूलॉम","ओम","कूलॉम विद्युत आवेश की SI इकाई है; 1 कूलॉम = ~6.25×10¹⁸ इलेक्ट्रॉनों का आवेश।"),
    ("D","medium",2023,"A fuse wire has:","High resistance, high melting point","Low resistance, high melting point","High resistance, low melting point","Low resistance, low melting point","Fuse wire has low melting point to melt and break circuit when current exceeds safe limit.","फ्यूज तार में होता है:","उच्च प्रतिरोध, उच्च गलनांक","निम्न प्रतिरोध, उच्च गलनांक","उच्च प्रतिरोध, निम्न गलनांक","निम्न प्रतिरोध, निम्न गलनांक","फ्यूज तार का गलनांक कम होता है ताकि धारा सुरक्षित सीमा से अधिक होने पर पिघलकर परिपथ तोड़ दे।"),
    ("B","medium",2024,"The heating effect of electric current is used in:","Motor","Electric iron","Generator","Transformer","Electric iron uses Joule heating (I²R) where electrical energy converts to heat.","विद्युत धारा का ऊष्मीय प्रभाव किसमें उपयोग होता है:","मोटर","विद्युत इस्त्री","जनित्र","ट्रांसफार्मर","विद्युत इस्त्री जूल तापन (I²R) का उपयोग करती है जहाँ विद्युत ऊर्जा ऊष्मा में बदलती है।"),
    ("A","easy",2024,"Ammeter is always connected in:","Series","Parallel","Either","Both","Ammeter has low resistance and is connected in series to measure current through a circuit.","एमीटर सदैव किसमें जोड़ा जाता है:","श्रेणीक्रम","समांतर क्रम","कोई भी","दोनों","एमीटर का प्रतिरोध कम होता है और यह परिपथ में धारा मापने के लिए श्रेणीक्रम में जोड़ा जाता है।"),
    ("C","medium",2023,"The commercial unit of electrical energy is:","Joule","Watt","kWh","Volt","1 kWh (kilowatt-hour) = 3.6 × 10⁶ J, the energy consumed by 1000W device in 1 hour.","विद्युत ऊर्जा की वाणिज्यिक इकाई है:","जूल","वॉट","kWh","वोल्ट","1 kWh (किलोवॉट-घंटा) = 3.6 × 10⁶ J, 1000W उपकरण द्वारा 1 घंटे में खपत ऊर्जा।"),
    ("D","medium",2024,"An electric motor converts:","Heat to electrical","Sound to electrical","Light to electrical","Electrical to mechanical","An electric motor converts electrical energy into mechanical (rotational) energy using magnetic field.","विद्युत मोटर किसे परिवर्तित करती है:","ऊष्मा से विद्युत","ध्वनि से विद्युत","प्रकाश से विद्युत","विद्युत से यांत्रिक","विद्युत मोटर चुंबकीय क्षेत्र का उपयोग कर विद्युत ऊर्जा को यांत्रिक (घूर्णी) ऊर्जा में बदलती है।"),
    ("B","easy",2024,"Ohm's law states that V is proportional to:","R","I","P","W","Ohm's law: V = IR, voltage is directly proportional to current at constant temperature.","ओम का नियम कहता है कि V किसके समानुपाती है:","R","I","P","W","ओम का नियम: V = IR, स्थिर ताप पर वोल्टता धारा के समानुपाती होती है।"),
    ("A","medium",2024,"Nichrome is an alloy used in:","Heating elements","Magnets","Batteries","Fuses","Nichrome (Ni-Cr alloy) has high resistivity and oxidation resistance, ideal for heating elements.","नाइक्रोम का उपयोग किसमें होता है:","तापन अवयव","चुंबक","बैटरी","फ्यूज","नाइक्रोम (Ni-Cr मिश्रधातु) में उच्च प्रतिरोधकता और ऑक्सीकरण प्रतिरोध है, तापन अवयवों के लिए आदर्श।"),
    ("C","medium",2023,"A 100W bulb used for 10 hours consumes:","0.1 kWh","10 kWh","1 kWh","100 kWh","Energy = Power × Time = 100W × 10h = 1000 Wh = 1 kWh.","100W का बल्ब 10 घंटे उपयोग करने पर खपत करता है:","0.1 kWh","10 kWh","1 kWh","100 kWh","ऊर्जा = शक्ति × समय = 100W × 10h = 1000 Wh = 1 kWh।"),
]

physics_force = [
    ("B","medium",2024,"A 2 kg object moving at 3 m/s has momentum of:","3 kg m/s","6 kg m/s","9 kg m/s","1.5 kg m/s","Momentum p = mv = 2 × 3 = 6 kg m/s.","3 m/s से गतिशील 2 kg वस्तु का संवेग है:","3 kg m/s","6 kg m/s","9 kg m/s","1.5 kg m/s","संवेग p = mv = 2 × 3 = 6 kg m/s।"),
    ("D","easy",2024,"Impulse is equal to:","Force × distance","Mass × velocity","Work done","Change in momentum","Impulse = Force × time = Change in momentum (Δp = mΔv).","आवेग किसके बराबर है:","बल × दूरी","द्रव्यमान × वेग","किया गया कार्य","संवेग में परिवर्तन","आवेग = बल × समय = संवेग में परिवर्तन (Δp = mΔv)।"),
    ("C","medium",2023,"Newton's first law is also called:","Law of momentum","Law of acceleration","Law of inertia","Law of reaction","Newton's first law (law of inertia) states that objects resist changes in their state of motion.","न्यूटन का प्रथम नियम क्या कहलाता है:","संवेग का नियम","त्वरण का नियम","जड़त्व का नियम","प्रतिक्रिया का नियम","न्यूटन का प्रथम नियम (जड़त्व का नियम) कहता है कि वस्तुएं अपनी गति अवस्था में परिवर्तन का विरोध करती हैं।"),
    ("A","medium",2024,"In a rocket, propulsion is based on:","Conservation of momentum","Conservation of energy","Newton's first law","Archimedes principle","Rocket propulsion uses conservation of momentum — exhaust gases pushed backward propel rocket forward.","रॉकेट में प्रणोदन किस पर आधारित है:","संवेग संरक्षण","ऊर्जा संरक्षण","न्यूटन का प्रथम नियम","आर्किमिडीज का सिद्धांत","रॉकेट प्रणोदन संवेग संरक्षण का उपयोग करता है — पीछे धकेली गई निकास गैसें रॉकेट को आगे धकेलती हैं।"),
    ("B","easy",2024,"The SI unit of force is:","Joule","Newton","Pascal","Watt","Newton (N) is the SI unit of force; 1 N = force needed to accelerate 1 kg at 1 m/s².","बल की SI इकाई है:","जूल","न्यूटन","पास्कल","वॉट","न्यूटन (N) बल की SI इकाई है; 1 N = 1 kg को 1 m/s² से त्वरित करने का बल।"),
    ("D","medium",2023,"Action and reaction forces:","Act on same body","Are always balanced","Cancel each other","Act on different bodies","Newton's third law: Action and reaction are equal, opposite, and act on DIFFERENT bodies.","क्रिया और प्रतिक्रिया बल:","एक ही पिंड पर कार्य करते हैं","सदैव संतुलित होते हैं","एक-दूसरे को रद्द करते हैं","भिन्न पिंडों पर कार्य करते हैं","न्यूटन का तृतीय नियम: क्रिया और प्रतिक्रिया बराबर, विपरीत और भिन्न पिंडों पर कार्य करते हैं।"),
    ("A","medium",2024,"The recoil of a gun is explained by:","Conservation of momentum","Newton's first law","Work-energy theorem","Impulse","When a bullet is fired forward, the gun recoils backward to conserve total momentum (initially zero).","बंदूक का प्रतिक्षेप किससे समझाया जाता है:","संवेग संरक्षण","न्यूटन का प्रथम नियम","कार्य-ऊर्जा प्रमेय","आवेग","जब गोली आगे छूटती है, बंदूक कुल संवेग (प्रारंभ में शून्य) संरक्षित करने के लिए पीछे हटती है।"),
    ("C","easy",2024,"Frictional force always acts:","In direction of motion","Perpendicular to motion","Opposite to motion","Upward","Friction always opposes relative motion between two surfaces in contact.","घर्षण बल सदैव किस दिशा में कार्य करता है:","गति की दिशा में","गति के लंबवत","गति के विपरीत","ऊपर की ओर","घर्षण सदैव संपर्क में दो सतहों के बीच आपेक्षिक गति का विरोध करता है।"),
    ("B","medium",2023,"The gravitational force is:","Always repulsive","Always attractive","Sometimes attractive","Zero at all times","Gravitational force is always attractive between any two masses.","गुरुत्वाकर्षण बल है:","सदैव प्रतिकर्षी","सदैव आकर्षी","कभी-कभी आकर्षी","हमेशा शून्य","गुरुत्वाकर्षण बल किन्हीं दो द्रव्यमानों के बीच सदैव आकर्षी होता है।"),
    ("D","medium",2024,"A force of 10 N acts on a 2 kg object. Acceleration is:","20 m/s²","0.2 m/s²","10 m/s²","5 m/s²","F = ma; a = F/m = 10/2 = 5 m/s².","10 N का बल 2 kg वस्तु पर लगता है। त्वरण है:","20 m/s²","0.2 m/s²","10 m/s²","5 m/s²","F = ma; a = F/m = 10/2 = 5 m/s²।"),
]

physics_gravitation = [
    ("A","medium",2024,"The value of g (acceleration due to gravity) on Moon is about:","g/6","g/2","g/3","g","g on Moon ≈ 1.63 m/s² (about 1/6 of Earth's 9.8 m/s²) due to Moon's smaller mass.","चंद्रमा पर g (गुरुत्वीय त्वरण) का मान लगभग है:","g/6","g/2","g/3","g","चंद्रमा का कम द्रव्यमान होने के कारण g ≈ 1.63 m/s² (पृथ्वी के 9.8 m/s² का लगभग 1/6)।"),
    ("C","easy",2024,"The SI unit of weight is:","Kilogram","Gram","Newton","Pascal","Weight is a force (W = mg), so its SI unit is Newton (N).","भार की SI इकाई है:","किलोग्राम","ग्राम","न्यूटन","पास्कल","भार एक बल है (W = mg), इसलिए इसकी SI इकाई न्यूटन (N) है।"),
    ("D","medium",2023,"Archimedes' principle is related to:","Gravity","Magnetism","Friction","Buoyancy","Archimedes' principle: buoyant force on an object equals weight of fluid displaced.","आर्किमिडीज का सिद्धांत किससे संबंधित है:","गुरुत्वाकर्षण","चुंबकत्व","घर्षण","उत्प्लावन","आर्किमिडीज का सिद्धांत: वस्तु पर उत्प्लावन बल = विस्थापित द्रव का भार।"),
    ("B","medium",2024,"An object weighs 60 N on Earth. Its mass is approximately:","60 kg","6 kg","600 kg","10 kg","W = mg; m = W/g = 60/10 ≈ 6 kg (using g ≈ 10 m/s² for approximation).","एक वस्तु का पृथ्वी पर भार 60 N है। इसका द्रव्यमान लगभग है:","60 kg","6 kg","600 kg","10 kg","W = mg; m = W/g = 60/10 ≈ 6 kg (g ≈ 10 m/s² का उपयोग करते हुए)।"),
    ("A","easy",2024,"Free fall is motion under:","Gravity only","Air resistance only","Both gravity and air","Magnetic force","Free fall occurs when an object moves under the influence of gravity alone (neglecting air resistance).","मुक्त पतन किसके अंतर्गत गति है:","केवल गुरुत्वाकर्षण","केवल वायु प्रतिरोध","गुरुत्व और वायु दोनों","चुंबकीय बल","मुक्त पतन तब होता है जब वस्तु केवल गुरुत्वाकर्षण के प्रभाव में गति करती है (वायु प्रतिरोध नगण्य)।"),
    ("C","medium",2023,"Pressure is defined as:","Force × area","Force × distance","Force ÷ area","Mass ÷ area","Pressure = Force / Area (P = F/A), measured in Pascal (N/m²).","दाब किस प्रकार परिभाषित है:","बल × क्षेत्रफल","बल × दूरी","बल ÷ क्षेत्रफल","द्रव्यमान ÷ क्षेत्रफल","दाब = बल / क्षेत्रफल (P = F/A), पास्कल (N/m²) में मापा जाता है।"),
    ("D","medium",2024,"A sharp knife cuts better because:","More force","Less weight","More area","Less area, more pressure","Sharp edge has small area → high pressure (P = F/A), making cutting easier.","तेज चाकू बेहतर काटता है क्योंकि:","अधिक बल","कम भार","अधिक क्षेत्रफल","कम क्षेत्रफल, अधिक दाब","तेज धार का क्षेत्रफल कम → उच्च दाब (P = F/A), काटना आसान बनाता है।"),
    ("B","easy",2024,"The upward force exerted by a fluid is:","Weight","Buoyant force","Gravitational force","Friction","The buoyant (upthrust) force pushes objects upward in a fluid, opposing weight.","द्रव द्वारा ऊपर की ओर लगाया गया बल है:","भार","उत्प्लावन बल","गुरुत्वाकर्षण बल","घर्षण","उत्प्लावन (उत्क्षेप) बल द्रव में वस्तुओं को ऊपर धकेलता है, भार का विरोध करता है।"),
    ("A","medium",2024,"The universal gravitational constant G was first measured by:","Cavendish","Newton","Galileo","Kepler","Henry Cavendish first measured G using a torsion balance experiment in 1798.","सार्वत्रिक गुरुत्वाकर्षण नियतांक G पहली बार किसने मापा:","कैवेंडिश","न्यूटन","गैलीलियो","केपलर","हेनरी कैवेंडिश ने 1798 में मरोड़ तुला प्रयोग द्वारा पहली बार G मापा।"),
    ("C","medium",2023,"The relative density of a substance is:","Mass/volume","Volume/mass","Density of substance/Density of water","Weight/volume","Relative density (specific gravity) = density of substance / density of water at 4°C.","किसी पदार्थ का आपेक्षिक घनत्व है:","द्रव्यमान/आयतन","आयतन/द्रव्यमान","पदार्थ का घनत्व/जल का घनत्व","भार/आयतन","आपेक्षिक घनत्व (विशिष्ट गुरुत्व) = पदार्थ का घनत्व / 4°C पर जल का घनत्व।"),
]

physics_heat = [
    ("B","medium",2024,"The latent heat of vaporization of water is:","80 cal/g","540 cal/g","334 cal/g","100 cal/g","Water's latent heat of vaporization is 540 cal/g (2260 kJ/kg) — energy to convert water at 100°C to steam.","जल की वाष्पन गुप्त ऊष्मा है:","80 cal/g","540 cal/g","334 cal/g","100 cal/g","जल की वाष्पन गुप्त ऊष्मा 540 cal/g (2260 kJ/kg) — 100°C जल को भाप में बदलने की ऊर्जा।"),
    ("D","easy",2024,"The normal human body temperature is:","32°C","25°C","42°C","37°C","Normal human body temperature is approximately 37°C (98.6°F).","सामान्य मानव शरीर का तापमान है:","32°C","25°C","42°C","37°C","सामान्य मानव शरीर का तापमान लगभग 37°C (98.6°F) है।"),
    ("A","medium",2023,"A clinical thermometer range is:","35°C to 42°C","0°C to 100°C","-10°C to 110°C","20°C to 50°C","Clinical thermometer measures 35-42°C, suitable for measuring human body temperature.","नैदानिक थर्मामीटर का परास है:","35°C से 42°C","0°C से 100°C","-10°C से 110°C","20°C से 50°C","नैदानिक थर्मामीटर 35-42°C मापता है, मानव शरीर तापमान मापने के लिए उपयुक्त।"),
    ("C","medium",2024,"Thermal expansion of a solid is:","Always harmful","Always useful","Can be useful or harmful","Negligible","Thermal expansion is useful (bimetallic strips, thermometers) but can be harmful (railway track buckling).","ठोस का ऊष्मीय प्रसार है:","सदैव हानिकारक","सदैव उपयोगी","उपयोगी या हानिकारक हो सकता है","नगण्य","ऊष्मीय प्रसार उपयोगी (द्विधातु पट्टी, थर्मामीटर) पर हानिकारक भी हो सकता है (रेल पटरी मुड़ना)।"),
    ("B","easy",2024,"Heat transfer in solids occurs by:","Convection","Conduction","Radiation","All three","Conduction transfers heat through solids by molecular vibrations without particle movement.","ठोसों में ऊष्मा स्थानांतरण किसके द्वारा होता है:","संवहन","चालन","विकिरण","तीनों","चालन ठोसों में अणु कंपन द्वारा बिना कण गति के ऊष्मा स्थानांतरित करता है।"),
    ("D","medium",2023,"Convection of heat occurs in:","Solids only","Vacuum","Metals","Liquids and gases","Convection requires movement of particles, occurring only in fluids (liquids and gases).","ऊष्मा का संवहन कहाँ होता है:","केवल ठोस","निर्वात","धातु","द्रव और गैस","संवहन के लिए कणों की गति आवश्यक है, केवल तरल पदार्थों (द्रव और गैस) में होता है।"),
    ("A","medium",2024,"Radiation can travel through:","Vacuum","Solids only","Liquids only","Gases only","Radiation (electromagnetic waves) requires no medium and can travel through vacuum (e.g., Sun's heat).","विकिरण किसके माध्यम से गमन कर सकता है:","निर्वात","केवल ठोस","केवल द्रव","केवल गैस","विकिरण (विद्युत चुंबकीय तरंगें) को माध्यम की आवश्यकता नहीं, निर्वात में गमन कर सकता है (जैसे सूर्य की ऊष्मा)।"),
    ("C","easy",2024,"The SI unit of specific heat capacity is:","Calorie/g°C","Joule","J/kg·K","Watt","Specific heat capacity = J/(kg·K), energy required to raise 1 kg by 1 K.","विशिष्ट ऊष्मा धारिता की SI इकाई है:","कैलोरी/g°C","जूल","J/kg·K","वॉट","विशिष्ट ऊष्मा धारिता = J/(kg·K), 1 kg को 1 K बढ़ाने की ऊर्जा।"),
    ("B","medium",2023,"Water has the highest specific heat capacity because of:","Low density","Hydrogen bonding","High density","Low molecular weight","Water's high specific heat (4.18 J/g°C) is due to extensive hydrogen bonding between molecules.","जल की विशिष्ट ऊष्मा धारिता सबसे अधिक है क्योंकि:","कम घनत्व","हाइड्रोजन बंधन","उच्च घनत्व","कम अणुभार","जल की उच्च विशिष्ट ऊष्मा (4.18 J/g°C) अणुओं के बीच व्यापक हाइड्रोजन बंधन के कारण है।"),
    ("D","medium",2024,"The freezing point of water in Kelvin is:","0 K","100 K","373 K","273 K","Water freezes at 0°C = 273 K (Kelvin = Celsius + 273).","जल का हिमांक केल्विन में है:","0 K","100 K","373 K","273 K","जल 0°C = 273 K पर जमता है (केल्विन = सेल्सियस + 273)।"),
]

physics_light = [
    ("C","medium",2024,"The refractive index of water is approximately:","1.0","2.4","1.33","1.5","Water's refractive index is 1.33, meaning light travels 1.33 times slower in water than vacuum.","जल का अपवर्तनांक लगभग है:","1.0","2.4","1.33","1.5","जल का अपवर्तनांक 1.33 है, अर्थात प्रकाश निर्वात की तुलना में जल में 1.33 गुना धीमा चलता है।"),
    ("B","easy",2024,"A rainbow is formed due to:","Reflection only","Dispersion and internal reflection","Refraction only","Diffraction","Rainbows form when sunlight is dispersed by water droplets and internally reflected.","इंद्रधनुष किसके कारण बनता है:","केवल परावर्तन","वर्ण-विक्षेपण और आंतरिक परावर्तन","केवल अपवर्तन","विवर्तन","इंद्रधनुष तब बनता है जब सूर्यप्रकाश जल बूंदों द्वारा वर्ण-विक्षेपित और आंतरिक परावर्तित होता है।"),
    ("D","medium",2023,"A convex lens of focal length 20 cm has power:","0.05 D","0.2 D","20 D","5 D","Power (diopters) = 1/f(meters) = 1/0.20 = 5 D.","20 cm फोकस दूरी के उत्तल लेंस की क्षमता है:","0.05 D","0.2 D","20 D","5 D","क्षमता (डायोप्टर) = 1/f(मीटर) = 1/0.20 = 5 D।"),
    ("A","medium",2024,"The scattering of light by colloidal particles is:","Tyndall effect","Raman effect","Doppler effect","Zeeman effect","Tyndall effect is the scattering of light by colloidal particles, making the beam visible.","कोलॉइडी कणों द्वारा प्रकाश का प्रकीर्णन है:","टिंडल प्रभाव","रमन प्रभाव","डॉप्लर प्रभाव","जीमान प्रभाव","टिंडल प्रभाव कोलॉइडी कणों द्वारा प्रकाश का प्रकीर्णन है, जिससे किरणपुंज दिखाई देता है।"),
    ("C","easy",2024,"Which mirror is used in car headlights?","Plane mirror","Convex mirror","Concave mirror","Cylindrical mirror","Concave mirrors converge light to produce a strong parallel beam in car headlights.","कार हेडलाइट में कौन सा दर्पण उपयोग होता है:","समतल दर्पण","उत्तल दर्पण","अवतल दर्पण","बेलनाकार दर्पण","अवतल दर्पण कार हेडलाइट में प्रकाश को अभिसरित कर प्रबल समांतर किरणपुंज बनाते हैं।"),
    ("B","medium",2023,"The sky appears blue due to:","Reflection","Scattering","Refraction","Dispersion","Rayleigh scattering: shorter wavelength blue light scatters more than red, making the sky appear blue.","आकाश नीला किसके कारण दिखता है:","परावर्तन","प्रकीर्णन","अपवर्तन","वर्ण-विक्षेपण","रेले प्रकीर्णन: छोटी तरंगदैर्ध्य का नीला प्रकाश लाल से अधिक प्रकीर्णित होता है, आकाश नीला दिखता है।"),
    ("D","medium",2024,"For a plane mirror, image distance is:","Half of object distance","Double of object distance","Zero","Equal to object distance","In a plane mirror, image forms at equal distance behind the mirror as the object is in front.","समतल दर्पण के लिए, प्रतिबिंब दूरी है:","वस्तु दूरी की आधी","वस्तु दूरी की दोगुनी","शून्य","वस्तु दूरी के बराबर","समतल दर्पण में, प्रतिबिंब दर्पण के पीछे उतनी ही दूरी पर बनता है जितनी दूर वस्तु सामने है।"),
    ("A","easy",2024,"The splitting of white light into colors is:","Dispersion","Reflection","Refraction","Scattering","Dispersion splits white light into 7 colors (VIBGYOR) due to different wavelengths refracting differently.","श्वेत प्रकाश का रंगों में विभाजन है:","वर्ण-विक्षेपण","परावर्तन","अपवर्तन","प्रकीर्णन","वर्ण-विक्षेपण श्वेत प्रकाश को 7 रंगों (VIBGYOR) में विभाजित करता है क्योंकि विभिन्न तरंगदैर्ध्य भिन्न रूप से अपवर्तित होते हैं।"),
    ("C","medium",2023,"A concave lens always forms:","Real and inverted","Real and erect","Virtual and erect","Virtual and inverted","Concave (diverging) lenses always produce virtual, erect, and diminished images.","अवतल लेंस सदैव बनाता है:","वास्तविक और उल्टा","वास्तविक और सीधा","आभासी और सीधा","आभासी और उल्टा","अवतल (अपसारी) लेंस सदैव आभासी, सीधा और छोटा प्रतिबिंब बनाते हैं।"),
    ("B","medium",2024,"The human eye lens is:","Concave","Convex (biconvex)","Plane","Cylindrical","The eye lens is a convex (biconvex) lens that focuses light on the retina.","मानव नेत्र लेंस है:","अवतल","उत्तल (द्वि-उत्तल)","समतल","बेलनाकार","नेत्र लेंस एक उत्तल (द्वि-उत्तल) लेंस है जो रेटिना पर प्रकाश फोकस करता है।"),
]

physics_magnetism = [
    ("C","medium",2024,"A current-carrying solenoid behaves like a:","Permanent magnet only","Electromagnet only","Bar magnet","Insulator","A solenoid with current produces a magnetic field similar to a bar magnet with N and S poles.","धारावाही परिनालिका किसकी तरह व्यवहार करती है:","केवल स्थायी चुंबक","केवल विद्युत चुंबक","दंड चुंबक","कुचालक","धारावाही परिनालिका N और S ध्रुवों वाले दंड चुंबक जैसा चुंबकीय क्षेत्र उत्पन्न करती है।"),
    ("B","easy",2024,"The magnetic field inside a solenoid is:","Zero","Uniform","Non-uniform","Alternating","The magnetic field inside a long current-carrying solenoid is uniform (parallel lines, equal spacing).","परिनालिका के अंदर चुंबकीय क्षेत्र है:","शून्य","एकसमान","असमान","प्रत्यावर्ती","लंबी धारावाही परिनालिका के अंदर चुंबकीय क्षेत्र एकसमान (समांतर रेखाएं, समान दूरी) होता है।"),
    ("D","medium",2023,"An AC generator works on the principle of:","Motor effect","Ohm's law","Joule heating","Electromagnetic induction","AC generators use electromagnetic induction (Faraday's law) — changing magnetic flux induces EMF.","AC जनित्र किस सिद्धांत पर कार्य करता है:","मोटर प्रभाव","ओम का नियम","जूल तापन","विद्युत चुंबकीय प्रेरण","AC जनित्र विद्युत चुंबकीय प्रेरण (फैराडे का नियम) का उपयोग करते हैं — बदलता चुंबकीय फ्लक्स EMF प्रेरित करता है।"),
    ("A","medium",2024,"The direction of magnetic field around a straight wire is given by:","Right-hand thumb rule","Fleming's left hand rule","Fleming's right hand rule","Ohm's law","Right-hand thumb rule: thumb → current direction, curled fingers → magnetic field direction.","सीधे तार के चारों ओर चुंबकीय क्षेत्र की दिशा किससे ज्ञात होती है:","दक्षिण-हस्त अंगुष्ठ नियम","फ्लेमिंग का बायाँ हाथ नियम","फ्लेमिंग का दायाँ हाथ नियम","ओम का नियम","दक्षिण-हस्त अंगुष्ठ नियम: अंगूठा → धारा दिशा, मुड़ी अंगुलियां → चुंबकीय क्षेत्र दिशा।"),
    ("C","easy",2024,"Which device converts electrical energy to mechanical energy?","Generator","Transformer","Electric motor","Rectifier","An electric motor converts electrical energy to mechanical (rotational) energy using magnetic forces.","कौन सा उपकरण विद्युत ऊर्जा को यांत्रिक ऊर्जा में बदलता है:","जनित्र","ट्रांसफार्मर","विद्युत मोटर","दिष्टकारी","विद्युत मोटर चुंबकीय बलों द्वारा विद्युत ऊर्जा को यांत्रिक (घूर्णी) ऊर्जा में बदलती है।"),
    ("B","medium",2023,"Fleming's left hand rule is used for:","Generator","Electric motor","Transformer","Battery","Fleming's left hand rule gives direction of force on a current-carrying conductor in magnetic field (motor effect).","फ्लेमिंग का बायाँ हाथ नियम किसके लिए उपयोग होता है:","जनित्र","विद्युत मोटर","ट्रांसफार्मर","बैटरी","फ्लेमिंग का बायाँ हाथ नियम चुंबकीय क्षेत्र में धारावाही चालक पर बल की दिशा बताता है (मोटर प्रभाव)।"),
    ("D","medium",2024,"A step-up transformer:","Decreases voltage","Keeps voltage same","Only works with DC","Increases voltage","Step-up transformer has more turns in secondary coil, increasing voltage (Nₛ > Nₚ → Vₛ > Vₚ).","उच्चायी ट्रांसफार्मर:","वोल्टता घटाता है","वोल्टता समान रखता है","केवल DC पर कार्य करता है","वोल्टता बढ़ाता है","उच्चायी ट्रांसफार्मर में द्वितीयक कुंडली में अधिक फेरे होते हैं, वोल्टता बढ़ती है (Nₛ > Nₚ → Vₛ > Vₚ)।"),
    ("A","easy",2024,"The core of an electromagnet is made of:","Soft iron","Steel","Copper","Aluminum","Soft iron is used because it magnetizes easily and loses magnetism quickly when current stops.","विद्युत चुंबक का क्रोड बना होता है:","नरम लोहा","इस्पात","तांबा","एल्युमीनियम","नरम लोहा उपयोग होता है क्योंकि यह आसानी से चुंबकित और धारा रुकने पर शीघ्र विचुंबकित होता है।"),
    ("C","medium",2023,"The magnetic field lines inside a magnet go from:","North to South","East to West","South to North","Random","Inside a magnet, field lines go from South to North pole (outside: North to South, forming closed loops).","चुंबक के अंदर चुंबकीय क्षेत्र रेखाएं किस दिशा में जाती हैं:","उत्तर से दक्षिण","पूर्व से पश्चिम","दक्षिण से उत्तर","यादृच्छिक","चुंबक के अंदर, क्षेत्र रेखाएं दक्षिण से उत्तर ध्रुव की ओर जाती हैं (बाहर: उत्तर से दक्षिण, बंद लूप बनाती हैं)।"),
    ("B","medium",2024,"A galvanometer can be converted to ammeter by connecting:","High resistance in series","Low resistance in parallel (shunt)","Capacitor in series","Inductor in parallel","A low resistance shunt in parallel diverts most current, converting galvanometer to ammeter.","गैल्वेनोमीटर को एमीटर में बदला जा सकता है जोड़कर:","श्रेणी में उच्च प्रतिरोध","समांतर में निम्न प्रतिरोध (शंट)","श्रेणी में संधारित्र","समांतर में प्रेरक","समांतर में निम्न प्रतिरोध शंट अधिकांश धारा मोड़ता है, गैल्वेनोमीटर को एमीटर में बदलता है।"),
]

physics_motion = [
    ("B","medium",2024,"A car accelerates from rest to 20 m/s in 5 s. Acceleration is:","100 m/s²","4 m/s²","0.25 m/s²","20 m/s²","a = (v-u)/t = (20-0)/5 = 4 m/s².","एक कार विराम से 5 s में 20 m/s तक त्वरित होती है। त्वरण है:","100 m/s²","4 m/s²","0.25 m/s²","20 m/s²","a = (v-u)/t = (20-0)/5 = 4 m/s²।"),
    ("D","easy",2024,"Displacement is a:","Scalar quantity","Dimensionless quantity","Always positive","Vector quantity","Displacement has both magnitude and direction, making it a vector quantity (unlike distance).","विस्थापन है:","अदिश राशि","विमाहीन राशि","सदैव धनात्मक","सदिश राशि","विस्थापन में परिमाण और दिशा दोनों होते हैं, इसे सदिश राशि बनाते हैं (दूरी के विपरीत)।"),
    ("C","medium",2023,"A body moving in a circle with constant speed has:","Zero acceleration","Constant velocity","Centripetal acceleration","Linear acceleration","Even at constant speed, direction changes continuously → centripetal acceleration toward center.","स्थिर चाल से वृत्त में गतिमान पिंड में होता है:","शून्य त्वरण","नियत वेग","अभिकेंद्रीय त्वरण","रैखिक त्वरण","स्थिर चाल पर भी, दिशा निरंतर बदलती है → केंद्र की ओर अभिकेंद्रीय त्वरण।"),
    ("A","medium",2024,"The slope of a velocity-time graph gives:","Acceleration","Displacement","Speed","Distance","Slope of v-t graph = Δv/Δt = acceleration. Area under v-t graph = displacement.","वेग-समय ग्राफ की ढाल क्या देती है:","त्वरण","विस्थापन","चाल","दूरी","v-t ग्राफ की ढाल = Δv/Δt = त्वरण। v-t ग्राफ के नीचे क्षेत्रफल = विस्थापन।"),
    ("B","easy",2024,"The SI unit of speed is:","km/h","m/s","cm/s","m/s²","Speed (scalar) and velocity (vector) both have SI unit m/s (meter per second).","चाल की SI इकाई है:","km/h","m/s","cm/s","m/s²","चाल (अदिश) और वेग (सदिश) दोनों की SI इकाई m/s (मीटर प्रति सेकंड) है।"),
    ("D","medium",2023,"A ball thrown up returns after 6 s. Maximum height is (g=10 m/s²):","180 m","90 m","30 m","45 m","Time to max height = 3 s; h = ut - ½gt²; u = g×3 = 30 m/s; h = 30×3 - ½×10×9 = 90-45 = 45 m.","ऊपर फेंकी गई गेंद 6 s बाद लौटती है। अधिकतम ऊंचाई (g=10 m/s²):","180 m","90 m","30 m","45 m","अधिकतम ऊंचाई का समय = 3 s; h = ut - ½gt²; u = g×3 = 30 m/s; h = 30×3 - ½×10×9 = 90-45 = 45 m।"),
    ("C","medium",2024,"The area under a speed-time graph represents:","Acceleration","Velocity","Distance","Force","Area under speed-time graph gives total distance traveled.","चाल-समय ग्राफ के नीचे का क्षेत्रफल दर्शाता है:","त्वरण","वेग","दूरी","बल","चाल-समय ग्राफ के नीचे क्षेत्रफल कुल तय दूरी देता है।"),
    ("A","easy",2024,"Uniform circular motion is an example of:","Accelerated motion","Uniform velocity","Constant speed only","Linear motion","Uniform circular motion has constant speed but changing direction → acceleration (centripetal).","एकसमान वृत्तीय गति किसका उदाहरण है:","त्वरित गति","समान वेग","केवल नियत चाल","रैखिक गति","एकसमान वृत्तीय गति में स्थिर चाल पर बदलती दिशा → त्वरण (अभिकेंद्रीय) होता है।"),
    ("B","medium",2023,"The equation s = ut + ½at² is valid for:","Non-uniform acceleration","Uniform acceleration","Variable velocity","Circular motion","This second equation of motion applies only when acceleration is constant (uniform).","समीकरण s = ut + ½at² मान्य है:","असमान त्वरण के लिए","समान त्वरण के लिए","परिवर्ती वेग के लिए","वृत्तीय गति के लिए","गति का यह दूसरा समीकरण केवल तब लागू होता है जब त्वरण स्थिर (समान) हो।"),
    ("D","medium",2024,"A stone dropped from a cliff hits ground in 4 s. Height (g=10 m/s²):","40 m","160 m","20 m","80 m","h = ½gt² = ½ × 10 × 16 = 80 m (initial velocity = 0).","चट्टान से गिराया पत्थर 4 s में जमीन पर पहुंचता है। ऊंचाई (g=10 m/s²):","40 m","160 m","20 m","80 m","h = ½gt² = ½ × 10 × 16 = 80 m (प्रारंभिक वेग = 0)।"),
]

physics_sound = [
    ("B","medium",2024,"A sonar sends a signal and receives echo after 4 s. If speed of sound in water is 1500 m/s, depth is:","6000 m","3000 m","1500 m","750 m","Depth = (v × t)/2 = (1500 × 4)/2 = 3000 m (divide by 2 for round trip).","सोनार सिग्नल भेजता है और 4 s बाद प्रतिध्वनि प्राप्त करता है। जल में ध्वनि की चाल 1500 m/s, गहराई:","6000 m","3000 m","1500 m","750 m","गहराई = (v × t)/2 = (1500 × 4)/2 = 3000 m (आने-जाने के लिए 2 से भाग)।"),
    ("D","easy",2024,"Ultrasound has frequency:","Below 20 Hz","20 Hz to 20 kHz","Below 20 kHz","Above 20 kHz","Ultrasound refers to sound waves with frequency greater than 20,000 Hz (20 kHz).","पराध्वनि की आवृत्ति होती है:","20 Hz से नीचे","20 Hz से 20 kHz","20 kHz से नीचे","20 kHz से ऊपर","पराध्वनि 20,000 Hz (20 kHz) से अधिक आवृत्ति की ध्वनि तरंगों को कहते हैं।"),
    ("C","medium",2023,"The relation between frequency (f), wavelength (λ), and velocity (v) is:","v = f/λ","v = λ/f","v = f × λ","v = f + λ","Wave equation: velocity = frequency × wavelength (v = fλ).","आवृत्ति (f), तरंगदैर्ध्य (λ) और वेग (v) में संबंध है:","v = f/λ","v = λ/f","v = f × λ","v = f + λ","तरंग समीकरण: वेग = आवृत्ति × तरंगदैर्ध्य (v = fλ)।"),
    ("A","medium",2024,"A sound wave has frequency 500 Hz and wavelength 0.68 m. Speed is:","340 m/s","170 m/s","680 m/s","250 m/s","v = fλ = 500 × 0.68 = 340 m/s (speed of sound in air).","एक ध्वनि तरंग की आवृत्ति 500 Hz और तरंगदैर्ध्य 0.68 m है। चाल:","340 m/s","170 m/s","680 m/s","250 m/s","v = fλ = 500 × 0.68 = 340 m/s (वायु में ध्वनि की चाल)।"),
    ("B","easy",2024,"Sound cannot travel through:","Air","Vacuum","Water","Steel","Sound requires a medium to propagate; it cannot travel through vacuum (no particles to vibrate).","ध्वनि किसमें गमन नहीं कर सकती:","वायु","निर्वात","जल","इस्पात","ध्वनि को संचरण के लिए माध्यम चाहिए; निर्वात में नहीं चल सकती (कंपन के लिए कण नहीं)।"),
    ("D","medium",2023,"The audible range for humans is:","Below 20 Hz","Above 20 kHz","1-100 Hz","20 Hz to 20 kHz","Human ear can detect sounds between 20 Hz (infrasound limit) and 20,000 Hz (ultrasound limit).","मनुष्यों के लिए श्रव्य परास है:","20 Hz से नीचे","20 kHz से ऊपर","1-100 Hz","20 Hz से 20 kHz","मानव कान 20 Hz (अवश्रव्य सीमा) से 20,000 Hz (पराध्वनि सीमा) के बीच ध्वनि सुन सकता है।"),
    ("C","medium",2024,"Echo is produced due to:","Refraction","Diffraction","Reflection of sound","Absorption","Echo is the reflection of sound from a hard surface, heard after a minimum 0.1 s delay.","प्रतिध्वनि किसके कारण उत्पन्न होती है:","अपवर्तन","विवर्तन","ध्वनि का परावर्तन","अवशोषण","प्रतिध्वनि कठोर सतह से ध्वनि का परावर्तन है, न्यूनतम 0.1 s विलंब से सुनाई देती है।"),
    ("A","easy",2024,"The pitch of a sound depends on:","Frequency","Amplitude","Speed","Medium","Pitch is determined by frequency — higher frequency = higher pitch (shrill sound).","ध्वनि का तारत्व किस पर निर्भर करता है:","आवृत्ति","आयाम","चाल","माध्यम","तारत्व आवृत्ति से निर्धारित होता है — उच्च आवृत्ति = उच्च तारत्व (तीखी ध्वनि)।"),
    ("B","medium",2023,"The loudness of sound depends on:","Frequency","Amplitude","Wavelength","Velocity","Loudness is proportional to the square of amplitude of the sound wave.","ध्वनि की प्रबलता किस पर निर्भर करती है:","आवृत्ति","आयाम","तरंगदैर्ध्य","वेग","प्रबलता ध्वनि तरंग के आयाम के वर्ग के समानुपाती होती है।"),
    ("D","medium",2024,"Which medium has the highest speed of sound?","Air","Water","Vacuum","Steel","Sound travels fastest in solids — in steel ~5960 m/s, faster than in liquids or gases.","किस माध्यम में ध्वनि की चाल सबसे अधिक है?","वायु","जल","निर्वात","इस्पात","ध्वनि ठोसों में सबसे तेज चलती है — इस्पात में ~5960 m/s, द्रव या गैस से तेज।"),
]

physics_work_energy = [
    ("C","medium",2024,"A 50 kg person climbs 10 m. Work done against gravity (g=10):","500 J","1000 J","5000 J","50 J","W = mgh = 50 × 10 × 10 = 5000 J.","50 kg का व्यक्ति 10 m चढ़ता है। गुरुत्व के विरुद्ध कार्य (g=10):","500 J","1000 J","5000 J","50 J","W = mgh = 50 × 10 × 10 = 5000 J।"),
    ("B","easy",2024,"The SI unit of power is:","Joule","Watt","Newton","Pascal","Power (rate of work) = Watt = Joule/second (1 W = 1 J/s).","शक्ति की SI इकाई है:","जूल","वॉट","न्यूटन","पास्कल","शक्ति (कार्य की दर) = वॉट = जूल/सेकंड (1 W = 1 J/s)।"),
    ("D","medium",2023,"Kinetic energy depends on:","Mass only","Velocity only","Height","Mass and velocity squared","KE = ½mv² — kinetic energy depends on mass and the square of velocity.","गतिज ऊर्जा किस पर निर्भर करती है:","केवल द्रव्यमान","केवल वेग","ऊंचाई","द्रव्यमान और वेग का वर्ग","KE = ½mv² — गतिज ऊर्जा द्रव्यमान और वेग के वर्ग पर निर्भर करती है।"),
    ("A","medium",2024,"A 2 kg object moves at 4 m/s. Its KE is:","16 J","8 J","32 J","4 J","KE = ½ × 2 × 4² = ½ × 2 × 16 = 16 J.","2 kg की वस्तु 4 m/s से चलती है। इसकी गतिज ऊर्जा:","16 J","8 J","32 J","4 J","KE = ½ × 2 × 4² = ½ × 2 × 16 = 16 J।"),
    ("C","easy",2024,"Potential energy of an object at height h is:","mgh/2","mg/h","mgh","mgh²","Gravitational PE = mgh (mass × gravity × height).","h ऊंचाई पर वस्तु की स्थितिज ऊर्जा है:","mgh/2","mg/h","mgh","mgh²","गुरुत्वीय स्थितिज ऊर्जा = mgh (द्रव्यमान × गुरुत्व × ऊंचाई)।"),
    ("B","medium",2023,"The law of conservation of energy states that energy:","Can be created","Can neither be created nor destroyed","Can be destroyed","Always decreases","Energy cannot be created or destroyed, only transformed from one form to another.","ऊर्जा संरक्षण का नियम कहता है कि ऊर्जा:","बनाई जा सकती है","न बनाई जा सकती है न नष्ट","नष्ट की जा सकती है","सदैव घटती है","ऊर्जा न तो बनाई जा सकती है न नष्ट, केवल एक रूप से दूसरे में रूपांतरित होती है।"),
    ("D","medium",2024,"A 100W bulb running for 1 hour uses energy of:","100 J","1000 J","6000 J","360,000 J","E = P × t = 100W × 3600s = 360,000 J (or 0.1 kWh).","100W का बल्ब 1 घंटे चलने पर ऊर्जा उपयोग करता है:","100 J","1000 J","6000 J","360,000 J","E = P × t = 100W × 3600s = 360,000 J (या 0.1 kWh)।"),
    ("A","easy",2024,"In a hydroelectric dam, energy transformation is:","PE → KE → Electrical","KE → PE → Heat","Electrical → KE → PE","Heat → PE → KE","Water's potential energy → kinetic energy → rotates turbine → electrical energy.","जलविद्युत बांध में ऊर्जा रूपांतरण है:","स्थितिज → गतिज → विद्युत","गतिज → स्थितिज → ऊष्मा","विद्युत → गतिज → स्थितिज","ऊष्मा → स्थितिज → गतिज","जल की स्थितिज ऊर्जा → गतिज ऊर्जा → टरबाइन घूर्णन → विद्युत ऊर्जा।"),
    ("C","medium",2023,"1 horsepower (hp) equals approximately:","100 W","1000 W","746 W","500 W","1 hp = 746 watts, a unit of power commonly used for engines and motors.","1 अश्वशक्ति (hp) लगभग किसके बराबर है:","100 W","1000 W","746 W","500 W","1 hp = 746 वॉट, इंजन और मोटरों के लिए सामान्य शक्ति इकाई।"),
    ("B","medium",2024,"When a spring is compressed, it stores:","Kinetic energy","Elastic potential energy","Gravitational potential energy","Heat energy","A compressed or stretched spring stores elastic potential energy: PE = ½kx².","जब स्प्रिंग संपीडित होती है, यह संग्रहित करती है:","गतिज ऊर्जा","प्रत्यास्थ स्थितिज ऊर्जा","गुरुत्वीय स्थितिज ऊर्जा","ऊष्मा ऊर्जा","संपीडित या खिंची स्प्रिंग प्रत्यास्थ स्थितिज ऊर्जा संग्रहित करती है: PE = ½kx²।"),
]

# ══════════════════════════════════════════════
# MAP AND PROCESS ALL FILES
# ══════════════════════════════════════════════
file_data_map = {
    # Biology (10 files)
    "biology-cell-structure.json": ("gdsbcs", cell_extra if 'cell_extra' in dir() else []),
    "biology-tissues.json": ("gdsbt", tissue_extra if 'tissue_extra' in dir() else []),
    "biology-nutrition.json": ("gdsbn", nutrition_extra if 'nutrition_extra' in dir() else []),
    "biology-respiration.json": ("gdsbr", respiration_extra if 'respiration_extra' in dir() else []),
    "biology-transportation.json": ("gdsbtp", transport_extra if 'transport_extra' in dir() else []),
    "biology-excretion.json": ("gdsbe", excretion_extra if 'excretion_extra' in dir() else []),
    "biology-reproduction.json": ("gdsbrp", reproduction_extra if 'reproduction_extra' in dir() else []),
    "biology-genetics.json": ("gdsbg", genetics_extra if 'genetics_extra' in dir() else []),
    "biology-diseases.json": ("gdsbd", diseases_extra if 'diseases_extra' in dir() else []),
    "biology-ecology.json": ("gdsbec", ecology_extra if 'ecology_extra' in dir() else []),
    # Chemistry (7 files)
    "chemistry-acids-bases-salts.json": ("gdscabs", acids_data),
    "chemistry-carbon-compounds.json": ("gdsccc", carbon_data),
    "chemistry-chemical-reactions.json": ("gdscrn", reactions_data),
    "chemistry-metals-nonmetals.json": ("gdscmn", metals_data),
    "chemistry-periodic-table.json": ("gdscpt", periodic_data),
    "chemistry-atoms-molecules.json": ("gdscam", atoms_data),
    "chemistry-matter.json": ("gdscm", matter_data),
    # Physics (9 files)
    "physics-electricity.json": ("gdspel", physics_electricity),
    "physics-force-laws.json": ("gdspfl", physics_force),
    "physics-gravitation.json": ("gdspgv", physics_gravitation),
    "physics-heat-thermodynamics.json": ("gdspht", physics_heat),
    "physics-light.json": ("gdsplt", physics_light),
    "physics-magnetism.json": ("gdspmg", physics_magnetism),
    "physics-motion.json": ("gdspmo", physics_motion),
    "physics-sound.json": ("gdspsd", physics_sound),
    "physics-work-energy-power.json": ("gdspwe", physics_work_energy),
}

print("=" * 60)
print("Group D Science Question Generator")
print("=" * 60)

total_added = 0
for fname, (prefix, questions) in file_data_map.items():
    if not questions:
        print(f"  SKIP {fname}: no new questions defined")
        continue
    try:
        existing = load(fname)
        existing.extend(questions)
        save(fname, existing)
        total_added += len(questions)
    except Exception as e:
        print(f"  ERROR {fname}: {e}")

print(f"\n✓ Total new questions added: {total_added}")
print("✓ All files updated. Run validation to verify.")
