#!/usr/bin/env python3
import json, os
BASE = r"C:\Users\core\rrb-exam-prep\public\data\questions\ntpc\general-awareness"
E,M,H="easy","medium","hard"; Y24,Y23,Y25=2024,2023,2025
def Q(c,d,y,eq,eo,ex,hq,ho,hx):
    return {"correctOption":c,"difficulty":d,"sourceYear":y,"en":{"question":eq,"options":eo,"explanation":ex},"hi":{"question":hq,"options":ho,"explanation":hx}}
def proc(fn,qs):
    p=os.path.join(BASE,fn)
    with open(p,'r',encoding='utf-8') as f: data=json.load(f)
    s=int(data[-1]['id'].split('-')[-1]) if data else 0
    for i,q in enumerate(qs): q['id']=f"ntpc-ga-{s+i+1:04d}"
    data.extend(qs)
    with open(p,'w',encoding='utf-8') as f: json.dump(data,f,ensure_ascii=False,indent=2)
    print(f"  {fn}: +{len(qs)} = {len(data)} total")
    return len(qs)
tot=0
print("\n=== RRB NTPC GA Batch 1: History, Geography, Polity, Economics, General Science ===\n")

# ====== 1. INDIAN HISTORY (65 new Qs) ======
print("1. Indian History")
H=[Q("C",E,Y24,"Largest Indus Valley site?",["Mohenjo-daro","Harappa","Rakhigarhi","Dholavira"],"Rakhigarhi (Haryana) spanning 350+ hectares, largest IVC site.","सबसे बड़ा सिंधु घाटी स्थल?",["मोहनजोदड़ो","हड़प्पा","राखीगढ़ी","धोलावीरा"],"हरियाणा में राखीगढ़ी 350+ हेक्टेयर, सबसे बड़ा सिंधु घाटी स्थल।"),
Q("B",M,Y24,"Great Bath found at which Indus site?",["Harappa","Mohenjo-daro","Lothal","Kalibangan"],"Great Bath at Mohenjo-daro: large rectangular tank for ritual bathing.","महान स्नानागार किस स्थल पर?",["हड़प्पा","मोहनजोदड़ो","लोथल","कालीबंगा"],"मोहनजोदड़ो में बड़ा आयताकार जल कुंड, अनुष्ठान स्नान हेतु।"),
Q("D",M,Y24,"Indus site famous for dockyard?",["Mohenjo-daro","Harappa","Kalibangan","Lothal"],"Lothal (Gujarat) dockyard connected to Sabarmati River, maritime trade.","बंदरगाह वाला सिंधु स्थल?",["मोहनजोदड़ो","हड़प्पा","कालीबंगा","लोथल"],"गुजरात में लोथल: साबरमती से जुड़ा बंदरगाह, समुद्री व्यापार।"),
Q("A",E,Y24,"Indus people worshipped?",["Pashupati (Proto-Shiva)","Vishnu","Brahma","Indra"],"Pashupati seal: horned figure with animals, proto-Shiva.","सिंधु लोग किसकी पूजा करते थे?",["पशुपति (आदि-शिव)","विष्णु","ब्रह्मा","इंद्र"],"पशुपति मुहर: सींग वाली आकृति, आदि-शिव।"),
Q("B",M,Y24,"Metal unknown to Indus Valley?",["Copper","Iron","Bronze","Gold"],"Iron was not known. They used copper, bronze, gold, silver, lead.","सिंधु लोग किस धातु से अनजान?",["तांबा","लोहा","कांसा","सोना"],"लोहा अज्ञात। तांबा, कांसा, सोना, चांदी, सीसा का प्रयोग।"),
Q("A",E,Y24,"Oldest Veda?",["Rigveda","Samaveda","Yajurveda","Atharvaveda"],"Rigveda (~1500-1200 BCE): 1,028 hymns in 10 mandalas.","सबसे पुराना वेद?",["ऋग्वेद","सामवेद","यजुर्वेद","अथर्ववेद"],"ऋग्वेद (~1500-1200 ई.पू.): 10 मंडलों में 1,028 सूक्त।"),
Q("C",M,Y24,"Gayatri Mantra found in?",["Samaveda","Yajurveda","Rigveda","Atharvaveda"],"Rigveda Mandala 3, Hymn 62, Verse 10.","गायत्री मंत्र किसमें?",["सामवेद","यजुर्वेद","ऋग्वेद","अथर्ववेद"],"ऋग्वेद मंडल 3, सूक्त 62, श्लोक 10।"),
Q("B",E,Y24,"Composer of Gayatri Mantra?",["Vasishta","Vishwamitra","Atri","Agastya"],"Rishi Vishwamitra composed several Rigvedic hymns.","गायत्री मंत्र के रचयिता?",["वसिष्ठ","विश्वामित्र","अत्रि","अगस्त्य"],"ऋषि विश्वामित्र ने कई ऋग्वैदिक सूक्त रचे।"),
Q("D",H,Y23,"Battle of Ten Kings fought on?",["Ganga","Yamuna","Saraswati","Ravi (Parushni)"],"King Sudas vs ten tribes on Ravi. Sudas won.","दस राजाओं का युद्ध किस पर?",["गंगा","यमुना","सरस्वती","रावी (परुष्णी)"],"राजा सुदास बनाम दस जनजातियाँ। सुदास विजयी।"),
Q("B",M,Y24,"Samaveda known as?",["Book of Hymns","Book of Chants","Book of Sacrifices","Book of Spells"],"Contains melodies/chants from Rigvedic hymns.","सामवेद किस नाम से?",["सूक्तों की पुस्तक","गानों की पुस्तक","यज्ञों की पुस्तक","मंत्रों की पुस्तक"],"ऋग्वैदिक सूक्तों के गान/संगीत।"),
Q("C",M,Y24,"Mahajanapadas count in 6th c. BCE?",["12","14","16","18"],"16 per Anguttara Nikaya. Magadha most powerful.","छठी शताब्दी ई.पू. में महाजनपद?",["12","14","16","18"],"अंगुत्तर निकाय अनुसार 16. मगध सबसे शक्तिशाली।"),
Q("B",E,Y24,"Chandragupta Maurya succeeded by?",["Ashoka","Bindusara","Samprati","Dasharatha"],"Bindusara (297-273 BCE), called Amitraghata.","चंद्रगुप्त मौर्य का उत्तराधिकारी?",["अशोक","बिंदुसार","संप्रति","दशरथ"],"बिंदुसार (297-273 ई.पू.), अमित्रघात।"),
Q("C",M,Y24,"Kalinga War year?",["273 BCE","269 BCE","261 BCE","250 BCE"],"261 BCE. Ashoka embraced Buddhism after.","कलिंग युद्ध वर्ष?",["273 ई.पू.","269 ई.पू.","261 ई.पू.","250 ई.पू."],"261 ई.पू.। बाद में अशोक ने बौद्ध धर्म अपनाया।"),
Q("D",M,Y24,"Megasthenes: envoy to?",["Ashoka","Bindusara","Samprati","Chandragupta Maurya"],"Greek ambassador, wrote Indica.","मेगस्थनीज़: राजदूत?",["अशोक","बिंदुसार","संप्रति","चंद्रगुप्त मौर्य"],"यूनानी राजदूत, इंडिका लिखी।"),
Q("A",M,Y24,"Last Mauryan ruler?",["Brihadratha","Ashoka","Dasharatha","Samprati"],"Killed by Pushyamitra Shunga 185 BCE.","अंतिम मौर्य शासक?",["बृहद्रथ","अशोक","दशरथ","संप्रति"],"185 ई.पू. में पुष्यमित्र शुंग ने हत्या की।"),
Q("B",H,Y24,"Arthashastra by?",["Megasthenes","Kautilya (Chanakya)","Kalidasa","Panini"],"Kautilya: treatise on statecraft, economics, military.","अर्थशास्त्र किसने?",["मेगस्थनीज़","कौटिल्य (चाणक्य)","कालिदास","पाणिनि"],"कौटिल्य: राजकाज, अर्थशास्त्र, सैन्य ग्रंथ।"),
Q("C",E,Y24,"Napoleon of India?",["Chandragupta Maurya","Ashoka","Samudragupta","Harsha"],"Samudragupta for extensive military campaigns.","भारत का नेपोलियन?",["चंद्रगुप्त मौर्य","अशोक","समुद्रगुप्त","हर्ष"],"समुद्रगुप्त, व्यापक सैन्य अभियानों के लिए।"),
Q("B",M,Y24,"Mehrauli Iron Pillar: which ruler?",["Samudragupta","Chandragupta II Vikramaditya","Kumaragupta I","Skandagupta"],"Rust-resistant pillar with Chandragupta II inscription.","महरौली स्तंभ: किससे जुड़ा?",["समुद्रगुप्त","चंद्रगुप्त द्वितीय विक्रमादित्य","कुमारगुप्त प्रथम","स्कंदगुप्त"],"जंग-रोधी, चंद्रगुप्त द्वितीय का शिलालेख।"),
Q("D",H,Y24,"Fa-Hien visited during whose reign?",["Samudragupta","Kumaragupta","Skandagupta","Chandragupta II"],"Chinese pilgrim (399-414 CE) described Gupta prosperity.","फाहियान किसके शासन में?",["समुद्रगुप्त","कुमारगुप्त","स्कंदगुप्त","चंद्रगुप्त द्वितीय"],"चीनी यात्री (399-414 ई.), गुप्त समृद्धि का वर्णन।"),
Q("A",M,Y24,"Gupta ruler titled Maharajadhiraja?",["Chandragupta I","Samudragupta","Chandragupta II","Skandagupta"],"Chandragupta I; started Gupta Era 319-320 CE.","महाराजाधिराज उपाधि?",["चंद्रगुप्त प्रथम","समुद्रगुप्त","चंद्रगुप्त द्वितीय","स्कंदगुप्त"],"चंद्रगुप्त प्रथम; गुप्त संवत 319-320 ई.।"),
Q("C",H,Y23,"Navratnas at whose court?",["Samudragupta","Kumaragupta","Chandragupta II","Skandagupta"],"Chandragupta II: Kalidasa, Varahamihira, Amarasimha.","नवरत्न किस दरबार में?",["समुद्रगुप्त","कुमारगुप्त","चंद्रगुप्त द्वितीय","स्कंदगुप्त"],"चंद्रगुप्त द्वितीय: कालिदास, वराहमिहिर, अमरसिंह।"),
Q("B",E,Y24,"Kalidasa flourished during?",["Mauryan","Gupta","Kushan","Harsha"],"Gupta period: Abhijnanashakuntalam, Meghaduta.","कालिदास किस काल में?",["मौर्य","गुप्त","कुषाण","हर्ष"],"गुप्त काल: अभिज्ञानशाकुंतलम, मेघदूत।"),
Q("C",M,Y24,"Harsha's capital?",["Pataliputra","Ujjain","Kannauj","Taxila"],"Harshavardhana (Pushyabhuti dynasty) at Kannauj.","हर्ष की राजधानी?",["पाटलिपुत्र","उज्जैन","कन्नौज","तक्षशिला"],"हर्षवर्धन (पुष्यभूति) की राजधानी कन्नौज।"),
Q("D",H,Y24,"Hiuen Tsang visited during?",["Ashoka","Chandragupta II","Samudragupta","Harshavardhana"],"Chinese monk (630-644 CE), studied at Nalanda.","ह्वेनसांग किसके शासन में?",["अशोक","चंद्रगुप्त द्वितीय","समुद्रगुप्त","हर्षवर्धन"],"चीनी भिक्षु (630-644 ई.), नालंदा में अध्ययन।"),
Q("B",H,Y23,"Harsha defeated by which Chalukya?",["Vikramaditya I","Pulakeshin II","Kirtivarman I","Mangalesha"],"Pulakeshin II on Narmada banks (~618 CE).","हर्ष किस चालुक्य से हारे?",["विक्रमादित्य प्रथम","पुलकेशिन द्वितीय","कीर्तिवर्मन प्रथम","मंगलेश"],"पुलकेशिन द्वितीय, नर्मदा तट पर (~618 ई.)।"),
Q("A",E,Y24,"Delhi Sultanate founder?",["Qutb-ud-din Aibak","Iltutmish","Alauddin Khilji","Balban"],"Aibak (1206), slave general of Muhammad Ghori.","दिल्ली सल्तनत के संस्थापक?",["कुतुब-उद-दीन ऐबक","इल्तुतमिश","अलाउद्दीन खिलजी","बलबन"],"ऐबक (1206), मुहम्मद गौरी का गुलाम सेनापति।"),
Q("B",M,Y24,"Token currency introduced by?",["Alauddin Khilji","Muhammad bin Tughlaq","Firoz Shah Tughlaq","Iltutmish"],"Muhammad bin Tughlaq (1330): brass/copper. Failed.","सांकेतिक मुद्रा किसने?",["अलाउद्दीन खिलजी","मुहम्मद बिन तुगलक","फिरोज शाह तुगलक","इल्तुतमिश"],"मुहम्मद बिन तुगलक (1330): पीतल/तांबा। विफल।"),
Q("C",H,Y23,"Market control policy by?",["Iltutmish","Balban","Alauddin Khilji","Muhammad bin Tughlaq"],"Alauddin: fixed prices, mandis, Shahna-i-Mandi.","बाजार नियंत्रण नीति?",["इल्तुतमिश","बलबन","अलाउद्दीन खिलजी","मुहम्मद बिन तुगलक"],"अलाउद्दीन: निश्चित मूल्य, मंडियाँ, शहना-ए-मंडी।"),
Q("A",M,Y24,"Correct Sultanate dynasty order?",["Slave→Khilji→Tughlaq→Sayyid→Lodi","Khilji→Slave→Tughlaq→Lodi→Sayyid","Slave→Tughlaq→Khilji→Lodi→Sayyid","Tughlaq→Slave→Khilji→Sayyid→Lodi"],"1206-90 Slave, 1290-1320 Khilji, 1320-1414 Tughlaq, 1414-51 Sayyid, 1451-1526 Lodi.","सही राजवंश क्रम?",["गुलाम→खिलजी→तुगलक→सैयद→लोदी","खिलजी→गुलाम→तुगलक→लोदी→सैयद","गुलाम→तुगलक→खिलजी→लोदी→सैयद","तुगलक→गुलाम→खिलजी→सैयद→लोदी"],"1206-90 गुलाम, 1290-1320 खिलजी, 1320-1414 तुगलक, 1414-51 सैयद, 1451-1526 लोदी।"),
Q("B",M,Y24,"Qutub Minar completed by?",["Qutb-ud-din Aibak","Iltutmish","Alauddin Khilji","Firoz Shah"],"Aibak started; Iltutmish completed. Firoz added floors.","कुतुब मीनार किसने पूरा किया?",["कुतुब-उद-दीन ऐबक","इल्तुतमिश","अलाउद्दीन खिलजी","फिरोज शाह"],"ऐबक ने शुरू; इल्तुतमिश ने पूरा। फिरोज ने मंजिलें जोड़ीं।"),
Q("C",E,Y24,"First Battle of Panipat: Babur defeated?",["Rana Sanga","Hemu","Ibrahim Lodi","Sher Shah"],"April 21, 1526: Babur used artillery.","पानीपत प्रथम: बाबर ने हराया?",["राणा सांगा","हेमू","इब्राहिम लोदी","शेरशाह"],"21 अप्रैल 1526: बाबर ने तोपखाने से।"),
Q("A",M,Y24,"Mansabdari system by?",["Akbar","Babur","Humayun","Shah Jahan"],"Akbar (~1570): zat and sawar ranking system.","मनसबदारी प्रणाली?",["अकबर","बाबर","हुमायूं","शाहजहां"],"अकबर (~1570): जात और सवार रैंकिंग।"),
Q("B",M,Y24,"Din-i-Ilahi founded by?",["Jahangir","Akbar","Shah Jahan","Aurangzeb"],"Akbar (1582): syncretic faith.","दीन-ए-इलाही?",["जहांगीर","अकबर","शाहजहां","औरंगज़ेब"],"अकबर (1582): समन्वयात्मक धर्म।"),
Q("D",E,Y24,"Taj Mahal built in memory of?",["Nur Jahan","Jahanara","Mumtaz Begum","Mumtaz Mahal"],"Shah Jahan for his wife. 1632-1653.","ताजमहल किसकी याद में?",["नूरजहां","जहांआरा","मुमताज बेगम","मुमताज महल"],"शाहजहां ने पत्नी की याद में। 1632-1653।"),
Q("C",H,Y24,"Zinda Pir (Living Saint)?",["Akbar","Jahangir","Aurangzeb","Shah Jahan"],"Aurangzeb: strict orthodoxy, re-imposed Jizya.","जिंदा पीर?",["अकबर","जहांगीर","औरंगज़ेब","शाहजहां"],"औरंगज़ेब: सख्त रूढ़िवाद, जजिया पुनः लागू।"),
Q("B",M,Y24,"Fatehpur Sikri built by?",["Humayun","Akbar","Jahangir","Shah Jahan"],"Akbar (1571-1585), abandoned for water shortage.","फतेहपुर सीकरी?",["हुमायूं","अकबर","जहांगीर","शाहजहां"],"अकबर (1571-1585), पानी की कमी से छोड़ा।"),
Q("D",H,Y23,"Second Battle of Panipat between?",["Babur-Ibrahim Lodi","Humayun-Sher Shah","Akbar-Rana Pratap","Akbar (Bairam Khan) and Hemu"],"1556: Bairam Khan led Mughals; Hemu defeated.","दूसरा पानीपत युद्ध?",["बाबर-इब्राहिम","हुमायूं-शेरशाह","अकबर-राणा प्रताप","अकबर (बैरम खां) और हेमू"],"1556: बैरम खां ने हेमू को हराया।"),
Q("A",M,Y24,"Buland Darwaza built by?",["Akbar","Shah Jahan","Jahangir","Aurangzeb"],"Akbar (1601), Fatehpur Sikri, Gujarat conquest.","बुलंद दरवाजा?",["अकबर","शाहजहां","जहांगीर","औरंगज़ेब"],"अकबर (1601), फतेहपुर सीकरी, गुजरात विजय।"),
Q("C",M,Y24,"Jahangir's autobiography?",["Akbarnama","Humayunnama","Tuzuk-i-Jahangiri","Shahjahannama"],"Tuzuk-i-Jahangiri: his own memoirs.","जहांगीर की आत्मकथा?",["अकबरनामा","हुमायूंनामा","तुज़ुक-ए-जहांगीरी","शाहजहांनामा"],"तुज़ुक-ए-जहांगीरी: उनके स्वयं के संस्मरण।"),
Q("B",H,Y24,"Nur Jahan's real name?",["Arjumand Banu","Mehr-un-Nisa","Jodha Bai","Manmati"],"Mehr-un-Nisa; married Jahangir 1611.","नूरजहां का असली नाम?",["अर्जुमंद बानू","मेहर-उन-निसा","जोधा बाई","मनमती"],"मेहर-उन-निसा; 1611 में जहांगीर से विवाह।"),
Q("B",E,Y24,"Red Fort Delhi built by?",["Akbar","Shah Jahan","Humayun","Aurangzeb"],"Shah Jahan (1639-1648), Shahjahanabad.","लाल किला किसने?",["अकबर","शाहजहां","हुमायूं","औरंगज़ेब"],"शाहजहां (1639-1648), शाहजहानाबाद।"),
Q("B",M,Y24,"Shivaji crowned Chhatrapati in?",["1670","1674","1680","1646"],"June 6, 1674 at Raigad Fort.","शिवाजी का राज्याभिषेक?",["1670","1674","1680","1646"],"6 जून 1674, रायगढ़ किला।"),
Q("D",H,Y23,"Third Battle of Panipat between?",["British vs Marathas","Mughals vs Marathas","Sikhs vs Marathas","Marathas vs Ahmad Shah Abdali"],"1761: Sadashivrao Bhau vs Abdali. Maratha defeat.","तीसरा पानीपत?",["अंग्रेज़-मराठा","मुगल-मराठा","सिख-मराठा","मराठा-अहमद शाह अब्दाली"],"1761: सदाशिवराव भाऊ बनाम अब्दाली। मराठा हार।"),
Q("C",E,Y24,"1857 Revolt began at?",["Delhi","Kanpur","Meerut","Lucknow"],"May 10, 1857: sepoys refused greased cartridges.","1857 विद्रोह शुरू?",["दिल्ली","कानपुर","मेरठ","लखनऊ"],"10 मई 1857: सिपाहियों ने कारतूसों से इनकार।"),
Q("A",M,Y24,"1857 revolt leader at Kanpur?",["Nana Sahib","Tantia Tope","Rani Lakshmibai","Kunwar Singh"],"Nana Sahib, adopted son of Peshwa Baji Rao II.","कानपुर में नेता?",["नाना साहब","तांत्या टोपे","रानी लक्ष्मीबाई","कुंवर सिंह"],"नाना साहब, पेशवा बाजीराव द्वितीय के दत्तक पुत्र।"),
Q("B",E,Y24,"Rani Lakshmibai: which center?",["Kanpur","Jhansi","Delhi","Bareilly"],"Rani of Jhansi; died at Gwalior June 1858.","रानी लक्ष्मीबाई?",["कानपुर","झांसी","दिल्ली","बरेली"],"झांसी की रानी; जून 1858 को ग्वालियर में शहीद।"),
Q("A",M,Y24,"INC founded in?",["1885","1890","1900","1882"],"Dec 28, 1885 Bombay. W.C. Bonnerjee president.","INC स्थापना?",["1885","1890","1900","1882"],"28 दिसंबर 1885 बॉम्बे। डब्ल्यू.सी. बनर्जी अध्यक्ष।"),
Q("D",H,Y23,"1929 Lahore INC president?",["Gandhi","Motilal Nehru","Subhas Bose","Jawaharlal Nehru"],"Nehru; Purna Swaraj resolution passed.","1929 लाहौर अध्यक्ष?",["गांधी","मोतीलाल नेहरू","सुभाष बोस","जवाहरलाल नेहरू"],"नेहरू; पूर्ण स्वराज प्रस्ताव।"),
Q("C",E,Y24,"'Do or Die' by?",["Subhas Bose","Nehru","Mahatma Gandhi","Patel"],"Gandhi, Aug 8, 1942 Quit India Movement.","'करो या मरो'?",["सुभाष बोस","नेहरू","महात्मा गांधी","पटेल"],"गांधी, 8 अगस्त 1942 भारत छोड़ो।"),
Q("B",M,Y24,"Dandi March began?",["Mar 12, 1931","Mar 12, 1930","Apr 6, 1930","Apr 12, 1930"],"March 12, 1930 from Sabarmati to Dandi.","दांडी मार्च?",["12 मार्च 1931","12 मार्च 1930","6 अप्रैल 1930","12 अप्रैल 1930"],"12 मार्च 1930 साबरमती से दांडी।"),
Q("B",E,Y24,"British PM at independence?",["Churchill","Clement Attlee","Chamberlain","Macmillan"],"Attlee (Labour); sent Cabinet Mission.","स्वतंत्रता पर ब्रिटिश PM?",["चर्चिल","क्लेमेंट एटली","चैंबरलेन","मैकमिलन"],"एटली (लेबर); कैबिनेट मिशन भेजा।"),
Q("C",M,Y24,"Radcliffe Line drawn by?",["Mountbatten","Cripps","Cyril Radcliffe","Alexander"],"Sir Cyril Radcliffe, Boundary Commission.","रैडक्लिफ रेखा?",["माउंटबेटन","क्रिप्स","सिरिल रैडक्लिफ","अलेक्जेंडर"],"सर सिरिल रैडक्लिफ, सीमा आयोग।"),
Q("D",M,Y24,"Iron Man of India?",["Gandhi","Nehru","Ambedkar","Sardar Patel"],"Patel integrated 560+ princely states.","भारत का लौह पुरुष?",["गांधी","नेहरू","अंबेडकर","सरदार पटेल"],"पटेल ने 560+ रियासतें मिलाईं।"),
Q("B",M,Y24,"Buddha's enlightenment at?",["Lumbini","Bodh Gaya","Sarnath","Kushinagar"],"Bodh Gaya under Bodhi tree.","बुद्ध का ज्ञान?",["लुंबिनी","बोध गया","सारनाथ","कुशीनगर"],"बोध गया, बोधि वृक्ष के नीचे।"),
Q("D",H,Y23,"First Buddhist Council at?",["Vaishali","Pataliputra","Kashmir","Rajgriha"],"483 BCE, Ajatashatru, Mahakasyapa.","प्रथम बौद्ध संगीति?",["वैशाली","पाटलिपुत्र","कश्मीर","राजगृह"],"483 ई.पू., अजातशत्रु, महाकश्यप।"),
Q("C",E,Y24,"24th Jain Tirthankara?",["Rishabhanatha","Parshvanatha","Mahavira","Neminatha"],"Mahavira (Vardhamana).","24वें जैन तीर्थंकर?",["ऋषभनाथ","पार्श्वनाथ","महावीर","नेमिनाथ"],"महावीर (वर्धमान)।"),
Q("A",M,Y24,"Shunga dynasty founder?",["Pushyamitra Shunga","Agnimitra","Vasumitra","Devabhuti"],"Killed Brihadratha 185 BCE.","शुंग वंश संस्थापक?",["पुष्यमित्र शुंग","अग्निमित्र","वसुमित्र","देवभूति"],"185 ई.पू. में बृहद्रथ की हत्या।"),
Q("C",E,Y24,"Simon Commission arrived?",["1925","1927","1928","1930"],"1928. 'Simon Go Back' slogan.","साइमन कमीशन?",["1925","1927","1928","1930"],"1928. 'साइमन वापस जाओ'।"),
Q("B",H,Y23,"'Dilli Chalo' call by?",["Gandhi","Subhas Chandra Bose","Nehru","Bhagat Singh"],"Netaji Bose to INA soldiers.","'दिल्ली चलो'?",["गांधी","सुभाष चंद्र बोस","नेहरू","भगत सिंह"],"नेताजी बोस ने INA सैनिकों को।"),
Q("A",E,Y24,"Viceroy during Partition?",["Lord Mountbatten","Lord Wavell","Lord Linlithgow","Lord Irwin"],"Last Viceroy (1947-48).","विभाजन के समय वायसराय?",["लॉर्ड माउंटबेटन","लॉर्ड वेवेल","लॉर्ड लिनलिथगो","लॉर्ड इरविन"],"अंतिम वायसराय (1947-48)।"),
Q("D",M,Y24,"Rowlatt Act passed?",["1915","1917","1918","1919"],"1919: detention without trial.","रॉलेट एक्ट?",["1915","1917","1918","1919"],"1919: बिना मुकदमे नज़रबंदी।"),
Q("C",M,Y24,"Khilafat Movement year?",["1917","1918","1919","1920"],"1919; Ali brothers, Gandhi's support.","खिलाफत आंदोलन?",["1917","1918","1919","1920"],"1919; अली बंधु, गांधी का समर्थन।"),
Q("B",E,Y24,"Jallianwala Bagh date?",["Apr 13, 1918","Apr 13, 1919","Apr 13, 1920","Apr 13, 1921"],"April 13, 1919 (Baisakhi). General Dyer.","जलियांवाला बाग?",["13 अप्रैल 1918","13 अप्रैल 1919","13 अप्रैल 1920","13 अप्रैल 1921"],"13 अप्रैल 1919 (बैसाखी)। जनरल डायर।")]
tot+=proc("indian-history.json",H); print(f"  History: {len(H)} Qs added.\n")
print(f"Batch 1 complete! Total added: {tot} questions.")
