#!/usr/bin/env python3
"""Batch 1: Indian History, Geography, Polity, Economics, General Science (~325 Qs)"""
import json, os
BASE = r"C:\Users\core\rrb-exam-prep\public\data\questions\ntpc\general-awareness"
E,M,H="easy","medium","hard"
Y24,Y23,Y25=2024,2023,2025
def Q(c,d,y,eq,eo,ex,hq,ho,hx):
    return {"correctOption":c,"difficulty":d,"sourceYear":y,"en":{"question":eq,"options":eo,"explanation":ex},"hi":{"question":hq,"options":ho,"explanation":hx}}
def proc(fn,qs):
    p=os.path.join(BASE,fn)
    with open(p,'r',encoding='utf-8') as f: data=json.load(f)
    s=int(data[-1]['id'].split('-')[-1]) if data else 0
    for i,q in enumerate(qs): q['id']=f"ntpc-ga-{s+i+1:04d}"
    data.extend(qs)
    with open(p,'w',encoding='utf-8') as f: json.dump(data,f,ensure_ascii=False,indent=2)
    print(f"  {fn}: +{len(qs)} = {len(data)} total")
    return len(qs)
tot=0
print("\n=== Batch 1: History, Geography, Polity, Economics, General Science ===\n")

# ====== 1. INDIAN HISTORY (65 new Qs) ======
print("1. Indian History")
H=[Q("C",E,Y24,"Largest Indus Valley site?",["Mohenjo-daro","Harappa","Rakhigarhi","Dholavira"],"Rakhigarhi (Haryana) spanning over 350 hectares is now considered the largest IVC site.","सबसे बड़ा सिंधु घाटी स्थल?",["मोहनजोदड़ो","हड़प्पा","राखीगढ़ी","धोलावीरा"],"हरियाणा में राखीगढ़ी 350 हेक्टेयर से अधिक क्षेत्र में फैला सबसे बड़ा सिंधु घाटी स्थल माना जाता है।"),
Q("B",M,Y24,"Great Bath found at which Indus site?",["Harappa","Mohenjo-daro","Lothal","Kalibangan"],"Great Bath at Mohenjo-daro: large rectangular water tank, likely used for ritual bathing.","महान स्नानागार किस सिंधु स्थल पर मिला?",["हड़प्पा","मोहनजोदड़ो","लोथल","कालीबंगा"],"मोहनजोदड़ो का महान स्नानागार: बड़ा आयताकार जल कुंड, संभवतः अनुष्ठान स्नान हेतु।"),
Q("D",M,Y24,"Indus site famous for dockyard?",["Mohenjo-daro","Harappa","Kalibangan","Lothal"],"Lothal (Gujarat) had a remarkable dockyard connected to Sabarmati River.","बंदरगाह के लिए प्रसिद्ध सिंधु स्थल?",["मोहनजोदड़ो","हड़प्पा","कालीबंगा","लोथल"],"गुजरात में लोथल में साबरमती नदी से जुड़ा उल्लेखनीय बंदरगाह था।"),
Q("A",E,Y24,"Indus people worshipped which deity?",["Pashupati (Proto-Shiva)","Vishnu","Brahma","Indra"],"The Pashupati seal shows a horned figure surrounded by animals, considered proto-Shiva.","सिंधु लोग किस देवता की पूजा करते थे?",["पशुपति (आदि-शिव)","विष्णु","ब्रह्मा","इंद्र"],"पशुपति मुहर में पशुओं से घिरी सींग वाली आकृति दिखती है, जिसे आदि-शिव माना जाता है।"),
Q("B",M,Y24,"Metal unknown to Indus Valley people?",["Copper","Iron","Bronze","Gold"],"Iron was unknown. They used copper, bronze, gold, silver, and lead.","सिंधु घाटी के लोग किस धातु से अनजान थे?",["तांबा","लोहा","कांसा","सोना"],"लोहा अज्ञात था। वे तांबा, कांसा, सोना, चांदी और सीसा का उपयोग करते थे।"),
Q("A",E,Y24,"Oldest Veda?",["Rigveda","Samaveda","Yajurveda","Atharvaveda"],"Rigveda (~1500-1200 BCE): 1,028 hymns in 10 mandalas.","सबसे पुराना वेद?",["ऋग्वेद","सामवेद","यजुर्वेद","अथर्ववेद"],"ऋग्वेद (लगभग 1500-1200 ई.पू.): 10 मंडलों में 1,028 सूक्त।"),
Q("C",M,Y24,"Gayatri Mantra found in which Veda?",["Samaveda","Yajurveda","Rigveda","Atharvaveda"],"Rigveda Mandala 3, Hymn 62, Verse 10, dedicated to Savitr.","गायत्री मंत्र किस वेद में है?",["सामवेद","यजुर्वेद","ऋग्वेद","अथर्ववेद"],"ऋग्वेद मंडल 3, सूक्त 62, श्लोक 10, सविता को समर्पित।"),
Q("B",E,Y24,"Rishi who composed Gayatri Mantra?",["Vasishta","Vishwamitra","Atri","Agastya"],"Vishwamitra composed several Rigvedic hymns including the Gayatri Mantra.","गायत्री मंत्र की रचना किस ऋषि ने की?",["वसिष्ठ","विश्वामित्र","अत्रि","अगस्त्य"],"विश्वामित्र ने गायत्री मंत्र सहित कई ऋग्वैदिक सूक्तों की रचना की।"),
Q("D",H,Y23,"Battle of Ten Kings fought on which river?",["Ganga","Yamuna","Saraswati","Ravi (Parushni)"],"King Sudas (Bharata) vs ten tribes on Ravi. Sudas won.","दस राजाओं का युद्ध किस नदी पर?",["गंगा","यमुना","सरस्वती","रावी (परुष्णी)"],"राजा सुदास (भरत) बनाम दस जनजातियाँ, रावी पर। सुदास विजयी।"),
Q("B",M,Y24,"Samaveda is primarily known as?",["Book of Hymns","Book of Chants","Book of Sacrifices","Book of Spells"],"Samaveda has melodies/chants for sacrificial rituals from Rigvedic hymns.","सामवेद मुख्यतः किस रूप में जाना जाता है?",["सूक्तों की पुस्तक","गानों की पुस्तक","यज्ञों की पुस्तक","मंत्रों की पुस्तक"],"सामवेद में ऋग्वैदिक सूक्तों से यज्ञानुष्ठानों के लिए गान/संगीत।"),
Q("C",M,Y24,"Mahajanapadas count in 6th century BCE?",["12","14","16","18"],"16 Mahajanapadas per Anguttara Nikaya. Magadha became most powerful.","छठी शताब्दी ई.पू. में महाजनपदों की संख्या?",["12","14","16","18"],"अंगुत्तर निकाय के अनुसार 16. मगध सबसे शक्तिशाली बना।"),
Q("B",E,Y24,"Chandragupta Maurya succeeded by?",["Ashoka","Bindusara","Samprati","Dasharatha"],"Bindusara (297-273 BCE) called Amitraghata (slayer of enemies).","चंद्रगुप्त मौर्य का उत्तराधिकारी?",["अशोक","बिंदुसार","संप्रति","दशरथ"],"बिंदुसार (297-273 ई.पू.), अमित्रघात (शत्रुओं का विनाशक) कहलाए।"),
Q("C",M,Y24,"Year of Kalinga War?",["273 BCE","269 BCE","261 BCE","250 BCE"],"261 BCE. Its horrors turned Ashoka towards Buddhism and Dhamma.","कलिंग युद्ध का वर्ष?",["273 ई.पू.","269 ई.पू.","261 ई.पू.","250 ई.पू."],"261 ई.पू.। इसकी भयावहता ने अशोक को बौद्ध धर्म और धम्म की ओर मोड़ा।"),
Q("D",M,Y24,"Megasthenes: envoy to which Mauryan?",["Ashoka","Bindusara","Samprati","Chandragupta Maurya"],"Greek ambassador from Seleucus Nicator. Wrote Indica about Mauryan India.","मेगस्थनीज़: किस मौर्य का राजदूत?",["अशोक","बिंदुसार","संप्रति","चंद्रगुप्त मौर्य"],"सेल्यूकस निकेटर का यूनानी राजदूत। मौर्य भारत पर इंडिका लिखी।"),
Q("A",M,Y24,"Last Mauryan ruler?",["Brihadratha","Ashoka","Dasharatha","Samprati"],"Assassinated by Pushyamitra Shunga in 185 BCE, ending Mauryan dynasty.","अंतिम मौर्य शासक?",["बृहद्रथ","अशोक","दशरथ","संप्रति"],"185 ई.पू. में पुष्यमित्र शुंग द्वारा हत्या, मौर्य वंश समाप्त।"),
Q("B",H,Y24,"Author of Arthashastra?",["Megasthenes","Kautilya (Chanakya)","Kalidasa","Panini"],"Kautilya/Chanakya/Vishnugupta: treatise on statecraft, economics, military.","अर्थशास्त्र के लेखक?",["मेगस्थनीज़","कौटिल्य (चाणक्य)","कालिदास","पाणिनि"],"कौटिल्य/चाणक्य/विष्णुगुप्त: राजकाज, अर्थशास्त्र, सैन्य पर ग्रंथ।"),
Q("C",E,Y24,"Napoleon of India?",["Chandragupta Maurya","Ashoka","Samudragupta","Harsha"],"Samudragupta for extensive conquests documented in Allahabad Pillar inscription.","भारत का नेपोलियन?",["चंद्रगुप्त मौर्य","अशोक","समुद्रगुप्त","हर्ष"],"समुद्रगुप्त, इलाहाबाद स्तंभ शिलालेख में वर्णित व्यापक विजयों के लिए।"),
Q("B",M,Y24,"Mehrauli Iron Pillar associated with?",["Samudragupta","Chandragupta II Vikramaditya","Kumaragupta I","Skandagupta"],"Rust-resistant pillar bears inscription of Chandragupta II.","महरौली का लौह स्तंभ किससे जुड़ा?",["समुद्रगुप्त","चंद्रगुप्त द्वितीय विक्रमादित्य","कुमारगुप्त प्रथम","स्कंदगुप्त"],"जंग-रोधी स्तंभ पर चंद्रगुप्त द्वितीय का शिलालेख।"),
Q("D",H,Y24,"Fa-Hien visited during whose reign?",["Samudragupta","Kumaragupta","Skandagupta","Chandragupta II"],"Chinese pilgrim Fa-Hien (399-414 CE) during Chandragupta II's reign.","फाहियान किसके शासन में आए?",["समुद्रगुप्त","कुमारगुप्त","स्कंदगुप्त","चंद्रगुप्त द्वितीय"],"चीनी यात्री फाहियान (399-414 ई.) चंद्रगुप्त द्वितीय के शासन में।"),
Q("A",M,Y24,"Gupta ruler titled Maharajadhiraja?",["Chandragupta I","Samudragupta","Chandragupta II","Skandagupta"],"Chandragupta I; also started Gupta Era (319-320 CE).","महाराजाधिराज उपाधि किस गुप्त शासक ने ली?",["चंद्रगुप्त प्रथम","समुद्रगुप्त","चंद्रगुप्त द्वितीय","स्कंदगुप्त"],"चंद्रगुप्त प्रथम; गुप्त संवत (319-320 ई.) भी शुरू किया।"),
Q("C",H,Y23,"Navratnas at whose Gupta court?",["Samudragupta","Kumaragupta","Chandragupta II","Skandagupta"],"Chandragupta II's court: Kalidasa, Varahamihira, Amarasimha, Dhanvantari etc.","नवरत्न किस गुप्त दरबार में?",["समुद्रगुप्त","कुमारगुप्त","चंद्रगुप्त द्वितीय","स्कंदगुप्त"],"चंद्रगुप्त द्वितीय के दरबार में कालिदास, वराहमिहिर, अमरसिंह, धन्वंतरि आदि।"),
Q("B",E,Y24,"Kalidasa flourished during which period?",["Mauryan","Gupta","Kushan","Harsha"],"Gupta period; wrote Abhijnanashakuntalam, Meghaduta, Raghuvamsha.","कालिदास किस काल के कवि थे?",["मौर्य","गुप्त","कुषाण","हर्ष"],"गुप्त काल; अभिज्ञानशाकुंतलम, मेघदूत, रघुवंश लिखा।"),
Q("C",M,Y24,"Harsha's capital?",["Pataliputra","Ujjain","Kannauj","Taxila"],"Harshavardhana (Pushyabhuti dynasty) made Kannauj his capital.","हर्ष की राजधानी?",["पाटलिपुत्र","उज्जैन","कन्नौज","तक्षशिला"],"हर्षवर्धन (पुष्यभूति वंश) ने कन्नौज को राजधानी बनाया।"),
Q("D",H,Y24,"Hiuen Tsang visited during whose reign?",["Ashoka","Chandragupta II","Samudragupta","Harshavardhana"],"Chinese monk Hiuen Tsang (Xuanzang) visited 630-644 CE, studied at Nalanda.","ह्वेनसांग किसके शासनकाल में आए?",["अशोक","चंद्रगुप्त द्वितीय","समुद्रगुप्त","हर्षवर्धन"],"चीनी भिक्षु ह्वेनसांग (630-644 ई.) नालंदा में पढ़े।"),
Q("B",H,Y23,"Harsha defeated by which Chalukya king?",["Vikramaditya I","Pulakeshin II","Kirtivarman I","Mangalesha"],"Pulakeshin II defeated Harsha on Narmada river banks (~618 CE).","हर्ष किस चालुक्य राजा से पराजित हुए?",["विक्रमादित्य प्रथम","पुलकेशिन द्वितीय","कीर्तिवर्मन प्रथम","मंगलेश"],"पुलकेशिन द्वितीय ने नर्मदा तट पर हर्ष को हराया (लगभग 618 ई.)।"),
Q("A",E,Y24,"Who founded Delhi Sultanate?",["Qutb-ud-din Aibak","Iltutmish","Alauddin Khilji","Balban"],"Qutb-ud-din Aibak (1206), slave general of Muhammad Ghori, founded Slave/Mamluk dynasty.","दिल्ली सल्तनत की स्थापना किसने की?",["कुतुब-उद-दीन ऐबक","इल्तुतमिश","अलाउद्दीन खिलजी","बलबन"],"कुतुब-उद-दीन ऐबक (1206), मुहम्मद गौरी का गुलाम सेनापति।"),
Q("B",M,Y24,"Token currency introduced by?",["Alauddin Khilji","Muhammad bin Tughlaq","Firoz Shah Tughlaq","Iltutmish"],"Muhammad bin Tughlaq (1330): brass/copper tokens. Failed due to forgery.","सांकेतिक मुद्रा किसने शुरू की?",["अलाउद्दीन खिलजी","मुहम्मद बिन तुगलक","फिरोज शाह तुगलक","इल्तुतमिश"],"मुहम्मद बिन तुगलक (1330): पीतल/तांबे के सिक्के। जालसाजी से विफल।"),
Q("C",H,Y23,"Market control policy by which Sultan?",["Iltutmish","Balban","Alauddin Khilji","Muhammad bin Tughlaq"],"Alauddin Khilji: fixed prices, separate mandis, appointed Shahna-i-Mandi.","बाजार नियंत्रण नीति किस सुल्तान ने लागू की?",["इल्तुतमिश","बलबन","अलाउद्दीन खिलजी","मुहम्मद बिन तुगलक"],"अलाउद्दीन खिलजी: निश्चित मूल्य, अलग मंडियाँ, शहना-ए-मंडी नियुक्त।"),
Q("A",M,Y24,"Correct Delhi Sultanate dynasty order?",["Slave→Khilji→Tughlaq→Sayyid→Lodi","Khilji→Slave→Tughlaq→Lodi→Sayyid","Slave→Tughlaq→Khilji→Lodi→Sayyid","Tughlaq→Slave→Khilji→Sayyid→Lodi"],"1206-1290 Slave, 1290-1320 Khilji, 1320-1414 Tughlaq, 1414-1451 Sayyid, 1451-1526 Lodi.","दिल्ली सल्तनत के राजवंशों का सही क्रम?",["गुलाम→खिलजी→तुगलक→सैयद→लोदी","खिलजी→गुलाम→तुगलक→लोदी→सैयद","गुलाम→तुगलक→खिलजी→लोदी→सैयद","तुगलक→गुलाम→खिलजी→सैयद→लोदी"],"1206-1290 गुलाम, 1290-1320 खिलजी, 1320-1414 तुगलक, 1414-1451 सैयद, 1451-1526 लोदी।"),
Q("B",M,Y24,"Qutub Minar completed by?",["Qutb-ud-din Aibak","Iltutmish","Alauddin Khilji","Firoz Shah Tughlaq"],"Aibak started; Iltutmish completed. Firoz repaired and added floors.","कुतुब मीनार किसने पूरा करवाया?",["कुतुब-उद-दीन ऐबक","इल्तुतमिश","अलाउद्दीन खिलजी","फिरोज शाह तुगलक"],"ऐबक ने शुरू करवाया; इल्तुतमिश ने पूरा करवाया। फिरोज ने मरम्मत कर मंजिलें जोड़ीं।"),
Q("D",H,Y24,"Iqta system under Delhi Sultanate was?",["Tax collection","Military rank","Judicial system","Land revenue assignment"],"Iqta: assigning land revenue to officers/soldiers in lieu of salary. Introduced by Iltutmish.","दिल्ली सल्तनत में इक्ता प्रणाली क्या थी?",["कर संग्रह","सैन्य रैंक","न्यायिक प्रणाली","भू-राजस्व असाइनमेंट"],"इक्ता: वेतन के बदले अधिकारियों/सैनिकों को भू-राजस्व देना। इल्तुतमिश ने शुरू किया।"),
Q("C",E,Y24,"First Battle of Panipat: Babur defeated?",["Rana Sanga","Hemu","Ibrahim Lodi","Sher Shah Suri"],"April 21, 1526: Babur used artillery and Tuluguma tactics to defeat Ibrahim Lodi.","पानीपत का पहला युद्ध: बाबर ने किसे हराया?",["राणा सांगा","हेमू","इब्राहिम लोदी","शेर शाह सूरी"],"21 अप्रैल 1526: बाबर ने तोपखाने और तुलुगुमा रणनीति से इब्राहिम लोदी को हराया।"),
Q("A",M,Y24,"Mansabdari system introduced by which Mughal?",["Akbar","Babur","Humayun","Shah Jahan"],"Akbar (~1570): military-cum-admin system ranking officers by zat and sawar.","मनसबदारी प्रणाली किस मुगल ने शुरू की?",["अकबर","बाबर","हुमायूं","शाहजहां"],"अकबर (लगभग 1570): जात और सवार द्वारा अधिकारियों की रैंकिंग।"),
Q("B",M,Y24,"Din-i-Ilahi founded by?",["Jahangir","Akbar","Shah Jahan","Aurangzeb"],"Akbar (1582): syncretic faith combining elements of various religions.","दीन-ए-इलाही की स्थापना किसने की?",["जहांगीर","अकबर","शाहजहां","औरंगज़ेब"],"अकबर (1582): विभिन्न धर्मों के तत्वों का समन्वयात्मक धर्म।"),
Q("D",E,Y24,"Taj Mahal built in memory of?",["Nur Jahan","Jahanara","Mumtaz Begum","Mumtaz Mahal"],"Shah Jahan built it in Agra (1632-1653) for his wife Mumtaz Mahal.","ताजमहल किसकी याद में बना?",["नूरजहां","जहांआरा","मुमताज बेगम","मुमताज महल"],"शाहजहां ने पत्नी मुमताज महल की याद में आगरा में (1632-1653) बनवाया।"),
Q("C",H,Y24,"Mughal emperor called Zinda Pir?",["Akbar","Jahangir","Aurangzeb","Shah Jahan"],"Aurangzeb: strict Islamic orthodoxy, re-imposed Jizya, banned court music.","किस मुगल को जिंदा पीर कहा गया?",["अकबर","जहांगीर","औरंगज़ेब","शाहजहां"],"औरंगज़ेब: सख्त इस्लामी रूढ़िवाद, जजिया पुनः लागू, दरबारी संगीत पर प्रतिबंध।"),
Q("B",M,Y24,"Fatehpur Sikri built by?",["Humayun","Akbar","Jahangir","Shah Jahan"],"Akbar built it as capital (1571-1585), abandoned due to water shortage.","फतेहपुर सीकरी किसने बनवाया?",["हुमायूं","अकबर","जहांगीर","शाहजहां"],"अकबर ने राजधानी के रूप में (1571-1585); पानी की कमी से छोड़ा।"),
Q("D",H,Y23,"Second Battle of Panipat fought between?",["Babur and Ibrahim Lodi","Humayun and Sher Shah","Akbar and Rana Pratap","Akbar (Bairam Khan) and Hemu"],"1556: Bairam Khan led Mughal army; defeated Hemu. Akbar was only 13.","पानीपत का दूसरा युद्ध किसके बीच?",["बाबर और इब्राहिम लोदी","हुमायूं और शेरशाह","अकबर और राणा प्रताप","अकबर (बैरम खां) और हेमू"],"1556: बैरम खां के नेतृत्व में मुगल सेना ने हेमू को हराया। अकबर केवल 13 वर्ष के थे।"),
Q("A",M,Y24,"Buland Darwaza built by?",["Akbar","Shah Jahan","Jahangir","Aurangzeb"],"Akbar (1601) at Fatehpur Sikri to commemorate Gujarat conquest.","बुलंद दरवाजा किसने बनवाया?",["अकबर","शाहजहां","जहांगीर","औरंगज़ेब"],"अकबर (1601) फतेहपुर सीकरी में, गुजरात विजय के उपलक्ष्य में।"),
Q("C",M,Y24,"Jahangir's autobiography?",["Akbarnama","Humayunnama","Tuzuk-i-Jahangiri","Shahjahannama"],"Tuzuk-i-Jahangiri: Jahangir's memoirs written by himself.","जहांगीर की आत्मकथा?",["अकबरनामा","हुमायूंनामा","तुज़ुक-ए-जहांगीरी","शाहजहांनामा"],"तुज़ुक-ए-जहांगीरी: जहांगीर के स्वलिखित संस्मरण।"),
Q("B",H,Y24,"Nur Jahan's original name?",["Arjumand Banu Begum","Mehr-un-Nisa","Jodha Bai","Manmati"],"Mehr-un-Nisa; Jahangir gave her title Nur Jahan after marriage in 1611.","नूरजहां का मूल नाम?",["अर्जुमंद बानू बेगम","मेहर-उन-निसा","जोधा बाई","मनमती"],"मेहर-उन-निसा; जहांगीर ने 1611 में विवाह के बाद नूरजहां उपाधि दी।"),
Q("B",E,Y24,"Red Fort (Delhi) built by?",["Akbar","Shah Jahan","Humayun","Aurangzeb"],"Shah Jahan (1639-1648) when shifting capital to Shahjahanabad.","लाल किला (दिल्ली) किसने बनवाया?",["अकबर","शाहजहां","हुमायूं","औरंगज़ेब"],"शाहजहां (1639-1648), शाहजहानाबाद में राजधानी स्थानांतरित करते समय।"),
Q("B",M,Y24,"Shivaji crowned Chhatrapati in?",["1670","1674","1680","1646"],"June 6, 1674 at Raigad Fort; ceremony by scholar Gaga Bhatt.","शिवाजी का छत्रपति राज्याभिषेक कब?",["1670","1674","1680","1646"],"6 जून 1674, रायगढ़ किले में; विद्वान गागा भट्ट द्वारा।"),
Q("D",H,Y23,"Third Battle of Panipat fought between?",["British vs Marathas","Mughals vs Marathas","Sikhs vs Marathas","Marathas vs Ahmad Shah Abdali"],"1761: Sadashivrao Bhau (Marathas) vs Abdali. Devastating Maratha defeat.","पानीपत का तीसरा युद्ध किसके बीच?",["अंग्रेज़ बनाम मराठा","मुगल बनाम मराठा","सिख बनाम मराठा","मराठा बनाम अहमद शाह अब्दाली"],"1761: सदाशिवराव भाऊ (मराठा) बनाम अब्दाली। मराठों की विनाशकारी हार।"),
Q("C",E,Y24,"1857 Revolt began at?",["Delhi","Kanpur","Meerut","Lucknow"],"May 10, 1857 at Meerut; sepoys refused greased cartridges.","1857 का विद्रोह कहाँ शुरू हुआ?",["दिल्ली","कानपुर","मेरठ","लखनऊ"],"10 मई 1857, मेरठ; सिपाहियों ने चर्बीयुक्त कारतूसों से इनकार किया।"),
Q("A",M,Y24,"Leader of 1857 revolt at Kanpur?",["Nana Sahib","Tantia Tope","Rani Lakshmibai","Kunwar Singh"],"Nana Sahib (Dhondu Pant), adopted son of last Peshwa Baji Rao II.","कानपुर में 1857 विद्रोह का नेता?",["नाना साहब","तांत्या टोपे","रानी लक्ष्मीबाई","कुंवर सिंह"],"नाना साहब (धोंडू पंत), अंतिम पेशवा बाजीराव द्वितीय के दत्तक पुत्र।"),
Q("B",E,Y24,"Rani Lakshmibai associated with which center?",["Kanpur","Jhansi","Delhi","Bareilly"],"Rani of Jhansi; died fighting at Gwalior on June 17, 1858.","रानी लक्ष्मीबाई किस केंद्र से जुड़ी थीं?",["कानपुर","झांसी","दिल्ली","बरेली"],"झांसी की रानी; 17 जून 1858 को ग्वालियर में लड़ते हुए शहीद।"),
Q("A",M,Y24,"INC founded in which year?",["1885","1890","1900","1882"],"Dec 28, 1885, Bombay. W.C. Bonnerjee first president, 72 delegates.","INC की स्थापना कब हुई?",["1885","1890","1900","1882"],"28 दिसंबर 1885, बॉम्बे। डब्ल्यू.सी. बनर्जी पहले अध्यक्ष, 72 प्रतिनिधि।"),
Q("D",H,Y23,"1929 Lahore INC session president?",["Gandhi","Motilal Nehru","Subhas Bose","Jawaharlal Nehru"],"Nehru presided; Purna Swaraj resolution passed. Jan 26, 1930 - first Independence Day.","1929 लाहौर INC अधिवेशन के अध्यक्ष?",["गांधी","मोतीलाल नेहरू","सुभाष बोस","जवाहरलाल नेहरू"],"नेहरू ने अध्यक्षता की; पूर्ण स्वराज प्रस्ताव। 26 जनवरी 1930 - पहला स्वतंत्रता दिवस।"),
Q("C",E,Y24,"'Do or Die' slogan by?",["Subhas Bose","Nehru","Mahatma Gandhi","Sardar Patel"],"Gandhi at Bombay AICC, Aug 8, 1942 launching Quit India Movement.","'करो या मरो' नारा किसने दिया?",["सुभाष बोस","नेहरू","महात्मा गांधी","सरदार पटेल"],"गांधी ने 8 अगस्त 1942, बॉम्बे AICC में भारत छोड़ो आंदोलन शुरू करते हुए।"),
Q("B",M,Y24,"Dandi March started on?",["March 12, 1931","March 12, 1930","April 6, 1930","April 12, 1930"],"March 12, 1930 from Sabarmati. Reached Dandi on April 6, broke salt law.","दांडी मार्च कब शुरू हुआ?",["12 मार्च 1931","12 मार्च 1930","6 अप्रैल 1930","12 अप्रैल 1930"],"12 मार्च 1930, साबरमती से। 6 अप्रैल को दांडी पहुँचकर नमक कानून तोड़ा।"),
Q("C",M,Y24,"Cabinet Mission (1946) had how many members?",["2","3","4","5"],"3 British ministers: Cripps, Pethick-Lawrence, A.V. Alexander.","कैबिनेट मिशन (1946) में कितने सदस्य?",["2","3","4","5"],"3 ब्रिटिश मंत्री: क्रिप्स, पेथिक-लॉरेंस, ए.वी. अलेक्जेंडर।"),
Q("B",E,Y24,"British PM at India's independence?",["Churchill","Clement Attlee","Chamberlain","Macmillan"],"Attlee (Labour Party); sent Cabinet Mission, appointed Mountbatten Viceroy.","स्वतंत्रता के समय ब्रिटिश PM?",["चर्चिल","क्लेमेंट एटली","चैंबरलेन","मैकमिलन"],"एटली (लेबर पार्टी); कैबिनेट मिशन भेजा, माउंटबेटन को वायसराय नियुक्त किया।"),
Q("C",M,Y24,"Radcliffe Line drawn by?",["Mountbatten","Stafford Cripps","Cyril Radcliffe","A.V. Alexander"],"Sir Cyril Radcliffe chaired Boundary Commission, drew partition line Aug 17, 1947.","रैडक्लिफ रेखा किसने खींची?",["माउंटबेटन","स्टैफोर्ड क्रिप्स","सिरिल रैडक्लिफ","ए.वी. अलेक्जेंडर"],"सर सिरिल रैडक्लिफ ने सीमा आयोग की अध्यक्षता कर 17 अगस्त 1947 को विभाजन रेखा खींची।"),
Q("D",M,Y24,"Iron Man of India?",["Gandhi","Nehru","Ambedkar","Sardar Vallabhbhai Patel"],"Patel integrated 560+ princely states into Indian Union.","भारत का लौह पुरुष?",["गांधी","नेहरू","अंबेडकर","सरदार वल्लभभाई पटेल"],"पटेल ने 560+ रियासतों को भारतीय संघ में मिलाया।"),
Q("B",M,Y24,"Buddha attained enlightenment at?",["Lumbini","Bodh Gaya","Sarnath","Kushinagar"],"Bodh Gaya under the Bodhi tree. Four events: Lumbini(birth), Bodh Gaya(enlightenment), Sarnath(sermon), Kushinagar(death).","बुद्ध को ज्ञान कहाँ प्राप्त हुआ?",["लुंबिनी","बोध गया","सारनाथ","कुशीनगर"],"बोध गया में बोधि वृक्ष के नीचे। चार घटनाएँ: लुंबिनी(जन्म), बोध गया(ज्ञान), सारनाथ(उपदेश), कुशीनगर(मृत्यु)।"),
Q("D",H,Y23,"First Buddhist Council held at?",["Vaishali","Pataliputra","Kashmir","Rajgriha"],"483 BCE at Rajgriha under Ajatashatru, presided by Mahakasyapa. Tripitaka compiled.","प्रथम बौद्ध संगीति कहाँ हुई?",["वैशाली","पाटलिपुत्र","कश्मीर","राजगृह"],"483 ई.पू. राजगृह में अजातशत्रु के तहत, महाकश्यप की अध्यक्षता। त्रिपिटक संकलित।"),
Q("C",E,Y24,"24th Jain Tirthankara?",["Rishabhanatha","Parshvanatha","Mahavira","Neminatha"],"Mahavira (Vardhamana), born ~540 BCE in Kundagrama near Vaishali.","24वें जैन तीर्थंकर?",["ऋषभनाथ","पार्श्वनाथ","महावीर","नेमिनाथ"],"महावीर (वर्धमान), जन्म लगभग 540 ई.पू. वैशाली के पास कुंडग्राम में।"),
Q("A",M,Y24,"Shunga dynasty founder?",["Pushyamitra Shunga","Agnimitra","Vasumitra","Devabhuti"],"Pushyamitra assassinated last Mauryan Brihadratha in 185 BCE.","शुंग वंश का संस्थापक?",["पुष्यमित्र शुंग","अग्निमित्र","वसुमित्र","देवभूति"],"पुष्यमित्र ने 185 ई.पू. में अंतिम मौर्य बृहद्रथ की हत्या की।"),
Q("D",H,Y24,"Mudrarakshasa written by?",["Kalidasa","Banabhatta","Bharavi","Vishakhadatta"],"Vishakhadatta: Sanskrit play on Chandragupta Maurya's rise with Chanakya.","मुद्राराक्षस किसने लिखा?",["कालिदास","बाणभट्ट","भारवि","विशाखदत्त"],"विशाखदत्त: चाणक्य की सहायता से चंद्रगुप्त मौर्य के उत्थान पर संस्कृत नाटक।"),
Q("C",E,Y24,"Simon Commission arrived in?",["1925","1927","1928","1930"],"1928; no Indian members; slogan 'Simon Go Back'.","साइमन कमीशन कब आया?",["1925","1927","1928","1930"],"1928; कोई भारतीय सदस्य नहीं; 'साइमन वापस जाओ' नारा।"),
Q("B",H,Y23,"'Dilli Chalo' call given by?",["Gandhi","Subhas Chandra Bose","Nehru","Bhagat Singh"],"Netaji Subhas Bose to INA soldiers.","'दिल्ली चलो' का आह्वान किसने दिया?",["गांधी","सुभाष चंद्र बोस","नेहरू","भगत सिंह"],"नेताजी सुभाष बोस ने INA सैनिकों को।"),
Q("A",E,Y24,"Viceroy during Partition?",["Lord Mountbatten","Lord Wavell","Lord Linlithgow","Lord Irwin"],"Last Viceroy (1947-48), oversaw partition and independence.","विभाजन के समय वायसराय?",["लॉर्ड माउंटबेटन","लॉर्ड वेवेल","लॉर्ड लिनलिथगो","लॉर्ड इरविन"],"अंतिम वायसराय (1947-48), विभाजन और स्वतंत्रता की देखरेख की।"),
Q("D",M,Y24,"Rowlatt Act passed in?",["1915","1917","1918","1919"],"1919: allowed imprisonment without trial. Gandhi launched Satyagraha.","रॉलेट एक्ट कब पारित हुआ?",["1915","1917","1918","1919"],"1919: बिना मुकदमे कारावास। गांधी ने सत्याग्रह शुरू किया।"),
Q("C",M,Y24,"Khilafat Movement launched in?",["1917","1918","1919","1920"],"1919; led by Ali brothers (Shaukat & Muhammad Ali), supported by Gandhi.","खिलाफत आंदोलन कब शुरू हुआ?",["1917","1918","1919","1920"],"1919; अली बंधुओं के नेतृत्व में, गांधी का समर्थन।"),
Q("B",E,Y24,"Jallianwala Bagh massacre date?",["April 13, 1918","April 13, 1919","April 13, 1920","April 13, 1921"],"April 13, 1919 (Baisakhi). General Dyer fired on unarmed crowd, Amritsar.","जलियांवाला बाग हत्याकांड की तारीख?",["13 अप्रैल 1918","13 अप्रैल 1919","13 अप्रैल 1920","13 अप्रैल 1921"],"13 अप्रैल 1919 (बैसाखी)। जनरल डायर ने अमृतसर में निहत्थी भीड़ पर गोली चलाई।")]
tot+=proc("indian-history.json",H)
print(f"  History: {len(H)} Qs added.\n")

# ====== 2. GEOGRAPHY (65 new Qs) ======
print("2. Geography")
G=[Q("A",E,Y24,"Longest river in India?",["Ganga","Yamuna","Godavari","Brahmaputra"],"Ganga: ~2,525 km from Gangotri Glacier to Bay of Bengal.","भारत की सबसे लंबी नदी?",["गंगा","यमुना","गोदावरी","ब्रह्मपुत्र"],"गंगा: गंगोत्री ग्लेशियर से बंगाल की खाड़ी तक ~2,525 किमी।"),
Q("C",M,Y24,"Hirakud Dam built on which river?",["Godavari","Krishna","Mahanadi","Narmada"],"Hirakud Dam on Mahanadi in Odisha, one of world's longest dams (25.8 km).","हीराकुंड बांध किस नदी पर है?",["गोदावरी","कृष्णा","महानदी","नर्मदा"],"ओडिशा में महानदी पर, दुनिया के सबसे लंबे बांधों में से एक (25.8 किमी)।"),
Q("B",E,Y24,"India's highest peak?",["Nanda Devi","Kanchenjunga","Mount Everest","K2"],"Kanchenjunga (8,586 m) on India-Nepal border in Sikkim is India's highest peak.","भारत की सबसे ऊंची चोटी?",["नंदा देवी","कंचनजंगा","माउंट एवरेस्ट","K2"],"कंचनजंगा (8,586 मी) सिक्किम में भारत-नेपाल सीमा पर, भारत की सबसे ऊंची चोटी।"),
Q("D",M,Y24,"Largest Indian state by area?",["Maharashtra","Madhya Pradesh","Uttar Pradesh","Rajasthan"],"Rajasthan: 342,239 sq km, largest by area.","भारत का सबसे बड़ा राज्य (क्षेत्रफल)?",["महाराष्ट्र","मध्य प्रदेश","उत्तर प्रदेश","राजस्थान"],"राजस्थान: 342,239 वर्ग किमी, क्षेत्रफल में सबसे बड़ा।"),
Q("A",M,Y24,"Khardung La pass located in?",["Ladakh","Himachal Pradesh","Uttarakhand","Sikkim"],"Khardung La (5,359 m) in Ladakh is one of world's highest motorable passes.","खारदुंग ला दर्रा कहाँ स्थित है?",["लद्दाख","हिमाचल प्रदेश","उत्तराखंड","सिक्किम"],"खारदुंग ला (5,359 मी) लद्दाख में, दुनिया के सबसे ऊंचे मोटर-योग्य दर्रों में से एक।"),
Q("C",H,Y23,"India's first national park?",["Gir","Corbett","Jim Corbett (Hailey) National Park","Kaziranga"],"Established 1936 as Hailey National Park, renamed Jim Corbett in 1957, Uttarakhand.","भारत का पहला राष्ट्रीय उद्यान?",["गिर","कॉर्बेट","जिम कॉर्बेट (हेली) राष्ट्रीय उद्यान","काजीरंगा"],"1936 में हेली राष्ट्रीय उद्यान के रूप में स्थापित, 1957 में जिम कॉर्बेट नाम, उत्तराखंड।"),
Q("B",M,Y24,"Sundarbans delta formed by which rivers?",["Godavari-Krishna","Ganga-Brahmaputra","Narmada-Tapti","Mahanadi-Godavari"],"Ganga-Brahmaputra form the world's largest delta, Sundarbans.","सुंदरवन डेल्टा किन नदियों से बना?",["गोदावरी-कृष्णा","गंगा-ब्रह्मपुत्र","नर्मदा-ताप्ती","महानदी-गोदावरी"],"गंगा-ब्रह्मपुत्र दुनिया का सबसे बड़ा डेल्टा सुंदरवन बनाती हैं।"),
Q("D",E,Y24,"Best soil for cotton cultivation?",["Alluvial soil","Red soil","Laterite soil","Black soil (Regur)"],"Black soil (Regur) in Deccan retains moisture, ideal for cotton.","कपास के लिए सर्वोत्तम मिट्टी?",["जलोढ़ मिट्टी","लाल मिट्टी","लैटेराइट मिट्टी","काली मिट्टी (रेगुर)"],"दक्कन की काली मिट्टी (रेगुर) नमी बनाए रखती है, कपास के लिए आदर्श।"),
Q("B",M,Y24,"Indian state with longest international border?",["Rajasthan","West Bengal","Arunachal Pradesh","Gujarat"],"West Bengal shares borders with Bangladesh, Nepal, and Bhutan.","सबसे लंबी अंतरराष्ट्रीय सीमा वाला राज्य?",["राजस्थान","पश्चिम बंगाल","अरुणाचल प्रदेश","गुजरात"],"पश्चिम बंगाल की सीमा बांग्लादेश, नेपाल और भूटान से लगती है।"),
Q("A",E,Y24,"Indian state with longest coastline?",["Gujarat","Maharashtra","Tamil Nadu","Kerala"],"Gujarat: ~1,600 km coastline, longest among Indian states.","सबसे लंबी तटरेखा वाला भारतीय राज्य?",["गुजरात","महाराष्ट्र","तमिलनाडु","केरल"],"गुजरात: ~1,600 किमी तटरेखा, भारतीय राज्यों में सबसे लंबी।"),
Q("C",H,Y24,"Largest mica producing state in India?",["Rajasthan","Bihar","Andhra Pradesh","Jharkhand"],"Andhra Pradesh is the largest mica producer. Jharkhand and Rajasthan also have deposits.","भारत में अभ्रक का सबसे बड़ा उत्पादक राज्य?",["राजस्थान","बिहार","आंध्र प्रदेश","झारखंड"],"आंध्र प्रदेश सबसे बड़ा अभ्रक उत्पादक। झारखंड और राजस्थान में भी भंडार।"),
Q("D",M,Y24,"Southwest monsoon arrives in Kerala around?",["May 15","May 25","June 5","June 1"],"Monsoon normally hits Kerala coast around June 1, covers India by mid-July.","दक्षिण-पश्चिम मानसून केरल में लगभग कब आता है?",["15 मई","25 मई","5 जून","1 जून"],"मानसून सामान्यतः 1 जून के आसपास केरल तट पर पहुंचता है, मध्य जुलाई तक भारत को कवर करता है।"),
Q("A",M,Y24,"First Indian state formed on linguistic basis?",["Andhra Pradesh (1953)","Kerala","Tamil Nadu","Karnataka"],"Andhra State in 1953 after Potti Sriramulu's fast-unto-death. Became Andhra Pradesh in 1956.","भाषाई आधार पर बना पहला भारतीय राज्य?",["आंध्र प्रदेश (1953)","केरल","तमिलनाडु","कर्नाटक"],"1953 में पोट्टी श्रीरामुलु के आमरण अनशन के बाद आंध्र राज्य। 1956 में आंध्र प्रदेश बना।"),
Q("B",M,Y24,"Damodar river is known as?",["Ganga of the South","Sorrow of Bengal","Sorrow of Bihar","Life line of Odisha"],"Damodar was called 'Sorrow of Bengal' due to devastating floods. Now controlled by DVC dams.","दामोदर नदी किस नाम से जानी जाती है?",["दक्षिण की गंगा","बंगाल का शोक","बिहार का शोक","ओडिशा की जीवन रेखा"],"दामोदर को विनाशकारी बाढ़ के कारण 'बंगाल का शोक' कहा जाता था। अब DVC बांधों से नियंत्रित।"),
Q("A",M,Y24,"Sambhar Lake, India's largest inland salt lake, is in?",["Rajasthan","Gujarat","Maharashtra","Haryana"],"Sambhar Lake in Rajasthan is India's largest inland salt lake, a major salt production center.","भारत की सबसे बड़ी अंतर्देशीय नमक झील सांभर कहाँ है?",["राजस्थान","गुजरात","महाराष्ट्र","हरियाणा"],"राजस्थान में सांभर झील भारत की सबसे बड़ी अंतर्देशीय नमक झील है, प्रमुख नमक उत्पादन केंद्र।"),
Q("C",H,Y23,"Which mountain pass connects Srinagar to Leh?",["Rohtang Pass","Nathu La","Zoji La","Shipki La"],"Zoji La (3,528 m) connects Srinagar (Kashmir Valley) to Leh (Ladakh) on NH-1.","श्रीनगर को लेह से जोड़ने वाला दर्रा?",["रोहतांग दर्रा","नाथू ला","ज़ोजी ला","शिपकी ला"],"ज़ोजी ला (3,528 मी) NH-1 पर श्रीनगर (कश्मीर घाटी) को लेह (लद्दाख) से जोड़ता है।"),
Q("D",M,Y24,"Which is the largest freshwater lake in India?",["Chilka Lake","Dal Lake","Sambhar Lake","Wular Lake"],"Wular Lake in Jammu & Kashmir is India's largest freshwater lake (~130 sq km).","भारत की सबसे बड़ी मीठे पानी की झील?",["चिल्का झील","डल झील","सांभर झील","वूलर झील"],"जम्मू-कश्मीर में वूलर झील (~130 वर्ग किमी) भारत की सबसे बड़ी मीठे पानी की झील है।"),
Q("B",E,Y24,"Which soil type covers the largest area in India?",["Black soil","Alluvial soil","Red soil","Laterite soil"],"Alluvial soil covers ~43% of India's land area, found in Indo-Gangetic plains.","भारत में सबसे बड़े क्षेत्र में कौन सी मिट्टी पाई जाती है?",["काली मिट्टी","जलोढ़ मिट्टी","लाल मिट्टी","लैटेराइट मिट्टी"],"जलोढ़ मिट्टी भारत के ~43% भूमि क्षेत्र में, भारत-गंगा के मैदानों में पाई जाती है।"),
Q("A",H,Y24,"Indian state with largest forest cover?",["Madhya Pradesh","Arunachal Pradesh","Chhattisgarh","Odisha"],"Madhya Pradesh has the largest forest cover by area in India.","सबसे बड़े वन क्षेत्र वाला भारतीय राज्य?",["मध्य प्रदेश","अरुणाचल प्रदेश","छत्तीसगढ़","ओडिशा"],"मध्य प्रदेश में भारत में क्षेत्रफल की दृष्टि से सबसे बड़ा वन क्षेत्र है।"),
Q("C",M,Y24,"India shares the longest border with which country?",["China","Pakistan","Bangladesh","Myanmar"],"India-Bangladesh border is ~4,096 km, the longest. India-China: ~3,488 km.","भारत की सबसे लंबी सीमा किस देश के साथ है?",["चीन","पाकिस्तान","बांग्लादेश","म्यांमार"],"भारत-बांग्लादेश सीमा ~4,096 किमी, सबसे लंबी। भारत-चीन: ~3,488 किमी।"),
Q("D",M,Y24,"Jog Falls, India's highest waterfall, is on which river?",["Kaveri","Krishna","Godavari","Sharavati"],"Jog Falls (253 m) on Sharavati River in Karnataka is India's highest plunge waterfall.","भारत का सबसे ऊंचा जलप्रपात जोग फॉल्स किस नदी पर है?",["कावेरी","कृष्णा","गोदावरी","शरावती"],"कर्नाटक में शरावती नदी पर जोग फॉल्स (253 मी) भारत का सबसे ऊंचा सीधा जलप्रपात है।"),
Q("B",H,Y24,"World's wettest place Mawsynram is in which Indian state?",["Sikkim","Meghalaya","Arunachal Pradesh","Assam"],"Mawsynram, Meghalaya receives the highest average annual rainfall on Earth (~11,871 mm).","दुनिया का सबसे नम स्थान मावसिनराम किस भारतीय राज्य में है?",["सिक्किम","मेघालय","अरुणाचल प्रदेश","असम"],"मेघालय का मावसिनराम पृथ्वी पर सबसे अधिक औसत वार्षिक वर्षा (~11,871 मिमी) प्राप्त करता है।"),
Q("C",E,Y24,"The Tropic of Cancer does NOT pass through which state?",["Gujarat","Madhya Pradesh","Odisha","West Bengal"],"Tropic of Cancer passes through 8 states: Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, WB, Tripura, Mizoram. Not Odisha.","कर्क रेखा किस राज्य से नहीं गुज़रती?",["गुजरात","मध्य प्रदेश","ओडिशा","पश्चिम बंगाल"],"कर्क रेखा 8 राज्यों से गुज़रती है: गुजरात, राजस्थान, MP, छत्तीसगढ़, झारखंड, WB, त्रिपुरा, मिज़ोरम। ओडिशा नहीं।"),
Q("B",M,Y24,"Brahmaputra river is known as ____ in Tibet?",["Dihang","Tsangpo","Jamuna","Padma"],"Brahmaputra is called Tsangpo in Tibet, Dihang in Arunachal, Jamuna in Bangladesh.","ब्रह्मपुत्र नदी तिब्बत में किस नाम से जानी जाती है?",["दिहांग","सांगपो","जमुना","पद्मा"],"ब्रह्मपुत्र तिब्बत में सांगपो, अरुणाचल में दिहांग, बांग्लादेश में जमुना कहलाती है।"),
Q("A",H,Y24,"Which river is called 'Dakshin Ganga' (Ganga of the South)?",["Godavari","Kaveri","Krishna","Mahanadi"],"Godavari, the second longest river in India (~1,465 km), is called Dakshin Ganga or Vriddha Ganga.","किस नदी को 'दक्षिण गंगा' कहा जाता है?",["गोदावरी","कावेरी","कृष्णा","महानदी"],"गोदावरी, भारत की दूसरी सबसे लंबी नदी (~1,465 किमी), दक्षिण गंगा या वृद्ध गंगा कहलाती है।"),
Q("D",M,Y24,"Kaziranga National Park is famous for?",["Lions","Elephants","Snow leopards","One-horned rhinoceros"],"Kaziranga (Assam) has the world's largest population of Indian one-horned rhinoceros.","काजीरंगा राष्ट्रीय उद्यान किसके लिए प्रसिद्ध है?",["शेर","हाथी","हिम तेंदुआ","एक सींग वाला गैंडा"],"काजीरंगा (असम) में भारतीय एक सींग वाले गैंडे की दुनिया की सबसे बड़ी आबादी है।"),
Q("C",E,Y24,"Dudhsagar Falls is located in which state?",["Karnataka","Kerala","Goa","Maharashtra"],"Dudhsagar Falls (310 m) on Mandovi River, on Goa-Karnataka border, one of India's tallest.","दूधसागर जलप्रपात किस राज्य में स्थित है?",["कर्नाटक","केरल","गोवा","महाराष्ट्र"],"दूधसागर जलप्रपात (310 मी) मांडवी नदी पर, गोवा-कर्नाटक सीमा पर, भारत के सबसे ऊंचे जलप्रपातों में से एक।"),
Q("A",M,Y24,"Which Indian state is the largest producer of wheat?",["Uttar Pradesh","Punjab","Haryana","Madhya Pradesh"],"Uttar Pradesh is India's largest wheat producer, followed by Punjab and MP.","भारत में गेहूं का सबसे बड़ा उत्पादक राज्य?",["उत्तर प्रदेश","पंजाब","हरियाणा","मध्य प्रदेश"],"उत्तर प्रदेश भारत का सबसे बड़ा गेहूं उत्पादक है, उसके बाद पंजाब और MP।"),
Q("B",H,Y24,"Which Indian state has the highest population density?",["West Bengal","Bihar","Kerala","Uttar Pradesh"],"Bihar has the highest population density among Indian states (~1,106 persons/sq km).","सबसे अधिक जनसंख्या घनत्व वाला भारतीय राज्य?",["पश्चिम बंगाल","बिहार","केरल","उत्तर प्रदेश"],"बिहार में भारतीय राज्यों में सबसे अधिक जनसंख्या घनत्व (~1,106 व्यक्ति/वर्ग किमी) है।"),
Q("C",M,Y24,"Mullaperiyar Dam is located in which state?",["Tamil Nadu","Karnataka","Kerala","Andhra Pradesh"],"Mullaperiyar Dam is in Kerala on Periyar River, operated by Tamil Nadu under a 1886 lease agreement.","मुल्लापेरियार बांध किस राज्य में स्थित है?",["तमिलनाडु","कर्नाटक","केरल","आंध्र प्रदेश"],"मुल्लापेरियार बांध केरल में पेरियार नदी पर है, 1886 पट्टा समझौते के तहत तमिलनाडु द्वारा संचालित।"),
Q("D",E,Y24,"Thar Desert extends primarily across which Indian state?",["Gujarat","Punjab","Haryana","Rajasthan"],"Thar Desert (Great Indian Desert) covers ~60% of Rajasthan, also extends into Gujarat, Punjab, Haryana.","थार रेगिस्तान मुख्यतः किस भारतीय राज्य में फैला है?",["गुजरात","पंजाब","हरियाणा","राजस्थान"],"थार रेगिस्तान (महान भारतीय रेगिस्तान) राजस्थान के ~60% भाग में फैला है, साथ ही गुजरात, पंजाब, हरियाणा तक।"),
Q("A",H,Y23,"Which river flows through a rift valley?",["Narmada","Ganga","Godavari","Mahanadi"],"Narmada and Tapti flow westward through rift valleys between Vindhya and Satpura ranges.","कौन सी नदी दरार घाटी से होकर बहती है?",["नर्मदा","गंगा","गोदावरी","महानदी"],"नर्मदा और ताप्ती विंध्य और सतपुड़ा पर्वतमालाओं के बीच दरार घाटियों से होकर पश्चिम की ओर बहती हैं।"),
Q("B",M,Y24,"The Andaman and Nicobar Islands are separated by which channel?",["Palk Strait","Ten Degree Channel","Nine Degree Channel","Duncan Passage"],"Ten Degree Channel separates Andaman Islands from Nicobar Islands (10°N latitude).","अंडमान और निकोबार द्वीप समूह किस चैनल से अलग होते हैं?",["पाक जलडमरूमध्य","दस डिग्री चैनल","नौ डिग्री चैनल","डंकन मार्ग"],"दस डिग्री चैनल (10°N अक्षांश) अंडमान द्वीपों को निकोबार द्वीपों से अलग करता है।"),
Q("C",E,Y24,"India's largest nuclear power plant is?",["Narora","Tarapur","Kudankulam","Kaiga"],"Kudankulam in Tamil Nadu is India's largest nuclear power plant (with Russian collaboration).","भारत का सबसे बड़ा परमाणु ऊर्जा संयंत्र?",["नरोरा","तारापुर","कुडनकुलम","कैगा"],"तमिलनाडु में कुडनकुलम भारत का सबसे बड़ा परमाणु ऊर्जा संयंत्र है (रूसी सहयोग से)।"),
Q("B",M,Y24,"Bhakra Nangal Dam is built on which river?",["Yamuna","Sutlej","Beas","Ravi"],"Bhakra Nangal Dam on Sutlej River in Himachal Pradesh is one of India's highest gravity dams.","भाखड़ा नांगल बांध किस नदी पर बना है?",["यमुना","सतलुज","व्यास","रावी"],"हिमाचल प्रदेश में सतलुज नदी पर भाखड़ा नांगल बांध भारत के सबसे ऊंचे गुरुत्व बांधों में से एक है।"),
Q("D",H,Y24,"Which Indian state is the largest producer of coffee?",["Tamil Nadu","Kerala","Andhra Pradesh","Karnataka"],"Karnataka produces ~70% of India's coffee, mainly in Chikmagalur, Coorg, Hassan regions.","भारत में कॉफी का सबसे बड़ा उत्पादक राज्य?",["तमिलनाडु","केरल","आंध्र प्रदेश","कर्नाटक"],"कर्नाटक भारत की ~70% कॉफी का उत्पादन करता है, मुख्यतः चिकमगलूर, कूर्ग, हसन में।"),
Q("A",M,Y24,"Which Indian state has the highest literacy rate?",["Kerala","Delhi","Goa","Himachal Pradesh"],"Kerala has the highest literacy rate in India at ~96.2% (as per latest census/NSS data).","सबसे अधिक साक्षरता दर वाला भारतीय राज्य?",["केरल","दिल्ली","गोवा","हिमाचल प्रदेश"],"केरल में भारत में सबसे अधिक साक्षरता दर ~96.2% है।"),
Q("C",H,Y23,"Duncan Passage separates which islands?",["Andaman from Nicobar","North from South Andaman","South Andaman from Little Andaman","Great Nicobar from Sumatra"],"Duncan Passage separates South Andaman from Little Andaman.","डंकन मार्ग किन द्वीपों को अलग करता है?",["अंडमान से निकोबार","उत्तर से दक्षिण अंडमान","दक्षिण अंडमान से लिटिल अंडमान","ग्रेट निकोबार से सुमात्रा"],"डंकन मार्ग दक्षिण अंडमान को लिटिल अंडमान से अलग करता है।"),
Q("B",M,Y24,"The Nagarjuna Sagar Dam is built on which river?",["Godavari","Krishna","Mahanadi","Penna"],"Nagarjuna Sagar Dam on Krishna River, between Telangana and Andhra Pradesh, is one of India's largest masonry dams.","नागार्जुन सागर बांध किस नदी पर बना है?",["गोदावरी","कृष्णा","महानदी","पेन्ना"],"तेलंगाना और आंध्र प्रदेश के बीच कृष्णा नदी पर नागार्जुन सागर बांध भारत के सबसे बड़े चिनाई बांधों में से एक है।"),
Q("A",M,Y24,"Sundarbans is famous for which animal?",["Royal Bengal Tiger","Asiatic Lion","One-horned Rhino","Wild Buffalo"],"Sundarbans is the world's largest mangrove forest and home to the Royal Bengal Tiger.","सुंदरवन किस जानवर के लिए प्रसिद्ध है?",["रॉयल बंगाल टाइगर","एशियाई शेर","एक सींग वाला गैंडा","जंगली भैंसा"],"सुंदरवन दुनिया का सबसे बड़ा मैंग्रोव वन है और रॉयल बंगाल टाइगर का आवास है।"),
Q("C",H,Y24,"Which states are involved in the Cauvery water dispute?",["Kerala-Tamil Nadu","Andhra-Karnataka","Karnataka-Tamil Nadu","Maharashtra-Karnataka"],"The Cauvery water dispute primarily involves Karnataka (upstream) and Tamil Nadu (downstream), also Kerala and Puducherry.","कावेरी जल विवाद में कौन से राज्य शामिल हैं?",["केरल-तमिलनाडु","आंध्र-कर्नाटक","कर्नाटक-तमिलनाडु","महाराष्ट्र-कर्नाटक"],"कावेरी जल विवाद में मुख्यतः कर्नाटक (ऊपरी) और तमिलनाडु (निचला), साथ ही केरल और पुदुचेरी शामिल हैं।"),
Q("D",E,Y24,"India's standard time meridian passes through which city?",["Delhi","Mumbai","Kolkata","Mirzapur (Allahabad)"],"IST meridian 82.5°E passes through Mirzapur near Allahabad (Prayagraj), Uttar Pradesh.","भारत का मानक समय मध्याह्न रेखा किस शहर से गुज़रती है?",["दिल्ली","मुंबई","कोलकाता","मिर्ज़ापुर (इलाहाबाद)"],"IST मध्याह्न रेखा 82.5°E उत्तर प्रदेश में इलाहाबाद (प्रयागराज) के पास मिर्ज़ापुर से गुज़रती है।"),
Q("B",M,Y24,"Garo, Khasi, and Jaintia hills are in which state?",["Arunachal Pradesh","Meghalaya","Nagaland","Mizoram"],"These three hill ranges are in Meghalaya, part of the Peninsular plateau's northeastern extension.","गारो, खासी और जयंतिया पहाड़ियाँ किस राज्य में हैं?",["अरुणाचल प्रदेश","मेघालय","नागालैंड","मिज़ोरम"],"ये तीनों पर्वत श्रृंखलाएं मेघालय में हैं, जो प्रायद्वीपीय पठार का पूर्वोत्तर विस्तार हैं।"),
Q("A",M,Y24,"Chilika Lake, India's largest brackish water lagoon, is in?",["Odisha","West Bengal","Andhra Pradesh","Tamil Nadu"],"Chilika Lake in Odisha is India's largest coastal lagoon and a Ramsar wetland site.","भारत की सबसे बड़ी खारे पानी की लैगून चिल्का झील कहाँ है?",["ओडिशा","पश्चिम बंगाल","आंध्र प्रदेश","तमिलनाडु"],"ओडिशा में चिल्का झील भारत की सबसे बड़ी तटीय लैगून और रामसर आर्द्रभूमि स्थल है।"),
Q("C",H,Y24,"India's highest dam, Tehri Dam, is on which river?",["Yamuna","Alaknanda","Bhagirathi","Mandakini"],"Tehri Dam (260.5 m) on Bhagirathi River in Uttarakhand is India's highest dam.","भारत का सबसे ऊंचा बांध टिहरी बांध किस नदी पर है?",["यमुना","अलकनंदा","भागीरथी","मंदाकिनी"],"उत्तराखंड में भागीरथी नदी पर टिहरी बांध (260.5 मी) भारत का सबसे ऊंचा बांध है।"),
Q("D",M,Y24,"Which country does NOT share a land border with India?",["Bhutan","Myanmar","Nepal","Sri Lanka"],"Sri Lanka is separated from India by the Palk Strait and Gulf of Mannar (no land border).","किस देश की भारत के साथ स्थलीय सीमा नहीं है?",["भूटान","म्यांमार","नेपाल","श्रीलंका"],"श्रीलंका भारत से पाक जलडमरूमध्य और मन्नार की खाड़ी द्वारा अलग है (कोई स्थलीय सीमा नहीं)।"),
Q("A",H,Y23,"Rann of Kutch is famous for which type of ecosystem?",["Salt marsh","Mangrove forest","Tropical rainforest","Coral reef"],"Rann of Kutch (Gujarat) is a vast salt marsh, seasonally submerged, known for the Rann Utsav and wild ass sanctuary.","कच्छ का रण किस प्रकार के पारिस्थितिकी तंत्र के लिए प्रसिद्ध है?",["नमक दलदल","मैंग्रोव वन","उष्णकटिबंधीय वर्षावन","प्रवाल भित्ति"],"कच्छ का रण (गुजरात) एक विशाल नमक दलदल है, मौसमी रूप से जलमग्न, रण उत्सव और जंगली गधा अभयारण्य के लिए जाना जाता है।"),
Q("B",E,Y24,"India's southernmost point is?",["Kanyakumari","Indira Point","Rameswaram","Thiruvananthapuram"],"Indira Point (Great Nicobar Island) at 6°45'N is India's southernmost point. Kanyakumari is mainland's southernmost tip.","भारत का सबसे दक्षिणी बिंदु?",["कन्याकुमारी","इंदिरा प्वाइंट","रामेश्वरम","तिरुवनंतपुरम"],"इंदिरा प्वाइंट (ग्रेट निकोबार द्वीप) 6°45'N पर भारत का सबसे दक्षिणी बिंदु। कन्याकुमारी मुख्य भूमि का सबसे दक्षिणी छोर।"),
Q("C",M,Y24,"Which river is called the 'Lifeline of Gujarat'?",["Mahi","Tapti","Narmada","Sabarmati"],"Narmada is the lifeline of Gujarat, providing irrigation through Sardar Sarovar Dam.","किस नदी को 'गुजरात की जीवन रेखा' कहा जाता है?",["माही","ताप्ती","नर्मदा","साबरमती"],"नर्मदा गुजरात की जीवन रेखा है, सरदार सरोवर बांध से सिंचाई प्रदान करती है।"),
Q("D",M,Y24,"Palghat Gap connects which two states?",["Karnataka-Goa","Maharashtra-Gujarat","Andhra-Tamilnadu","Kerala-Tamil Nadu"],"Palghat (Palakkad) Gap in Western Ghats connects Kerala and Tamil Nadu.","पालघाट दर्रा किन दो राज्यों को जोड़ता है?",["कर्नाटक-गोवा","महाराष्ट्र-गुजरात","आंध्र-तमिलनाडु","केरल-तमिलनाडु"],"पश्चिमी घाट में पालघाट (पलक्कड़) दर्रा केरल और तमिलनाडु को जोड़ता है।"),
Q("A",H,Y24,"Loktak Lake, famous for phumdis (floating islands), is in?",["Manipur","Assam","Tripura","Mizoram"],"Loktak Lake in Manipur is Northeast's largest freshwater lake, known for floating phumdis and Keibul Lamjao National Park.","फुमदी (तैरते द्वीप) के लिए प्रसिद्ध लोकताक झील कहाँ है?",["मणिपुर","असम","त्रिपुरा","मिज़ोरम"],"मणिपुर में लोकताक झील पूर्वोत्तर की सबसे बड़ी मीठे पानी की झील है, तैरती फुमदी और कैबुल लामजाओ राष्ट्रीय उद्यान के लिए प्रसिद्ध।"),
Q("B",M,Y24,"India's largest river island Majuli is on which river?",["Ganga","Brahmaputra","Godavari","Mahanadi"],"Majuli Island on Brahmaputra in Assam is the world's largest river island.","भारत का सबसे बड़ा नदी द्वीप माजुली किस नदी पर है?",["गंगा","ब्रह्मपुत्र","गोदावरी","महानदी"],"असम में ब्रह्मपुत्र पर माजुली द्वीप दुनिया का सबसे बड़ा नदी द्वीप है।")]
tot+=proc("geography.json",G)
print(f"  Geography: {len(G)} Qs added.\n")
