#!/usr/bin/env python3
"""Complete question bank expander - all 15 files. Run this script to generate all expanded JSONs."""
import json, os

BASE = r"C:\Users\core\rrb-exam-prep\public\data\questions\ntpc\general-awareness"
E,M,H = "easy","medium","hard"
Y24,Y23,Y25 = 2024,2023,2025

def Q(c,d,y,eq,eo,ex,hq,ho,hx):
    return {"correctOption":c,"difficulty":d,"sourceYear":y,
            "en":{"question":eq,"options":eo,"explanation":ex},
            "hi":{"question":hq,"options":ho,"explanation":hx}}

def expand(path, qs):
    with open(path,'r',encoding='utf-8') as f: data = json.load(f)
    s = int(data[-1]['id'].split('-')[-1]) if data else 0
    for i,q in enumerate(qs): q['id'] = f"ntpc-ga-{s+i+1:04d}"
    data.extend(qs)
    with open(path,'w',encoding='utf-8') as f: json.dump(data,f,ensure_ascii=False,indent=2)
    print(f"  {os.path.basename(path)}: +{len(qs)} => {len(data)} total")
    return len(qs)

tot = 0

# ============================================================
# 1. INDIAN HISTORY (65 new questions)
# ============================================================
print("\n--- Indian History ---")
H1 = []
H1 += [Q("C",E,Y24,"Largest Indus Valley site?",["Mohenjo-daro","Harappa","Rakhigarhi","Dholavira"],"Rakhigarhi in Haryana over 350 hectares, now considered the largest IVC site.","सबसे बड़ा सिंधु घाटी स्थल?",["मोहनजोदड़ो","हड़प्पा","राखीगढ़ी","धोलावीरा"],"हरियाणा में राखीगढ़ी 350 हेक्टेयर से अधिक, अब सबसे बड़ा सिंधु घाटी स्थल माना जाता है।")]
H1 += [Q("B",M,Y24,"Great Bath found at which Indus site?",["Harappa","Mohenjo-daro","Lothal","Kalibangan"],"Great Bath at Mohenjo-daro is a large rectangular water tank, believed used for ritual bathing.","महान स्नानागार किस सिंधु स्थल पर मिला?",["हड़प्पा","मोहनजोदड़ो","लोथल","कालीबंगा"],"मोहनजोदड़ो का महान स्नानागार एक बड़ा आयताकार जल कुंड है, माना जाता है अनुष्ठान स्नान के लिए उपयोग होता था।")]
H1 += [Q("D",M,Y24,"Which Indus site had a dockyard?",["Mohenjo-daro","Harappa","Kalibangan","Lothal"],"Lothal in Gujarat had a remarkable dockyard connected to Sabarmati River, showing maritime trade.","किस सिंधु स्थल पर बंदरगाह था?",["मोहनजोदड़ो","हड़प्पा","कालीबंगा","लोथल"],"गुजरात में लोथल में साबरमती नदी से जुड़ा उल्लेखनीय बंदरगाह समुद्री व्यापार दर्शाता है।")]
H1 += [Q("A",E,Y24,"Indus people worshipped which deity form?",["Pashupati (Proto-Shiva)","Vishnu","Brahma","Indra"],"The Pashupati seal shows a seated figure surrounded by animals, considered a proto-Shiva representation.","सिंधु लोग किस देवता रूप की पूजा करते थे?",["पशुपति (आदि-शिव)","विष्णु","ब्रह्मा","इंद्र"],"पशुपति मुहर में पशुओं से घिरी बैठी आकृति है, जिसे आदि-शिव माना जाता है।")]
H1 += [Q("B",M,Y24,"Which metal was unknown to Indus Valley people?",["Copper","Iron","Bronze","Gold"],"Iron was unknown to Indus people. They used copper, bronze, gold, silver, and lead but had no knowledge of iron metallurgy.","सिंधु घाटी के लोग किस धातु से अनजान थे?",["तांबा","लोहा","कांसा","सोना"],"सिंधु लोग लोहे से अनजान थे। वे तांबा, कांसा, सोना, चांदी और सीसा का उपयोग करते थे किंतु लौह धातुकर्म का ज्ञान नहीं था।")]
H1 += [Q("A",E,Y24,"Oldest Veda is?",["Rigveda","Samaveda","Yajurveda","Atharvaveda"],"Rigveda (c.1500-1200 BCE) is the oldest Veda, containing 1,028 hymns divided into 10 mandalas.","सबसे पुराना वेद कौन सा है?",["ऋग्वेद","सामवेद","यजुर्वेद","अथर्ववेद"],"ऋग्वेद (लगभग 1500-1200 ई.पू.) सबसे पुराना वेद है, जिसमें 10 मंडलों में 1,028 सूक्त हैं।")]
H1 += [Q("C",M,Y24,"Gayatri Mantra is found in which Veda?",["Samaveda","Yajurveda","Rigveda","Atharvaveda"],"Gayatri Mantra is in Rigveda Mandala 3, Hymn 62, Verse 10, dedicated to solar deity Savitr.","गायत्री मंत्र किस वेद में पाया जाता है?",["सामवेद","यजुर्वेद","ऋग्वेद","अथर्ववेद"],"गायत्री मंत्र ऋग्वेद मंडल 3, सूक्त 62, श्लोक 10 में है, जो सौर देवता सविता को समर्पित है।")]
H1 += [Q("B",E,Y24,"Which Rishi composed the Gayatri Mantra?",["Vasishta","Vishwamitra","Atri","Agastya"],"Rishi Vishwamitra composed several Rigvedic hymns including the celebrated Gayatri Mantra.","गायत्री मंत्र की रचना किस ऋषि ने की?",["वसिष्ठ","विश्वामित्र","अत्रि","अगस्त्य"],"ऋषि विश्वामित्र ने गायत्री मंत्र सहित कई ऋग्वैदिक सूक्तों की रचना की।")]
H1 += [Q("D",H,Y23,"Battle of the Ten Kings fought on which river?",["Ganga","Yamuna","Saraswati","Ravi (Parushni)"],"King Sudas (Bharata tribe) vs confederacy of ten tribes on Ravi river banks. Sudas won.","दस राजाओं का युद्ध (दाशराज्ञ) किस नदी पर हुआ?",["गंगा","यमुना","सरस्वती","रावी (परुष्णी)"],"राजा सुदास (भरत जनजाति) और दस जनजातियों के संघ के बीच रावी नदी के तट पर। सुदास विजयी रहे।")]
H1 += [Q("B",M,Y24,"Samaveda is primarily known as?",["Book of Hymns","Book of Chants","Book of Sacrifices","Book of Spells"],"Samaveda contains melodies and chants, setting Rigvedic hymns to music for sacrificial rituals.","सामवेद मुख्य रूप से किस नाम से जाना जाता है?",["सूक्तों की पुस्तक","गानों की पुस्तक","यज्ञों की पुस्तक","मंत्रों की पुस्तक"],"सामवेद में यज्ञ अनुष्ठानों के लिए ऋग्वैदिक सूक्तों को संगीतबद्ध करने वाले गान और मंत्र हैं।")]
H1 += [Q("C",M,Y24,"How many Mahajanapadas existed in 6th century BCE?",["12","14","16","18"],"16 Mahajanapadas according to Buddhist text Anguttara Nikaya. Magadha emerged as the most powerful.","छठी शताब्दी ई.पू. में कितने महाजनपद थे?",["12","14","16","18"],"बौद्ध ग्रंथ अंगुत्तर निकाय के अनुसार 16 महाजनपद थे। मगध सबसे शक्तिशाली बनकर उभरा।")]
H1 += [Q("B",E,Y24,"Chandragupta Maurya was succeeded by?",["Ashoka","Bindusara","Samprati","Dasharatha"],"Bindusara ruled from about 297-273 BCE and was known as Amitraghata (slayer of enemies).","चंद्रगुप्त मौर्य का उत्तराधिकारी कौन था?",["अशोक","बिंदुसार","संप्रति","दशरथ"],"बिंदुसार ने लगभग 297-273 ई.पू. तक शासन किया और अमित्रघात (शत्रुओं का विनाशक) कहलाए।")]
H1 += [Q("C",M,Y24,"Kalinga War was fought in which year?",["273 BCE","269 BCE","261 BCE","250 BCE"],"The Kalinga War (261 BCE) was a turning point; its horrors led Ashoka to embrace Buddhism.","कलिंग युद्ध किस वर्ष लड़ा गया?",["273 ई.पू.","269 ई.पू.","261 ई.पू.","250 ई.पू."],"कलिंग युद्ध (261 ई.पू.) एक निर्णायक मोड़ था; इसकी भयावहता ने अशोक को बौद्ध धर्म अपनाने के लिए प्रेरित किया।")]
H1 += [Q("D",M,Y24,"Megasthenes was ambassador to which Mauryan court?",["Ashoka","Bindusara","Samprati","Chandragupta Maurya"],"Megasthenes, a Greek envoy sent by Seleucus Nicator, wrote 'Indica' describing Mauryan India.","मेगस्थनीज़ किस मौर्य शासक के दरबार में राजदूत था?",["अशोक","बिंदुसार","संप्रति","चंद्रगुप्त मौर्य"],"सेल्यूकस निकेटर द्वारा भेजे गए यूनानी राजदूत मेगस्थनीज़ ने मौर्य भारत का वर्णन करती 'इंडिका' लिखी।")]
H1 += [Q("A",M,Y24,"Who was the last Mauryan ruler?",["Brihadratha","Ashoka","Dasharatha","Samprati"],"Brihadratha was assassinated by his commander Pushyamitra Shunga in 185 BCE, ending Mauryan rule.","अंतिम मौर्य शासक कौन था?",["बृहद्रथ","अशोक","दशरथ","संप्रति"],"बृहद्रथ की 185 ई.पू. में उसके सेनापति पुष्यमित्र शुंग ने हत्या कर दी, जिससे मौर्य शासन समाप्त हो गया।")]
H1 += [Q("B",H,Y24,"Arthashastra was authored by?",["Megasthenes","Kautilya (Chanakya)","Kalidasa","Panini"],"Kautilya also known as Chanakya or Vishnugupta wrote Arthashastra, a comprehensive treatise on statecraft, economics, and military strategy.","अर्थशास्त्र की रचना किसने की?",["मेगस्थनीज़","कौटिल्य (चाणक्य)","कालिदास","पाणिनि"],"कौटिल्य, जिन्हें चाणक्य या विष्णुगुप्त भी कहा जाता है, ने राजकाज, अर्थशास्त्र और सैन्य रणनीति पर व्यापक ग्रंथ अर्थशास्त्र लिखा।")]
H1 += [Q("C",E,Y24,"Who is known as the Napoleon of India?",["Chandragupta Maurya","Ashoka","Samudragupta","Harshavardhana"],"Samudragupta earned this title due to his extensive military conquests documented in the Allahabad Pillar inscription.","भारत का नेपोलियन किसे कहा जाता है?",["चंद्रगुप्त मौर्य","अशोक","समुद्रगुप्त","हर्षवर्धन"],"समुद्रगुप्त को इलाहाबाद स्तंभ शिलालेख में वर्णित उनके व्यापक सैन्य अभियानों के कारण यह उपाधि मिली।")]
H1 += [Q("B",M,Y24,"Iron Pillar at Mehrauli is associated with?",["Samudragupta","Chandragupta II Vikramaditya","Kumaragupta I","Skandagupta"],"The rust-resistant Iron Pillar bears an inscription of Chandragupta II Vikramaditya, showcasing advanced Gupta metallurgy.","महरौली का लौह स्तंभ किस गुप्त शासक से जुड़ा है?",["समुद्रगुप्त","चंद्रगुप्त द्वितीय विक्रमादित्य","कुमारगुप्त प्रथम","स्कंदगुप्त"],"जंग-रोधी लौह स्तंभ पर चंद्रगुप्त द्वितीय विक्रमादित्य का शिलालेख है, जो उन्नत गुप्त धातुकर्म को दर्शाता है।")]
H1 += [Q("D",H,Y24,"Chinese pilgrim Fa-Hien visited India during whose reign?",["Samudragupta","Kumaragupta","Skandagupta","Chandragupta II"],"Fa-Hien visited India around 399-414 CE during Chandragupta II's reign and described the prosperity and peaceful nature of Gupta rule.","चीनी यात्री फाहियान किसके शासनकाल में भारत आए?",["समुद्रगुप्त","कुमारगुप्त","स्कंदगुप्त","चंद्रगुप्त द्वितीय"],"फाहियान चंद्रगुप्त द्वितीय के शासनकाल में लगभग 399-414 ई. में भारत आए और गुप्त शासन की समृद्धि व शांतिपूर्ण प्रकृति का वर्णन किया।")]
H1 += [Q("A",M,Y24,"Which Gupta ruler assumed the title Maharajadhiraja?",["Chandragupta I","Samudragupta","Chandragupta II","Skandagupta"],"Chandragupta I assumed this title and is credited with starting the Gupta Era in 319-320 CE.","किस गुप्त शासक ने महाराजाधिराज की उपाधि धारण की?",["चंद्रगुप्त प्रथम","समुद्रगुप्त","चंद्रगुप्त द्वितीय","स्कंदगुप्त"],"चंद्रगुप्त प्रथम ने यह उपाधि धारण की और 319-320 ई. में गुप्त संवत शुरू करने का श्रेय इन्हें दिया जाता है।")]
H1 += [Q("C",H,Y23,"The Navratnas adorned which Gupta emperor's court?",["Samudragupta","Kumaragupta","Chandragupta II Vikramaditya","Skandagupta"],"Chandragupta II's court was graced by the Navratnas including Kalidasa, Varahamihira, Amarasimha, and Dhanvantari.","नवरत्न किस गुप्त सम्राट के दरबार की शोभा थे?",["समुद्रगुप्त","कुमारगुप्त","चंद्रगुप्त द्वितीय विक्रमादित्य","स्कंदगुप्त"],"चंद्रगुप्त द्वितीय के दरबार में कालिदास, वराहमिहिर, अमरसिंह और धन्वंतरि सहित नवरत्न थे।")]
H1 += [Q("B",E,Y24,"Kalidasa lived during which historical period?",["Mauryan","Gupta","Kushan","Harsha"],"The great Sanskrit poet and dramatist Kalidasa flourished during the Gupta period, composing works like Abhijnanashakuntalam and Meghaduta.","कालिदास किस ऐतिहासिक काल के कवि थे?",["मौर्य","गुप्त","कुषाण","हर्ष"],"महान संस्कृत कवि और नाटककार कालिदास गुप्त काल में रचनाकार थे, जिन्होंने अभिज्ञानशाकुंतलम और मेघदूत जैसी रचनाएं कीं।")]
H1 += [Q("C",M,Y24,"Harshavardhana established his capital at?",["Pataliputra","Ujjain","Kannauj","Taxila"],"Harshavardhana of the Pushyabhuti dynasty made Kannauj his capital. His reign is documented by Banabhatta and Hiuen Tsang.","हर्षवर्धन ने अपनी राजधानी कहां स्थापित की?",["पाटलिपुत्र","उज्जैन","कन्नौज","तक्षशिला"],"पुष्यभूति राजवंश के हर्षवर्धन ने कन्नौज को अपनी राजधानी बनाया। उनके शासन का वर्णन बाणभट्ट और ह्वेनसांग ने किया।")]
H1 += [Q("D",H,Y24,"Hiuen Tsang visited India during whose reign?",["Ashoka","Chandragupta II","Samudragupta","Harshavardhana"],"The Chinese pilgrim Hiuen Tsang (Xuanzang) visited India from 630-644 CE during Harsha's reign and studied at Nalanda University.","ह्वेनसांग किसके शासनकाल में भारत आए?",["अशोक","चंद्रगुप्त द्वितीय","समुद्रगुप्त","हर्षवर्धन"],"चीनी यात्री ह्वेनसांग (जुआनज़ांग) 630-644 ई. के दौरान हर्ष के शासनकाल में भारत आए और नालंदा विश्वविद्यालय में अध्ययन किया।")]
H1 += [Q("B",H,Y23,"Harsha was defeated by which Chalukya ruler?",["Vikramaditya I","Pulakeshin II","Kirtivarman I","Mangalesha"],"Pulakeshin II of the Chalukya dynasty defeated Harshavardhana on the banks of the Narmada River around 618 CE.","हर्ष किस चालुक्य शासक से पराजित हुए?",["विक्रमादित्य प्रथम","पुलकेशिन द्वितीय","कीर्तिवर्मन प्रथम","मंगलेश"],"चालुक्य वंश के पुलकेशिन द्वितीय ने लगभग 618 ई. में नर्मदा नदी के तट पर हर्षवर्धन को पराजित किया।")]
H1 += [Q("A",E,Y24,"Who founded the Delhi Sultanate?",["Qutb-ud-din Aibak","Iltutmish","Alauddin Khilji","Balban"],"Qutb-ud-din Aibak, a slave general of Muhammad Ghori, founded the Slave (Mamluk) dynasty in 1206 CE, marking the beginning of the Delhi Sultanate.","दिल्ली सल्तनत की स्थापना किसने की?",["कुतुब-उद-दीन ऐबक","इल्तुतमिश","अलाउद्दीन खिलजी","बलबन"],"मुहम्मद गौरी के गुलाम सेनापति कुतुब-उद-दीन ऐबक ने 1206 ई. में गुलाम (ममलूक) राजवंश की स्थापना की, जो दिल्ली सल्तनत की शुरुआत थी।")]
H1 += [Q("B",M,Y24,"Who introduced token currency in the Delhi Sultanate?",["Alauddin Khilji","Muhammad bin Tughlaq","Firoz Shah Tughlaq","Iltutmish"],"Muhammad bin Tughlaq introduced brass and copper token coins to replace silver in 1330. The experiment failed due to widespread forgery.","दिल्ली सल्तनत में सांकेतिक मुद्रा किसने शुरू की?",["अलाउद्दीन खिलजी","मुहम्मद बिन तुगलक","फिरोज शाह तुगलक","इल्तुतमिश"],"मुहम्मद बिन तुगलक ने 1330 में चांदी के स्थान पर पीतल और तांबे के सांकेतिक सिक्के शुरू किए। व्यापक जालसाजी के कारण प्रयोग विफल रहा।")]
H1 += [Q("C",H,Y23,"Market control and price regulation policy was by?",["Iltutmish","Balban","Alauddin Khilji","Muhammad bin Tughlaq"],"Alauddin Khilji established a comprehensive market control system with fixed prices for commodities and appointed Shahna-i-Mandi to regulate markets.","बाजार नियंत्रण और मूल्य विनियमन नीति किसने लागू की?",["इल्तुतमिश","बलबन","अलाउद्दीन खिलजी","मुहम्मद बिन तुगलक"],"अलाउद्दीन खिलजी ने वस्तुओं के निश्चित मूल्यों के साथ व्यापक बाजार नियंत्रण प्रणाली स्थापित की और नियमन हेतु शहना-ए-मंडी नियुक्त किए।")]
H1 += [Q("A",M,Y24,"Correct order of Delhi Sultanate dynasties?",["Slave→Khilji→Tughlaq→Sayyid→Lodi","Khilji→Slave→Tughlaq→Lodi→Sayyid","Slave→Tughlaq→Khilji→Lodi→Sayyid","Tughlaq→Slave→Khilji→Sayyid→Lodi"],"Chronological order: Slave/Mamluk (1206-1290), Khilji (1290-1320), Tughlaq (1320-1414), Sayyid (1414-1451), Lodi (1451-1526).","दिल्ली सल्तनत के राजवंशों का सही क्रम?",["गुलाम→खिलजी→तुगलक→सैयद→लोदी","खिलजी→गुलाम→तुगलक→लोदी→सैयद","गुलाम→तुगलक→खिलजी→लोदी→सैयद","तुगलक→गुलाम→खिलजी→सैयद→लोदी"],"कालानुक्रम: गुलाम/ममलूक (1206-1290), खिलजी (1290-1320), तुगलक (1320-1414), सैयद (1414-1451), लोदी (1451-1526)।")]
H1 += [Q("B",M,Y24,"Qutub Minar was completed by which Sultan?",["Qutb-ud-din Aibak","Iltutmish","Alauddin Khilji","Firoz Shah Tughlaq"],"Qutb-ud-din Aibak started Qutub Minar. Iltutmish completed it. Firoz Shah Tughlaq later repaired and added floors after lightning damage.","कुतुब मीनार किस सुल्तान ने पूरा करवाया?",["कुतुब-उद-दीन ऐबक","इल्तुतमिश","अलाउद्दीन खिलजी","फिरोज शाह तुगलक"],"कुतुब-उद-दीन ऐबक ने कुतुब मीनार शुरू करवाया। इल्तुतमिश ने इसे पूरा किया। फिरोज शाह तुगलक ने बाद में बिजली क्षति के बाद मरम्मत कर ऊपरी मंजिलें जोड़ीं।")]
H1 += [Q("C",E,Y24,"First Battle of Panipat: Babur defeated?",["Rana Sanga","Hemu","Ibrahim Lodi","Sher Shah Suri"],"Babur defeated Ibrahim Lodi on April 21, 1526 at Panipat, using superior artillery and Tuluguma tactics.","पानीपत का पहला युद्ध: बाबर ने किसे हराया?",["राणा सांगा","हेमू","इब्राहिम लोदी","शेर शाह सूरी"],"बाबर ने 21 अप्रैल 1526 को पानीपत में श्रेष्ठ तोपखाने और तुलुगुमा रणनीति से इब्राहिम लोदी को हराया।")]
H1 += [Q("A",M,Y24,"Mansabdari system was introduced by?",["Akbar","Babur","Humayun","Shah Jahan"],"Akbar introduced the Mansabdari system around 1570, a military-cum-administrative ranking system with zat (personal rank) and sawar (cavalry maintained).","मनसबदारी प्रणाली किसने शुरू की?",["अकबर","बाबर","हुमायूं","शाहजहां"],"अकबर ने लगभग 1570 में जात (व्यक्तिगत रैंक) और सवार (घुड़सवार सेना) वाली सैन्य-प्रशासनिक मनसबदारी प्रणाली शुरू की।")]
H1 += [Q("B",M,Y24,"Din-i-Ilahi syncretic religion was founded by?",["Jahangir","Akbar","Shah Jahan","Aurangzeb"],"Akbar founded Din-i-Ilahi (Divine Faith) in 1582, combining elements of Hinduism, Islam, Christianity, and Zoroastrianism.","दीन-ए-इलाही की स्थापना किसने की?",["जहांगीर","अकबर","शाहजहां","औरंगज़ेब"],"अकबर ने 1582 में हिंदू धर्म, इस्लाम, ईसाई धर्म और पारसी धर्म के तत्वों को मिलाकर दीन-ए-इलाही (ईश्वरीय धर्म) की स्थापना की।")]
H1 += [Q("D",E,Y24,"Taj Mahal was built in memory of?",["Nur Jahan","Jahanara","Mumtaz Begum","Mumtaz Mahal"],"Shah Jahan built the Taj Mahal at Agra in memory of his beloved wife Mumtaz Mahal. Construction lasted from 1632 to approximately 1653.","ताजमहल किसकी स्मृति में बनवाया गया?",["नूरजहां","जहांआरा","मुमताज बेगम","मुमताज महल"],"शाहजहां ने अपनी प्रिय पत्नी मुमताज महल की स्मृति में आगरा में ताजमहल बनवाया। निर्माण 1632 से लगभग 1653 तक चला।")]
H1 += [Q("C",H,Y24,"Which Mughal emperor was called Zinda Pir (Living Saint)?",["Akbar","Jahangir","Aurangzeb","Shah Jahan"],"Aurangzeb was called Zinda Pir due to his strict adherence to Islamic orthodoxy. He re-imposed Jizya tax and banned music at court.","किस मुगल सम्राट को जिंदा पीर (जीवित संत) कहा जाता था?",["अकबर","जहांगीर","औरंगज़ेब","शाहजहां"],"औरंगज़ेब को उनकी सख्त इस्लामी रूढ़िवादिता के कारण जिंदा पीर कहा जाता था। उन्होंने जजिया कर पुनः लागू किया और दरबार में संगीत पर प्रतिबंध लगाया।")]
H1 += [Q("B",M,Y24,"Fatehpur Sikri was built by which Mughal emperor?",["Humayun","Akbar","Jahangir","Shah Jahan"],"Akbar built Fatehpur Sikri near Agra as his capital (1571-1585). It was later abandoned due to water shortage.","फतेहपुर सीकरी किस मुगल सम्राट ने बनवाया?",["हुमायूं","अकबर","जहांगीर","शाहजहां"],"अकबर ने आगरा के पास फतेहपुर सीकरी को अपनी राजधानी के रूप में बनवाया (1571-1585)। पानी की कमी के कारण बाद में इसे छोड़ दिया गया।")]
H1 += [Q("D",H,Y23,"Second Battle of Panipat (1556) was fought between?",["Babur and Ibrahim Lodi","Humayun and Sher Shah","Akbar and Rana Pratap","Akbar (Bairam Khan) and Hemu"],"Akbar's regent Bairam Khan led the Mughal army to victory over Hemu (Hem Chandra Vikramaditya). Akbar was only 13 years old at the time.","पानीपत का दूसरा युद्ध (1556) किनके बीच लड़ा गया?",["बाबर और इब्राहिम लोदी","हुमायूं और शेरशाह","अकबर और राणा प्रताप","अकबर (बैरम खां) और हेमू"],"अकबर के संरक्षक बैरम खां के नेतृत्व में मुगल सेना ने हेमू (हेम चंद्र विक्रमादित्य) पर विजय प्राप्त की। अकबर उस समय केवल 13 वर्ष के थे।")]
H1 += [Q("A",M,Y24,"Buland Darwaza was built by?",["Akbar","Shah Jahan","Jahangir","Aurangzeb"],"Akbar built the magnificent Buland Darwaza at Fatehpur Sikri in 1601 to commemorate his conquest of Gujarat.","बुलंद दरवाजा किसने बनवाया?",["अकबर","शाहजहां","जहांगीर","औरंगज़ेब"],"अकबर ने गुजरात विजय के उपलक्ष्य में 1601 में फतेहपुर सीकरी में भव्य बुलंद दरवाजा बनवाया।")]
H1 += [Q("C",M,Y24,"Jahangir's autobiography is titled?",["Akbarnama","Humayunnama","Tuzuk-i-Jahangiri","Shahjahannama"],"Tuzuk-i-Jahangiri is the memoirs of Emperor Jahangir, written by himself. Akbarnama was written by Abul Fazl about Akbar.","जहांगीर की आत्मकथा का शीर्षक क्या है?",["अकबरनामा","हुमायूंनामा","तुज़ुक-ए-जहांगीरी","शाहजहांनामा"],"तुज़ुक-ए-जहांगीरी सम्राट जहांगीर के स्वयं द्वारा लिखित संस्मरण हैं। अकबरनामा अबुल फज़ल ने अकबर के बारे में लिखा।")]
H1 += [Q("B",H,Y24,"Nur Jahan's original name was?",["Arjumand Banu Begum","Mehr-un-Nisa","Jodha Bai","Manmati"],"Mehr-un-Nisa was given the title Nur Jahan (Light of the World) by Emperor Jahangir after their marriage in 1611.","नूरजहां का मूल नाम क्या था?",["अर्जुमंद बानू बेगम","मेहर-उन-निसा","जोधा बाई","मनमती"],"मेहर-उन-निसा को सम्राट जहांगीर ने 1611 में विवाह के बाद नूरजहां (दुनिया की रोशनी) की उपाधि दी।")]
H1 += [Q("B",E,Y24,"The Red Fort (Lal Qila) in Delhi was built by?",["Akbar","Shah Jahan","Humayun","Aurangzeb"],"Shah Jahan built the Red Fort between 1639-1648 when he shifted his capital from Agra to Shahjahanabad (present-day Old Delhi).","दिल्ली का लाल किला किसने बनवाया?",["अकबर","शाहजहां","हुमायूं","औरंगज़ेब"],"शाहजहां ने 1639-1648 के बीच अपनी राजधानी आगरा से शाहजहानाबाद (वर्तमान पुरानी दिल्ली) स्थानांतरित करते समय लाल किला बनवाया।")]
H1 += [Q("B",M,Y24,"Shivaji was crowned Chhatrapati in which year?",["1670","1674","1680","1646"],"Shivaji Maharaj was formally crowned as Chhatrapati on June 6, 1674 at Raigad Fort in a grand ceremony presided over by scholar Gaga Bhatt.","शिवाजी का छत्रपति के रूप में राज्याभिषेक कब हुआ?",["1670","1674","1680","1646"],"शिवाजी महाराज का विधिवत राज्याभिषेक 6 जून 1674 को रायगढ़ किले में विद्वान गागा भट्ट की अध्यक्षता में भव्य समारोह में हुआ।")]
H1 += [Q("D",H,Y23,"Third Battle of Panipat (1761) was fought between?",["British and Marathas","Mughals and Marathas","Sikhs and Marathas","Marathas and Ahmad Shah Abdali"],"The Maratha Empire under Sadashivrao Bhau fought against Ahmad Shah Abdali (Durrani). The Marathas suffered a devastating defeat that changed India's power dynamics.","पानीपत का तीसरा युद्ध (1761) किसके बीच हुआ?",["अंग्रेज़ों और मराठों","मुगलों और मराठों","सिखों और मराठों","मराठों और अहमद शाह अब्दाली"],"सदाशिवराव भाऊ के नेतृत्व में मराठा साम्राज्य ने अहमद शाह अब्दाली (दुर्रानी) से युद्ध किया। मराठों की विनाशकारी हार ने भारत की शक्ति गतिशीलता बदल दी।")]
H1 += [Q("C",E,Y24,"The 1857 Revolt began at which location?",["Delhi","Kanpur","Meerut","Lucknow"],"The Revolt of 1857 started on May 10, 1857 at Meerut when sepoys refused to use greased cartridges rumored to contain cow and pig fat.","1857 का विद्रोह कहां से शुरू हुआ?",["दिल्ली","कानपुर","मेरठ","लखनऊ"],"1857 का विद्रोह 10 मई 1857 को मेरठ में शुरू हुआ जब सिपाहियों ने गाय और सूअर की चर्बी युक्त कारतूसों का उपयोग करने से इनकार कर दिया।")]
H1 += [Q("A",M,Y24,"Who led the 1857 revolt at Kanpur?",["Nana Sahib","Tantia Tope","Rani Lakshmibai","Kunwar Singh"],"Nana Sahib (born Dhondu Pant), the adopted son of the last Peshwa Baji Rao II, led the revolt at Kanpur.","कानपुर में 1857 के विद्रोह का नेतृत्व किसने किया?",["नाना साहब","तांत्या टोपे","रानी लक्ष्मीबाई","कुंवर सिंह"],"अंतिम पेशवा बाजीराव द्वितीय के दत्तक पुत्र नाना साहब (जन्म नाम धोंडू पंत) ने कानपुर में विद्रोह का नेतृत्व किया।")]
H1 += [Q("B",E,Y24,"Rani Lakshmibai was associated with which revolt center?",["Kanpur","Jhansi","Delhi","Bareilly"],"Rani Lakshmibai of Jhansi was one of the leading figures of the 1857 revolt. She died fighting British forces at Gwalior on June 17, 1858.","रानी लक्ष्मीबाई किस विद्रोह केंद्र से जुड़ी थीं?",["कानपुर","झांसी","दिल्ली","बरेली"],"झांसी की रानी लक्ष्मीबाई 1857 के विद्रोह की प्रमुख नेत्रियों में से एक थीं। वे 17 जून 1858 को ग्वालियर में ब्रिटिश सेना से लड़ते हुए शहीद हुईं।")]
H1 += [Q("A",M,Y24,"Indian National Congress was founded in which year?",["1885","1890","1900","1882"],"INC was founded on December 28, 1885 at Gokuldas Tejpal Sanskrit College, Bombay. W.C. Bonnerjee was the first president with 72 delegates attending.","भारतीय राष्ट्रीय कांग्रेस की स्थापना कब हुई?",["1885","1890","1900","1882"],"INC की स्थापना 28 दिसंबर 1885 को गोकुलदास तेजपाल संस्कृत कॉलेज, बॉम्बे में हुई। पहले अध्यक्ष डब्ल्यू.सी. बनर्जी थे और 72 प्रतिनिधि उपस्थित थे।")]
H1 += [Q("D",H,Y23,"Who presided over the 1929 Lahore INC session declaring Purna Swaraj?",["Mahatma Gandhi","Motilal Nehru","Subhas Chandra Bose","Jawaharlal Nehru"],"Jawaharlal Nehru presided over the Lahore session in December 1929 where the historic Purna Swaraj (complete independence) resolution was passed. January 26, 1930 was celebrated as the first Independence Day.","1929 के लाहौर INC अधिवेशन की अध्यक्षता किसने की?",["महात्मा गांधी","मोतीलाल नेहरू","सुभाष चंद्र बोस","जवाहरलाल नेहरू"],"जवाहरलाल नेहरू ने दिसंबर 1929 में लाहौर अधिवेशन की अध्यक्षता की जहां ऐतिहासिक पूर्ण स्वराज प्रस्ताव पारित हुआ। 26 जनवरी 1930 को पहला स्वतंत्रता दिवस मनाया गया।")]
H1 += [Q("C",E,Y24,"The slogan 'Do or Die' was given by?",["Subhas Chandra Bose","Jawaharlal Nehru","Mahatma Gandhi","Sardar Patel"],"Mahatma Gandhi gave the 'Do or Die' (Karo ya Maro) call on August 8, 1942 at the Bombay AICC session, launching the Quit India Movement.","'करो या मरो' का नारा किसने दिया?",["सुभाष चंद्र बोस","जवाहरलाल नेहरू","महात्मा गांधी","सरदार पटेल"],"महात्मा गांधी ने 8 अगस्त 1942 को बॉम्बे AICC अधिवेशन में 'करो या मरो' का आह्वान किया और भारत छोड़ो आंदोलन शुरू किया।")]
H1 += [Q("B",M,Y24,"The Dandi March began on which date?",["March 12, 1931","March 12, 1930","April 6, 1930","April 12, 1930"],"The Salt March started from Sabarmati Ashram on March 12, 1930. Gandhi and 78 followers reached Dandi on April 6, covering 241 miles, and broke the salt law.","दांडी मार्च (नमक सत्याग्रह) कब शुरू हुआ?",["12 मार्च 1931","12 मार्च 1930","6 अप्रैल 1930","12 अप्रैल 1930"],"नमक मार्च 12 मार्च 1930 को साबरमती आश्रम से शुरू हुआ। गांधी और 78 अनुयायी 241 मील चलकर 6 अप्रैल को दांडी पहुंचे और नमक कानून तोड़ा।")]
H1 += [Q("C",M,Y24,"The Cabinet Mission (1946) had how many members?",["2","3","4","5"],"The Cabinet Mission consisted of 3 British Cabinet ministers: Sir Stafford Cripps, Lord Pethick-Lawrence, and A.V. Alexander.","कैबिनेट मिशन (1946) में कितने सदस्य थे?",["2","3","4","5"],"कैबिनेट मिशन में 3 ब्रिटिश कैबिनेट मंत्री थे: सर स्टैफोर्ड क्रिप्स, लॉर्ड पेथिक-लॉरेंस और ए.वी. अलेक्जेंडर।")]
H1 += [Q("B",E,Y24,"British PM when India gained independence?",["Winston Churchill","Clement Attlee","Neville Chamberlain","Harold Macmillan"],"Clement Attlee of the Labour Party was the British PM. He sent the Cabinet Mission and appointed Lord Mountbatten as the last Viceroy.","भारत की स्वतंत्रता के समय ब्रिटिश प्रधानमंत्री कौन थे?",["विंस्टन चर्चिल","क्लेमेंट एटली","नेविल चैंबरलेन","हेरोल्ड मैकमिलन"],"लेबर पार्टी के क्लेमेंट एटली ब्रिटिश प्रधानमंत्री थे। उन्होंने कैबिनेट मिशन भेजा और लॉर्ड माउंटबेटन को अंतिम वायसराय नियुक्त किया।")]
H1 += [Q("C",M,Y24,"Who drew the Radcliffe Line?",["Lord Mountbatten","Stafford Cripps","Cyril Radcliffe","A.V. Alexander"],"Sir Cyril Radcliffe chaired the Boundary Commission that drew the Radcliffe Line on August 17, 1947, partitioning Punjab and Bengal between India and Pakistan.","रैडक्लिफ रेखा किसने खींची?",["लॉर्ड माउंटबेटन","स्टैफोर्ड क्रिप्स","सिरिल रैडक्लिफ","ए.वी. अलेक्जेंडर"],"सर सिरिल रैडक्लिफ ने सीमा आयोग की अध्यक्षता की और 17 अगस्त 1947 को भारत-पाकिस्तान के बीच पंजाब और बंगाल का विभाजन करती रैडक्लिफ रेखा खींची।")]
H1 += [Q("D",M,Y24,"Who is known as the Iron Man of India?",["Mahatma Gandhi","Jawaharlal Nehru","B.R. Ambedkar","Sardar Vallabhbhai Patel"],"Sardar Patel earned this title for his crucial role in integrating over 560 princely states into the Indian Union after independence.","भारत का लौह पुरुष किसे कहा जाता है?",["महात्मा गांधी","जवाहरलाल नेहरू","बी.आर. अंबेडकर","सरदार वल्लभभाई पटेल"],"स्वतंत्रता के बाद 560 से अधिक रियासतों को भारतीय संघ में शामिल करने की महत्वपूर्ण भूमिका के लिए सरदार पटेल को यह उपाधि मिली।")]
# More history
H1 += [Q("B",M,Y24,"Gautama Buddha attained enlightenment at?",["Lumbini","Bodh Gaya","Sarnath","Kushinagar"],"Bodh Gaya (Bihar) under the Bodhi tree. Four great events: Lumbini (birth), Bodh Gaya (enlightenment), Sarnath (first sermon), Kushinagar (Mahaparinirvana).","गौतम बुद्ध को ज्ञान की प्राप्ति कहां हुई?",["लुंबिनी","बोध गया","सारनाथ","कुशीनगर"],"बोध गया (बिहार) में बोधि वृक्ष के नीचे। चार महान घटनाएं: लुंबिनी (जन्म), बोध गया (ज्ञान), सारनाथ (प्रथम उपदेश), कुशीनगर (महापरिनिर्वाण)।")]
H1 += [Q("D",H,Y23,"The First Buddhist Council was held at?",["Vaishali","Pataliputra","Kashmir","Rajgriha"],"The First Buddhist Council was convened at Rajgriha in 483 BCE under King Ajatashatru, presided over by Mahakasyapa. The Tripitaka was compiled here.","प्रथम बौद्ध संगीति कहां हुई?",["वैशाली","पाटलिपुत्र","कश्मीर","राजगृह"],"प्रथम बौद्ध संगीति 483 ई.पू. में राजगृह में राजा अजातशत्रु के संरक्षण में बुलाई गई, जिसकी अध्यक्षता महाकश्यप ने की। त्रिपिटक का संकलन यहीं हुआ।")]
H1 += [Q("C",E,Y24,"Who was the 24th Tirthankara of Jainism?",["Rishabhanatha","Parshvanatha","Mahavira","Neminatha"],"Lord Mahavira (Vardhamana) was the 24th and last Tirthankara. He was born in Kundagrama near Vaishali around 540 BCE.","जैन धर्म के 24वें तीर्थंकर कौन थे?",["ऋषभनाथ","पार्श्वनाथ","महावीर","नेमिनाथ"],"भगवान महावीर (वर्धमान) 24वें और अंतिम तीर्थंकर थे। उनका जन्म लगभग 540 ई.पू. में वैशाली के पास कुंडग्राम में हुआ।")]
H1 += [Q("A",M,Y24,"Who founded the Shunga dynasty?",["Pushyamitra Shunga","Agnimitra","Vasumitra","Devabhuti"],"Pushyamitra Shunga assassinated the last Mauryan ruler Brihadratha and founded the Shunga dynasty in 185 BCE. He was originally the commander-in-chief of the Mauryan army.","शुंग राजवंश की स्थापना किसने की?",["पुष्यमित्र शुंग","अग्निमित्र","वसुमित्र","देवभूति"],"पुष्यमित्र शुंग ने अंतिम मौर्य शासक बृहद्रथ की हत्या कर 185 ई.पू. में शुंग राजवंश की स्थापना की। वे मूलतः मौर्य सेना के सेनापति थे।")]
H1 += [Q("D",H,Y24,"The Sanskrit play Mudrarakshasa was written by?",["Kalidasa","Banabhatta","Bharavi","Vishakhadatta"],"Vishakhadatta wrote Mudrarakshasa, a historical play about Chandragupta Maurya's rise to power with the help of Chanakya.","संस्कृत नाटक मुद्राराक्षस किसने लिखा?",["कालिदास","बाणभट्ट","भारवि","विशाखदत्त"],"विशाखदत्त ने मुद्राराक्षस लिखा, जो चाणक्य की सहायता से चंद्रगुप्त मौर्य के सत्ता में उत्थान पर आधारित ऐतिहासिक नाटक है।")]
H1 += [Q("C",E,Y24,"Simon Commission arrived in India in?",["1925","1927","1928","1930"],"The Simon Commission arrived in 1928 with no Indian members. It was boycotted across India with the slogan 'Simon Go Back'.","साइमन कमीशन भारत कब आया?",["1925","1927","1928","1930"],"साइमन कमीशन 1928 में बिना किसी भारतीय सदस्य के आया। पूरे भारत में 'साइमन वापस जाओ' के नारे से इसका बहिष्कार किया गया।")]
H1 += [Q("B",H,Y23,"'Dilli Chalo' call was given by?",["Mahatma Gandhi","Subhas Chandra Bose","Jawaharlal Nehru","Bhagat Singh"],"Subhas Chandra Bose, as the leader of the Indian National Army (INA), gave the stirring call 'Dilli Chalo' (March to Delhi) to his soldiers.","'दिल्ली चलो' का आह्वान किसने दिया?",["महात्मा गांधी","सुभाष चंद्र बोस","जवाहरलाल नेहरू","भगत सिंह"],"सुभाष चंद्र बोस ने भारतीय राष्ट्रीय सेना (INA) के नेता के रूप में अपने सैनिकों को 'दिल्ली चलो' का प्रेरक आह्वान दिया।")]
H1 += [Q("A",E,Y24,"Who was the Viceroy of India during Partition?",["Lord Mountbatten","Lord Wavell","Lord Linlithgow","Lord Irwin"],"Lord Louis Mountbatten was the last Viceroy of British India (1947-48) and oversaw the partition and independence of India.","विभाजन के समय भारत के वायसराय कौन थे?",["लॉर्ड माउंटबेटन","लॉर्ड वेवेल","लॉर्ड लिनलिथगो","लॉर्ड इरविन"],"लॉर्ड लुई माउंटबेटन ब्रिटिश भारत के अंतिम वायसराय (1947-48) थे और उन्होंने भारत के विभाजन और स्वतंत्रता की देखरेख की।")]
H1 += [Q("D",M,Y24,"The Rowlatt Act was passed in which year?",["1915","1917","1918","1919"],"The Rowlatt Act (1919) allowed imprisonment without trial. Gandhi launched the Rowlatt Satyagraha against this repressive measure.","रॉलेट एक्ट किस वर्ष पारित हुआ?",["1915","1917","1918","1919"],"रॉलेट एक्ट (1919) बिना मुकदमे के कारावास की अनुमति देता था। गांधी ने इस दमनकारी कानून के खिलाफ रॉलेट सत्याग्रह शुरू किया।")]
H1 += [Q("C",M,Y24,"Khilafat Movement was launched in which year?",["1917","1918","1919","1920"],"The Khilafat Movement (1919) was led by the Ali brothers (Shaukat Ali and Muhammad Ali) and supported by Mahatma Gandhi.","खिलाफत आंदोलन किस वर्ष शुरू हुआ?",["1917","1918","1919","1920"],"खिलाफत आंदोलन (1919) अली बंधुओं (शौकत अली और मुहम्मद अली) के नेतृत्व में शुरू हुआ और इसे महात्मा गांधी का समर्थन प्राप्त था।")]
H1 += [Q("B",E,Y24,"Jallianwala Bagh massacre took place on?",["April 13, 1918","April 13, 1919","April 13, 1920","April 13, 1921"],"On April 13, 1919 (Baisakhi day), General Reginald Dyer ordered troops to fire on an unarmed gathering at Jallianwala Bagh, Amritsar, killing hundreds.","जलियांवाला बाग हत्याकांड कब हुआ?",["13 अप्रैल 1918","13 अप्रैल 1919","13 अप्रैल 1920","13 अप्रैल 1921"],"13 अप्रैल 1919 (बैसाखी के दिन) को जनरल रेजिनाल्ड डायर ने अमृतसर के जलियांवाला बाग में निहत्थी भीड़ पर गोली चलाने का आदेश दिया, जिसमें सैकड़ों लोग मारे गए।")]

tot += expand(os.path.join(BASE,"indian-history.json"), H1)
print("Indian History: COMPLETE")
